### ISSUE TITLE
Add LinkedIn Tracking to Website

### ISSUE THREAD

**Issue by lindsaymarolich** [pulumi/pulumi-hugo#1005]
Could we please get the LinkedIn tag installed to the site for tracking -- we will need to add the following to the global footer of the site including signup conversion:

<script type=“text/javascript”>
_linkedin_partner_id = “1315796";
window._linkedin_data_partner_ids = window._linkedin_data_partner_ids || [];
window._linkedin_data_partner_ids.push(_linkedin_partner_id);
</script><script type=“text/javascript”>
(function(l) {
if (!l){window.lintrk = function(a,b){window.lintrk.q.push([a,b])};
window.lintrk.q=[]}
var s = document.getElementsByTagName(“script”)[0];
var b = document.createElement(“script”);
b.type = “text/javascript”;b.async = true;
b.src = “https://snap.licdn.com/li.lms-analytics/insight.min.js”;
s.parentNode.insertBefore(b, s);})(window.lintrk);
</script>
<noscript>
<img height=“1" width=“1” style=“display:none;” alt=“” src=“https://px.ads.linkedin.com/collect/?pid=1315796&fmt=gif” />
</noscript>

**Comment by cnunciato** [comment]
@lindsaymarolich Ok, I've enabled this in Segment (using the partner ID you provided in the issue), so I _think_ it's working. Let me know when you're able to confirm this is working as you'd expect, and I'll close this out.

**Comment by lindsaymarolich** [comment]
Thanks @cnunciato! I will check into this to verify.

**Comment by cnunciato** [comment]
@lindsaymarolich Following up to make sure we're good. If so, can we close?

**Comment by lindsaymarolich** [comment]
@cnunciato yes -- thanks for the reminder!
