### ISSUE TITLE
add info for "what is pulumi, why does it matter, why should I care?" 

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#1033]
there was an ask that came in via community slack related to "what is pulumi, why does it matter, why should I care?"  content for folks that are new to the space and new to pulumi

**Comment by susanev** [comment]
@nimbinatus or @cnunciato is this something either of you would be interested in taking on?

**Comment by nimbinatus** [comment]
Hm. I'm not sure I can take it on right now, but I get the value. If @cnunciato can't take it right now, we could at least get it on the radar for planning.

**Comment by susanev** [comment]
no urgency at all, whenev and only if yall are interested.

**Comment by lukehoban** [comment]
The main docs landing page is made up of  “What is Pulumi?” And “Why Pulumi?”  Do these not answer the question?

https://www.pulumi.com/docs/

**Comment by susanev** [comment]
this was a request from community slack, so id imagine that for them it didn't or they didn't know about that page. i can dm you more context.

**Comment by susanev** [comment]
im going to close this out, marketing folks can follow up and open a new issue if yall would like.
