### ISSUE TITLE
developer advocate updates to marketing website

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#1051]
## overview

ask from Kat: each developer advocate needs their own page to highlight information about them and links to their content.

current state: we have this page https://www.pulumi.com/community/developer-advocates/ though it does not exist in the navigation

@katcosgrove can provide a list of content that's needed on the individual developer advocate pages, along with a rough wireframe which communicates her thoughts

this needs to launch before the end of the quarter

## design needs
- add the developer advocates page to navigation; for now, i suggest adding it to the footer somewhere though w can explore the top nav after we redesign it
- design a way to get to each individual developer advocates page from the developer advocates page
- design a template for the individual developer advocates pages
   - needs to be able to easily get back to the developers advocates page
   - needs a space for each developer advocate to bio/intro themselves
   - needs a space for links to their content
   - needs a space for ways to get in contact with them
   - other needs should be identified in collaboration with Kat

### stretch goal
- design the content for the community page in collaboration with all of the developer advocates and @aaronkao and link to it in the footer instead of the developer advocate page

## eng needs
- after we have designed a template we will need to implement it, but then each developer advocate should be able to open their own pr which adds content to their individual page

## collaborators
@katcosgrove is the main point of content from the developer advocates, and should be included in design reviews

**Comment by anita-trimbur** [comment]
## [Figma Link](https://www.figma.com/file/5ob0PX54tpzhVSjBWAmCyV/Developer-Advocate-Pages?node-id=73%3A61)

## Designs and Changes

- The Developer Advocates page will link to individual profiles for each DA via new "View Profile" secondary buttons.
- Additionally the Developer Advocates page will be linked in the site footer. This is subject to change in the near future with the expected addition of a Community page. 
- Individual DA profiles will contain a profile image, social media handles, a short about blurb, a giveaway sign-up form, a list of upcoming and recent speaking engagements, recent blog posts, and a contact form. 
- Users will be able to toggle between DA profiles using a dropdown at the top of the page, or return to the main Developer Advocates page.
- The contact form on the main Developer Advocates page will move into individual profiles so each DA can be reached directly. 
- Responsive resizing and additional state changes viewable in Figma. See annotations for pertinent callouts.

![Standard view](https://user-images.githubusercontent.com/97129308/158269224-23c8e8bb-e33a-40f3-9206-b9cb22dc2bfe.png)

## Handoff Notes

- Recent Blog posts sections should have a maximum of 6 posts
- Past speaking events should be capped at the 10 most recent events
- For mobile resizing, speaking table can scroll horizontally when a fourth column is introduced for recent events

**Comment by anita-trimbur** [comment]
@zchase Tagging in case I haven't linked you this issue yet! If anything is unclear message me whenever!

**Comment by susanev** [comment]
this was completed (but still needs ux review) in https://github.com/pulumi/pulumi-hugo/pull/1281 and https://github.com/pulumi/pulumi-hugo/pull/1289
