### ISSUE TITLE
Explain imperative vs declarative better

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-hugo#1081]
The interplay between imperative code and how Pulumi's declarative engine / goal state works is not clearly explained anywhere, and yet is a very important point for new users to understand.

The closest is probably [How it Works](https://www.pulumi.com/docs/intro/concepts/how-pulumi-works/) but this page is quite lengthy and isn't oriented around these points, as much as it is giving a broad brush architectural overview of various key system pieces.

We should clearly describe this somewhere prominently.

**Comment by susanev** [comment]
@nimbinatus @cnunciato possibly another candidate for yalls backlogs

**Comment by cnunciato** [comment]
Yep, noted and placed on the Content backlog.
