### ISSUE TITLE
Fix all target="_blank" to include rel="noopener"

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi-hugo#1083]
Per https://developers.google.com/web/tools/lighthouse/audits/noopener - we should have rel="noopener" wherever we have target="_blank"

**Comment by cnunciato** [comment]
This is now the [default behavior](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#browser_compatibility) of the `a` tag where `target="blank"`, so we can close this.
