### ISSUE TITLE
Missing API overviews for awsx and eks

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-hugo#1089]
These should be updated to have useful package level overviews:
- [x] AWSX: https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/awsx/
- [x] EKS: https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/eks/

We should consider aligning with the style of https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/.

**Comment by stack72** [comment]
We can close this out now as AWSX is in the registry
