### ISSUE TITLE
Issues on Pulumi with Kubernetes/go getting started

### ISSUE THREAD

**Issue by scoulomb** [pulumi/pulumi-hugo#1094]
File: [docs/get-started/kubernetes/modify-program.md](https://www.pulumi.com/docs/get-started/kubernetes/modify-program/)

When trying Pulumi with go and Kubernetes (Minikube flavour), I faced 2 main issues:

- `pulumi config set isMinikube false/true` did not seems to work and had no effect.  It is always set to false. So the feType is always "Loadbalancer". I had to hardcode it.
- Then I was not able to get the service clusterIP (wondering if it is already updated yet when retrieved by Pulumi), but I managed to get the service port which is provided in input : cf. https://github.com/scoulomb/myIaC/blob/master/pulumi/quickstart/main.go#L79

Is it a known issue?

**Comment by desteves** [comment]
Please note the k8s getting started / go guide has been recently updated. I believe the [update](https://github.com/pulumi/pulumi-hugo/pull/3412) addresses the original concerns in this issue - (1) the value of `isMinikube` flag does matter. 

```go
	feType := "LoadBalancer"
		if isMinikube {
			feType = "ClusterIP"
		}

``` 

and (2)  get the service clusterIP - This is dependent on having a LB and reflected when assigning a value to the `pulumi.StringOutput` named `ip` .

**Comment by desteves** [comment]
@pulumi/docs I believe we can close this now given the recent update (see my previous msg). Thoughts?

**Comment by scottslowe** [comment]
The code from the current Kubernetes Getting Started guide works as expected, no problems. When using AWS EKS, there’s a slight delay while the DNS records for the ELB are propagated, but that’s all. Note that testing this on AWS EKS doesn’t test the code path that finds an IP address in the load balancer status field (AWS uses a DNS name), but I see no reason to believe that the code would not work equally well on AKS or GKE (both of which use IP addresses).
