### ISSUE TITLE
Redirect support page to support portal 

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-hugo#111]
Currently https://www.pulumi.com/support/ is a contact form which goes to a generic email alias when users should use https://support.pulumi.com/ instead.

The `/support` page is still linked from various locations and indexed by search engines. Can we 301 redirect (or whichever status is best) to https://support.pulumi.com/ to help users get to support faster?

**Comment by susanev** [comment]
@clstokes https://www.pulumi.com/support/ isnt linked to anywhere on the website. we can remove the page, do you want a redirect added?

**Comment by clstokes** [comment]
@susanev Yes, /support is indexed by search engines, so I think we should have a redirect for it.
