### ISSUE TITLE
Add work out to unselect active stacks to page /docs/intro/concepts/stack/

### ISSUE THREAD

**Issue by SaraDPH** [pulumi/pulumi-hugo#1140]
A customer mentioned to be unable to unselect an active stack, see issue [#9070](https://github.com/pulumi/pulumi/issues/9070) and no documentation about the mechanism in https://www.pulumi.com/docs/intro/concepts/stack/

Could a note be added to the documentation about this topic and how to go around it?
He mentions "If I manually edit or remove files in rm -rf ~/.pulumi/workspaces/*, my stack selection is reset."

FYI @zchase @Frassle

**Comment by susanev** [comment]
i dont think we should document that workaround in our docs.

relatedly it might be good to document in what situations we add workarounds to docs, and in what situations those remain in issues (which is mostly what we've done in the past). curious on @cnunciato's thoughts as well.

**Comment by Frassle** [comment]
Commented on slack but I think it would be really easy to add a `pulumi stack unselect` command. We should just add and document that rather than the workaround. Good little issue for @Zaid-Ajaj to pick up.

**Comment by cnunciato** [comment]
Agree with @Frassle and was just about to write the same. 😄 

Thank you @SaraDPH for keeping an eye out for things like this!

**Comment by cnunciato** [comment]
Closing as `pulumi stack unselect` now exists:

```
$ pulumi stack --help
Manage stacks and view stack state

A stack is a named update target, and a single project may have many of them.
Each stack has a configuration and update history associated with it, stored in
the workspace, in addition to a full checkpoint of the last known good update.

Usage:
  pulumi stack [flags]
  pulumi stack [command]

Available Commands:
  change-secrets-provider Change the secrets provider for a stack
  export                  Export a stack's deployment to standard out
  graph                   Export a stack's dependency graph to a file
  history                 Display history for a stack
  import                  Import a deployment from standard in into an existing stack
  init                    Create an empty stack with the given name, ready for updates
  ls                      List stacks
  output                  Show a stack's output properties
  rename                  Rename an existing stack
  rm                      Remove a stack and its configuration
  select                  Switch the current workspace to the given stack
  tag                     Manage stack tags
  unselect                Resets stack selection from the current workspace
```
