### ISSUE TITLE
docs updates for service saml sso improvements

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#1159]
### Problem description

we need to update the docs related to the saml sso improvements

### Suggestions for a fix

- [ ] mention the reauth requirement, why it happens, what folks need to do to adjust it and what users need to do to move past it

**Comment by cnunciato** [comment]
@EvanBoyle Any chance someone from the Service Team could take this, or if not, provide some explanation here on the issue that we can use to get this documented properly?

**Comment by susanev** [comment]
this was docs work that never got done after the saml sso changes. we need to document when reauth will happen (and why), and how folks can adjust the time limit. i can go digging for issues if yall need, let me know.

**Comment by cnunciato** [comment]
Thanks @susanev, yeah anything you could share would be helpful, as I don't have much context on this one.

**Comment by susanev** [comment]
@cnunciato found these two..
https://github.com/pulumi/pulumi-service/pull/5902
https://github.com/pulumi/pulumi-service/pull/5656

if this doesn't give you enough context we may want to consider asking Evan if this is an appropriate thing to get Chris' help on.

**Comment by susanev** [comment]
closing this; i believe the cloud team has their own tracking issues for this
