### ISSUE TITLE
How do you install `pulumi` on cli?

### ISSUE THREAD

**Issue by nojvek** [pulumi/pulumi-hugo#1163]
File: [docs/intro/languages/javascript.md](https://www.pulumi.com/docs/intro/languages/javascript/)

Docs say run `pulumi new javascript` but no mention of how to install it in first place.

`npm install -g pulumi` doesn't work.

So your Step 1 is missing.

**Comment by susanev** [comment]
this page now has get started information; and we also now have download and install in the left nav so closing as fixed; but def pls let me know if you have any more feedback
