### ISSUE TITLE
redesign docs landing page

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#1169]
this is spread across many issue, ill get it cleaned up later today

related: https://github.com/pulumi/pulumi-hugo/issues/1149
[doc about a usability study](https://docs.google.com/document/d/1zRfYvXddKbxZMAo1ZZerYeYwbjwl9Nzy63POACyub54/edit?usp=sharing)
[in-progress figma file](https://www.figma.com/file/eSe3rvnOP2kVHgIZhZrlKq/docs-landing?node-id=0%3A1)

**Comment by jonelleb** [comment]
@susanev - I am interested in doing this but I'd like to talk to you about it before starting just so I'm clear. I can schedule a meeting later this week or maybe we can go over it in one of our UX meetings? Thanks.

**Comment by jonelleb** [comment]
# Design Goals
Redesign [Docs landing page](https://www.pulumi.com/docs) so that users can easily access any of the links from the left nav. Also, we want to shorten the "What is Pulumi?" text and have a link to the Registry (the Registry is linked from the top navigation, but we want to call it out on this Docs landing page as well).

**Comment by jonelleb** [comment]
# [Figma File](https://www.figma.com/file/eSe3rvnOP2kVHgIZhZrlKq/docs-landing?node-id=359%3A21)
# [Figma Prototype](https://www.figma.com/proto/eSe3rvnOP2kVHgIZhZrlKq/docs-landing?page-id=359%3A20&node-id=359%3A21&viewport=313%2C48%2C0.18&scaling=scale-down-width&starting-point-node-id=359%3A21)
*(see prototype to see an example of how 'read more/read less' expand and collapse links should work)*

<img width="567" alt="Screen Shot 2022-03-22 at 3 48 01 PM" src="https://user-images.githubusercontent.com/100616532/159700735-0d7acce7-57fa-4648-83fa-96f8e6687712.png">

<img width="536" alt="Screen Shot 2022-03-22 at 3 48 10 PM" src="https://user-images.githubusercontent.com/100616532/159700770-6525796d-a63f-42f9-9164-7075d4ed88ae.png">

# Design Changes
- 'Get Started' button has been added to the right of Pulumi Documentation header.
- 'Read more' link - when clicked, expands the text above it.
- 'Read less' link - when clicked, expands the text above it.
- Circles in Getting Started, Reference, and Converters cards are using Pulumi brand colors but at 50% transparency.
- New Pulumi Registry callout design:
<img width="586" alt="Screen Shot 2022-03-23 at 7 43 09 AM" src="https://user-images.githubusercontent.com/100616532/159701861-f7078d94-6de2-48f6-a8c7-2115e1f783c6.png">

# Engineer Notes
- Comments have been added in Figma but please feel free to reach out with any questions or concerns. 

Thanks!

**Comment by susanev** [comment]
one note about this for @kimberleyamackenzie is that ive dropped both cloud providers and API reference on this page even though they are still in the docs left nav. im doing this because we have the registry callout and because both of those navigate to registry anyway. but if you have concerns or if that makes anything more difficult feel free to add them back in.
