### ISSUE TITLE
Update contact page to help user with best contact option

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-hugo#119]
### Context 

We frequently have people use our general Contact Us form for technical support items and also don't distinguish between sales inquiries and general inquiries.

### Suggestion 

Our page at https://www.pulumi.com/contact/ should provide help people get to the right form or option as quick as possible - e.g.:
- **Technical Support** - should link to https://support.pulumi.com/
- **Sales** - should take the user to a sales-specific form (can be the same generic form for now)
- **Other Inquiries** - should take the user to a generic contact form (likely the same form used right now)

### Mockup

To better illustrate what I have in mind, here's a mockup. I'm not tied to the styling or wording, but do think it should be this simple.

![image](https://user-images.githubusercontent.com/293763/115635486-ab856a00-a2c0-11eb-93e9-a1b05b8ac9fc.png)

**Comment by clstokes** [comment]
Kind of related... https://github.com/pulumi/pulumi-hugo/issues/111.

**Comment by susanev** [comment]
ill do the designs for this page, this week

**Comment by susanev** [comment]
@clstokes is technical support available for everyone? or only paying customers?

**Comment by tusharshahrs** [comment]
@susanev,
  The technical support is available for everyone.

**Comment by susanev** [comment]
its poor usability to link to the same form presented as two different options, so I did not include the sales, and other inquires as separate items. since we also have the support page linked in the same location as the contact us form, I also did not make support and sales the same prominence, take a look at the designs in #180 and let me know what you think.

**Comment by clstokes** [comment]
@susanev @zchase I looked at the design in #180 and think we need a stronger "callout" between the different options. It certainly does not have to be my proposed design, but I think people will miss the link to the support portal in what's in #180.

Also (new requirement!), after talking to Kevin, we'll want a "New user and want to talk to an engineer?" option, and sales and general contact. The forms for the last two might look like the same form, but they go to different internal distros with different expectations on who responds and when (hence the two paths).

So we want four options to ensure the user gets to what they need the quickest (not these exact phrases): 
- Existing user that needs technical help? link to zendesk
- New user and want to talk to an engineer? link to (likely new) contact us form
- Talk to sales? link to existing sales form
- General question? link to (likely new) contact form

**Comment by susanev** [comment]
Hi yall, can we design 1 form that allows folks to select the reason they are contacting us? Or do we really need separate forms for all the different options?
