### ISSUE TITLE
Add an errors reference page

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-hugo#1206]
It would be helpful to have a page describing all (common) CLI and SDK errors, what they mean, and how to remediate them.

**Comment by toriancrane** [comment]
I'm thinking this is the [Troubleshooting Guide](https://www.pulumi.com/docs/support/troubleshooting/)?

**Comment by cnunciato** [comment]
Yep, we think this is addressed by that guide. Closing.

**Comment by joeduffy** [comment]
I am ok with closing, however, the area I still think could use improving are:

* Doing an audit of _all_ error messages issued by the CLI and/or SDKs and ensuring each has
    1. A unique error code
    2. An error messages that appears verbatim on some reference page, so it's "guaranteed" to show up when Googling
    3. An explanation with examples where appropriate

**Comment by cnunciato** [comment]
I love this. Do we actually emit unique error codes?

**Comment by toriancrane** [comment]
I made a new [Issue](https://github.com/pulumi/pulumi-hugo/issues/3217) to capture the need for the improvements.
