### ISSUE TITLE
Animated background dots are squished

### ISSUE THREAD

**Issue by joebentaylor1995** [pulumi/pulumi-hugo#123]
In the hero and other places on the website (where used) the multicoloured dots look squished and not like the example provided in [Codepen](https://codepen.io/levinriegner/pen/1c2ce4c9f82b56e45208698110c147c1):

## Expected behavior
The dots should be perfect circles.
<img width="403" alt="Screenshot 2021-04-22 at 13 57 12" src="https://user-images.githubusercontent.com/54585427/115718036-a7b22000-a372-11eb-94cd-7de69a091347.png">

## Current behavior
The circles are squished on the vertical axis.
<img width="354" alt="Screenshot 2021-04-22 at 13 50 25" src="https://user-images.githubusercontent.com/54585427/115717914-8c471500-a372-11eb-996f-444920522156.png">

It seems the `mask-size` that has been coded doesnt match the [example](https://codepen.io/levinriegner/pen/1c2ce4c9f82b56e45208698110c147c1)

## Steps to reproduce
1. Go to the [website](https://www.pulumi.com/)
2. Observe

## Environment
Chrome Version 90.0.4430.85 (Official Build) (x86_64)
Macbook Pro 15"

**Comment by susanev** [comment]
closing as we do not have the time or people to work on them right now. when that changes we can reopen them.
