### ISSUE TITLE
Multiple Docs links

### ISSUE THREAD

**Issue by joebentaylor1995** [pulumi/pulumi-hugo#124]
Having two docs links within the header will cause split traffic and user confusion.

## Expected behavior
To have only one `Docs` link.
Based on your decisions t put this in the main nav, I would suggest removing this from the sub nav.
This may only be a small thing to report, but this could be the difference between a user converting or bouncing due to having to think about what to click.

<img width="589" alt="Screenshot 2021-04-22 at 14 03 00" src="https://user-images.githubusercontent.com/54585427/115718880-75ed8900-a373-11eb-9ee8-a12955d9f3ab.png">

## Current behavior
Two links to the same place
<img width="587" alt="Screenshot 2021-04-22 at 14 02 04" src="https://user-images.githubusercontent.com/54585427/115718750-57878d80-a373-11eb-9099-37b1f73c1b1a.png">

## Steps to reproduce
1. Go to the [website](https://www.pulumi.com/)

**Comment by susanev** [comment]
this was intentional, we will revist in the future if needed.
