### ISSUE TITLE
Example for create new user seems wrong

### ISSUE THREAD

**Issue by meagancojocar** [pulumi/pulumi-hugo#1244]
File: [themes/default/content/docs/reference/service-rest-api/_index.md](https://www.pulumi.com/docs/reference/service-rest-api/)

I'll pretty sure the example to [create a new user access token](https://www.pulumi.com/docs/reference/service-rest-api/#create-user-access-token) is incorrect (the path).

    curl \
      -H 'Accept: application/vnd.pulumi+8' \
      -H 'Content-Type: application/json' \
      -H 'Authorization: token $PULUMI_ACCESS_TOKEN' \
      --request POST \
      --data '{"description":"{description}"}' \
      https://api.pulumi.com/api/**stacks/{organization}/{project}/{stack}/tags**

Guessing here but my assumption is it should be:

    curl \
      -H 'Accept: application/vnd.pulumi+8' \
      -H 'Content-Type: application/json' \
      -H 'Authorization: token $PULUMI_ACCESS_TOKEN' \
      --request CREATE \
      https://api.pulumi.com/api/user/tokens/{tokenId}

**Comment by meagancojocar** [comment]
Hey @cnunciato are you able to validate this is actually wrong and that what I have is accurate? If so I can make the PR to fix.

**Comment by susanev** [comment]
@meagancojocar customer eng created and is responsible for this page i believe. may be worth asking over in their channel.

**Comment by cnunciato** [comment]
Hey @meagancojocar, thanks for noticing this! It should actually be the following -- everything's right* but the path:

```
curl \
  -H 'Accept: application/vnd.pulumi+8' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: token $PULUMI_ACCESS_TOKEN' \
  --request POST \
  --data '{"description":"{description}"}' \
  https://api.pulumi.com/api/user/tokens
```

\* ...not counting that ~all of the examples on the page need to be updated to use double-quotes instead of single quotes (which prevent the `PULUMI_ACCESS_TOKEN` environment variable from being expanded, and lead to confusing errors). 

I'll get a PR up for the single-quote problem if you want to submit for this one!

**Comment by cnunciato** [comment]
https://github.com/pulumi/pulumi-hugo/pull/1246

**Comment by susanev** [comment]
this was fixed
