### ISSUE TITLE
Header flexibility with smaller screens

### ISSUE THREAD

**Issue by joebentaylor1995** [pulumi/pulumi-hugo#125]
When changing browser size to a smaller width which some notebooks will be, the menu items start to go onto two lines as the padding between each item doesnt reduce.

## Expected behavior
Using `display: flex;` & `justify-content: space-between;` would allow for the header to be perfectly spaces for smaller devices.
<img width="1050" alt="Screenshot 2021-04-22 at 14 06 30" src="https://user-images.githubusercontent.com/54585427/115719394-f44a2b00-a373-11eb-8761-28730465979e.png">

## Current behavior
Items go into two lines
<img width="1117" alt="Screenshot 2021-04-22 at 14 03 56" src="https://user-images.githubusercontent.com/54585427/115719434-fca26600-a373-11eb-8e55-52f0604c1e06.png">

## Steps to reproduce
1. Go to the [website](https://www.pulumi.com/)
2. Reduce browser size to anything above `1024px` and below `1280px`

## Affected feature
Header

**Comment by susanev** [comment]
closing as we do not have the time or people to work on them right now. when that changes we can reopen them.
