### ISSUE TITLE
Header alignment mismatch

### ISSUE THREAD

**Issue by joebentaylor1995** [pulumi/pulumi-hugo#126]
The header and sub-nav do not line up with each other

## Expected behavior
Perfectly aligned together
<img width="182" alt="Screenshot 2021-04-22 at 14 11 51" src="https://user-images.githubusercontent.com/54585427/115720236-c6b1b180-a374-11eb-897f-516be5ad13e1.png">

## Current behavior
Sub-nav goes past the length of the main-nav
<img width="178" alt="Screenshot 2021-04-22 at 14 12 00" src="https://user-images.githubusercontent.com/54585427/115720304-dcbf7200-a374-11eb-8850-8dd9e8b04f0c.png">

## Steps to reproduce
1. Go to the [website](https://www.pulumi.com/)

## Affected feature
Header

**Comment by susanev** [comment]
closing as we do not have the time or people to work on them right now. when that changes we can reopen them.
