### ISSUE TITLE
Document where to get the "type" token for imports

### ISSUE THREAD

**Issue by Frassle** [pulumi/pulumi-hugo#1265]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Raised in [community slack](https://pulumi-community.slack.com/archives/C84L4E3N1/p1648257992751949):

> VS: Hi guys,
I'm going to import some existing resources with pulumi import [type] [name] [id] command. How can I get type for my resources?
> AN: If you look at the documentation of your provider, on each resource you can see an example of an import command that gives you the type of the resource.
> FW: You can also check the SDK code. https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/s3/bucket.ts#L334 for example is the type for old aws providers s3 bucket resource.
> VS: Thanks, guys.
It's not obvious from the first look. Especially, if you're a newbie to Pulumi. It'd would be great to add this to pulumi import doc (https://www.pulumi.com/docs/reference/cli/pulumi_import/)
> PS: Hey VS - if we update the docs to say “look for the Import sections in the API Docs for the type” would that help - we can also link to an example

We should document this better. Possibly both here in the docs site and as part of the import command itself.

**Comment by cnunciato** [comment]
As part of this, we should document (e.g., in the Concepts docs) what a type token is so we have something to link to when discussing them.
