### ISSUE TITLE
Add gitpod support for this repo 

### ISSUE THREAD

**Issue by mattstratton** [pulumi/pulumi-hugo#1272]
I think that if we added gitpod support to this repo, it would make it a lot easier for folks to make changes, submit content, etc etc without having to worry about local tooling/enviroments etc

fwiw, I have done this for a different hugo setup (devopsdays) and it's been well received, so I have some ideas :)

**Comment by susanev** [comment]
thx for the suggestion! we wont be able to prioritize at this time, so gonna close out.
