### ISSUE TITLE
Comparison page misrepresents AWS CDK

### ISSUE THREAD

**Issue by phitoduck** [pulumi/pulumi-hugo#1275]
File: [themes/default/content/docs/intro/vs/cloud-template-transpilers.md](https://www.pulumi.com/docs/intro/vs/cloud-template-transpilers/)

Hi there, I think there are some points on this page that are misleading about AWS CDK. 

My team is in the process of comparing Pulumi and CDK right now to decide which to standardize on. We love the fact that Pulumi doesn't use CloudFormation stacks, unlike CDK. However, this article makes some claims about CDK that are not true (maybe they were at one point and have since been added).

> Troposphere and CDK compile down to YAML and are therefore limited in what they can express. ...

> Pulumi also supports going beyond what you can express in YAML, such as building and publishing a Docker container image, authoring serverless functions in code, automating packaging and versioning of code, and so on.

CDK supports each of these things quite seamlessly:

- Building and publishing docker images: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecr_assets.DockerImageAsset.html
- Automating packaging and versioning of code. If this is a reference to serverless functions, CDK has this: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.AssetCode.html
- Authoring serverless functions in code, I know that the TypeScript version of CDK allows for this inline. I don't have experience with this in Python.

The rootski project uses CDK to publish a fairly complex AWS Lambda function with C-binaries, etc: https://github.com/rootski-io/rootski/blob/trunk/infrastructure/iac/aws-cdk/backend/rootski_backend_cdk/lambda_rest_api/stacks/lambda_rest_api.py

AWS CDK doesn't just compile to YAML. It compiles to "Cloud Assembly" which is a combination of CloudFormation templates and other assets such as packaged lambda functions that are created at `cdk synth` time. Then, at `cdk deploy` time, assets such as lambda functions and docker images are uploaded, and the CloudFormation templates are deployed.

### 1. Rich component library that saves oodles of developer time

I feel I should share a frustration with Pulumi that my team is experiencing. A huge strength over Pulumi that we are seeing with CDK is the amount of community support. I'm talking specifically about pre-written constructs that abstract away many common solutions that Pulumi (currently) seems to require you to implement yourself.

Want an S3 bucket that auto deletes objects after 30 days? Just set `auto_delete=True` and a duration in the `aws_s3.Bucket` construct, and you'll get a Lambda function with perfectly tight IAM permissions to do that for you. Want a DNS validated ACM cert? Use the `aws_acm.DNSValidatedCertificate` construct and CDK will create a lambda to validate the cert for you. In both cases, the API is extremely light and the functionality works beautifully. That's a lot of tested code I don't have to write 😄.

I imagine that CDK is where AWS puts their cookie-cutter solutions to make them available to the community.

If Pulumi had these "constructs" written (as "components") that we could easily use--especially in Python--our team wouldn't hesitate to choose Pulumi and be freed of the dreaded CloudFormation API and its deadlocks. But AWS CDK currently saves us weeks of developer time via their pre-written constructs. `awsx` looks like it may eventually grow into something like CDK in this way, but it does not seem to be there yet, and to my knowledge it is not available in Python. Am I missing something?

### 2. Helper methods

Pulumi and CDK both represent AWS resources as classes. Pulumi stops at implementing a constructor. CDK does more. It adds (sometimes) dozens of helper methods to add common configuration to the resources. See the [`aws_s3.Bucket` reference](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3.Bucket.html#methods) for examples.

Here's a cool one:

```python
my_bucket = aws_s3.Bucket(...)
my_iam_role = aws_iam.Role(...)
my_bucket.grant_read(my_iam_role)
```

This adds policies to an IAM role that are perfectly tight for granting read access to the S3 bucket. You can also plug in an IAM group or IAM user object! Super cool. The helper methods go far beyond IAM permissions, but even just the IAM permissions capabilities save lots of time.

## Wrap up

AWS has done the work to design these features. Are there barriers to simply reading the CDK codebase and adopting these methods and abstracted solutions into a pre-written library of Pulumi components?

At any rate, please update this page to make it clearer what CDK is capable of. Pulumi has plenty to admire. There is no need to misrepresent the truth about your competitors to attract masses of disenchanted CloudFormation users.

Likewise, if I'm misunderstanding Pulumi's offerings in any way, I'll happily take back anything incorrect that I said.

Thanks for reading this :)

Eric

**Comment by gshpychka** [comment]
Related: https://github.com/pulumi/pulumi-hugo/issues/926

**Comment by susanev** [comment]
@phitoduck thank you so much for writing up this detailed feedback! we are in the process of getting this information updated.

**Comment by gshpychka** [comment]
> @phitoduck thank you so much for writing up this detailed feedback! we are in the process of getting this information updated.

Thanks, can you give us an ETA or at least some insight into how you're prioritizing this?

**Comment by cnunciato** [comment]
@gshpychka It's actually being worked on presently! Several of these pages hadn't been updated in a while, and we happened to already be at work updating them when this issue came in. I'll report back here when they're ready.

**Comment by gshpychka** [comment]
> @gshpychka It's actually being worked on presently! Several of these pages hadn't been updated in a while, and we happened to already be at work updating them when this issue came in. I'll report back here when they're ready. 

That's great to hear. I have to say, though, that's pretty much exactly what you said three months ago in the linked issue, that's why I asked about ETA/prioritization.

**Comment by cnunciato** [comment]
Ah, I see someone did say that. I'm not sure what happened there. But since I'm the person who's actually working on this now, I can promise it'll be out soon! 😄 Thank you for your patience.

**Comment by gshpychka** [comment]
> Ah, I see someone did say that. I'm not sure what happened there. But since I'm the person who's actually working on this now, I can promise it'll be out soon! 😄 Thank you for your patience.

Yup my bad, it wasn't you who said it three months ago. Anyway, looking forward to it.

**Comment by susanev** [comment]
@phitoduck  apologies for the delay! last night we shipped changes to both of these pages. pls take a look and let us know if this addresses your feedback. thank you!

- https://www.pulumi.com/docs/intro/vs/cloud-template-transpilers/aws-cdk/
- https://www.pulumi.com/docs/intro/vs/cloud-templates/cloudformation/

**Comment by susanev** [comment]
@gshpychka apologies for the lack of updates until now. i did raise this internally as soon as you opened the issue and have been working with folks to make the changes. im looking forward to hearing your feedback on the updates!

**Comment by cnunciato** [comment]
Hi friends! As @susanev mentioned, we've shipped some updates to these docs, and they seem to address these points, so I'm going to close this issue for now. But if you feel like something still needs fixing, feel free to reopen with any details you like, and we'll get 'em looked into. Thanks again for the excellent feedback -- we really appreciate it.
