### ISSUE TITLE
Equivalent Go syntax to create encrypted storage class

### ISSUE THREAD

**Issue by AshKash** [pulumi/pulumi-hugo#1278]
I'm new Pulumi, this page shows how an encrypted storage class can be created using Typescript:
File: [themes/default/content/docs/guides/crosswalk/kubernetes/control-plane.md](https://www.pulumi.com/docs/guides/crosswalk/kubernetes/control-plane/)

What is the equivalent Go syntax for it? Since The Go SDK has `StorageClassArgs` but it does not have any encryption specific argument. Should they be untyped string arguments - using `Parameters pulumi.StringMapInput`. Any example will be helpful. The default way to create a cluster keeps everything unencrypted and this is not secure for many usecases. So have sane defaults will be really nice.

**Comment by lukehoban** [comment]
There is an `Encrypted` property on `StorageClassArgs` in the Go SDK. You should be able to use that. 

https://github.com/pulumi/pulumi-eks/blob/master/sdk/go/eks/pulumiTypes.go#L2013

Does that work?
