### ISSUE TITLE
Doc request : Document under Get Started, with DigitalOcean cloud provider

### ISSUE THREAD

**Issue by rahul3v** [pulumi/pulumi-hugo#1291]
It's been helpful if you can provide few examples using DigitalOcean cloud provider, with Kubernetes, under Get Started section

**Comment by susanev** [comment]
@cnunciato pinging you on this, since i know you were just doing content work with digitalocean so thought you might have thoughts.

**Comment by cnunciato** [comment]
Closing this as a duplicate of #1813.
