### ISSUE TITLE
Aggregate 3rd party Pulumi articles under case studies

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/pulumi-hugo#1296]
### Problem description

- Customer/Vendor articles in regards to Pulumi are not visible on pulumi.com
  -  [Building Fauna’s GDPR-compliant distributed and scalable database infrastructure with Pulumi](https://fauna.com/blog/building-faunas-gdpr-compliant-distributed-and-scalable-database)
  - [Skai Migrates and Modernizes with Pulumi and AWS](https://aws.amazon.com/partners/success/skai-pulumi/)

Add a link at the bottom of the page called [case studies](https://www.pulumi.com/case-studies/) to these artices.

**Comment by susanev** [comment]
@gthuang @zchase do yall know if this still needs to be done?

**Comment by gthuang** [comment]
Fauna & Skai case studies have been added to case studies page.
