### ISSUE TITLE
Recurring Task: Review, Fix and Track up/down votes feedback

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-hugo#1297]
We have voting buttons and freeform feedback fields on the docs site - and get a good amount of feedback from these.  We should on a regular basis review these and either fix or open tracking issues for top pieces of feedback.

**Comment by susanev** [comment]
@lukehoban @cnunciato is this issue still useful to yall? would it be helpful to have some sort of process in place around this instead of an issue?

**Comment by cnunciato** [comment]
@susanev Thanks, we have a few of these kinds of recurring docs-quality-related issues that we should set up processes for. I'll keep this issue open to track creating that process.
