### ISSUE TITLE
builds are failing with JavaScript heap out of memory

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#1325]
`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

`FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory`

**Comment by pierskarsenbarg** [comment]
Error in action: https://github.com/pulumi/pulumi-hugo/runs/5869060371?check_suite_focus=true#step:7:1151
