### ISSUE TITLE
[Learn] Cloud Fundamentals pathway

### ISSUE THREAD

**Issue by nimbinatus** [pulumi/pulumi-hugo#1329]
See https://github.com/pulumi/pulumi-hugo/tree/devrel/pulumi-cloud-fundamentals

Ref: #803

**Comment by aaronkao** [comment]
Question - should this be the pathway that walks through Blueprints

**Comment by scottslowe** [comment]
Assigning this to @interurban; this may be an issue you'll want to close as not planned once you and Torian sort out the plan for tutorials.
