### ISSUE TITLE
[Learn] Layout changes

### ISSUE THREAD

**Issue by nimbinatus** [pulumi/pulumi-hugo#1331]
Once we get more pathways, need to explore layout changes.

Ref branch: https://github.com/pulumi/pulumi-hugo/tree/devrel/learn-layout-updates

Ref: #911

**Comment by scottslowe** [comment]
Assigning this to @interurban---this may be an issue you'll want to close as not planned once you and Torian sort out the plan for tutorials.

**Comment by scottslowe** [comment]
Closing as not planned per team consensus
