### ISSUE TITLE
Design Updates to Marketing Site (Home Page & Site Footer)

### ISSUE THREAD

**Issue by jonelleb** [pulumi/pulumi-hugo#1337]
# Overview

*Please note that this issue is still in review - nothing has been decided on.*

As a Hackathon project, I explored adding animation to the Pulumi marketing site - particularly the Home page, adding a carousel with a gradent animation to the top of the page and changing the design of the footer throughout the site. We'd like to explore possibly updating the site with these changes.

**Header:**

![Screen Shot 2022-04-08 at 12 02 47 PM](https://user-images.githubusercontent.com/100616532/162488572-4a58d4b1-aa3b-4d2a-9412-8fd570d5b098.png)

**Footer:**
![Screen Shot 2022-04-08 at 12 03 04 PM](https://user-images.githubusercontent.com/100616532/162488595-d9741e6a-daa2-47c8-b9e2-1e66bd82cd26.png)

**Comment by jonelleb** [comment]
[Figma File](https://www.figma.com/file/t5hdRP0GSHMILLs03U6zA3/Jonelle---Hackathon-2022?node-id=24%3A1199)
[Figma Prototype](https://www.figma.com/proto/t5hdRP0GSHMILLs03U6zA3/Jonelle---Hackathon-2022?page-id=0%3A1&node-id=32%3A1191&starting-point-node-id=32%3A1191&show-proto-sidebar=1)

**Comment by cnunciato** [comment]
Closing as this is unplanned as of now, but feel free to reopen if you think we should revisit this!
