### ISSUE TITLE
Error in help file

### ISSUE THREAD

**Issue by MattacksWTW** [pulumi/pulumi-hugo#1349]
File: [themes/default/content/docs/intro/concepts/inputs-outputs.md](https://www.pulumi.com/docs/intro/concepts/inputs-outputs/)

Text says "For example, say you want to create a URL from hostname and port output values. You can do this using apply and all.", but the example does not use `all`

**Comment by susanev** [comment]
@MattacksWTW thank you for opening this issue! we will get to it as soon as we can, we also accept pull requests if you happen to have the time.

https://github.com/pulumi/pulumi-hugo/edit/master/themes/default/content/docs/intro/concepts/inputs-outputs.md

**Comment by cnunciato** [comment]
Closing as the example [now includes `all`](https://www.pulumi.com/docs/concepts/inputs-outputs/#outputs-and-strings).
