### ISSUE TITLE
AWS Getting Started Docs need updating with new Bucket resources

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-hugo#1381]
### Problem description

Since the changes in the [v5.0.0](https://github.com/pulumi/pulumi-aws/releases/tag/v5.0.0) version of the AWS provider that deprecated serveral bucket resources, the getting started guide [here](https://www.pulumi.com/docs/get-started/aws/deploy-changes/) are now out of date, and throw deprecation warnings to new users.

This is a very poor user experience for users new to Pulumi, as they immediately get a scary warning message when they provision their first resources.

We should update these resources to use the new `BucketV2` resources.

### Affected product version(s)

> pulumi-aws v5.0.0

**Comment by cnunciato** [comment]
Depending on how https://github.com/pulumi/pulumi-aws/issues/1911, we might want to do these first. separately.

**Comment by cnunciato** [comment]
We've fixed the deprecation messages that were leading to this experience, so closing this issue for now. We can file another issue for any changes we want to make to existing getting-started examples.
