### ISSUE TITLE
learn menu issue

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#1485]
it looks like because the resources description is 2 lines, it is forcing the case studies to also have that extra space, which looks pretty weird since it does not need it; can we fix this so having a 2 line description in one column does not effect the other column?

<img width="724" alt="white-space-sad" src="https://user-images.githubusercontent.com/5489125/167068270-5acab5a1-c331-4236-ac80-b1076541e751.png">

**Comment by susanev** [comment]
@sean1588 is this something you can easily fix?

**Comment by susanev** [comment]
we can also just shorten the resources description i suppose, @gthuang any thoughts on that? ill add im not sure what session means there? is that workshops?

**Comment by sean1588** [comment]
Yeah I think it _might_ be easy if we can make the menu box a bit wider, so the resources text won't wrap and fit on one line. If not, it may be complicated with getting flex to layout the items the way we desire. I think if I make it a tad wider and/or decrease the padding slightly it may work.

**Comment by sean1588** [comment]
Ok I made it like 2px wider and it was enough to get it to stop wrapping. 

![Screenshot from 2022-05-05 22-04-09](https://user-images.githubusercontent.com/16751381/167070381-afe981f3-faed-43ba-b526-d7b503f152a3.png)

Going to open a PR now.
