### ISSUE TITLE
How to provide input for inline programs

### ISSUE THREAD

**Issue by hansarh** [pulumi/pulumi-hugo#1487]
I would like to know more about the possibility of how to provide inputs for programs when you execute them. If I f.ex want to provide some inputs to config on the resources to be built. And be able to give my stack it's own name when I run the program.

File: [themes/default/content/docs/guides/automation-api/getting-started-automation-api.md](https://www.pulumi.com/docs/guides/automation-api/getting-started-automation-api/)

**Comment by susanev** [comment]
hi @hansarh would you mind asking your question either in [community slack](https://slack.pulumi.com/?_gl=1*4f9jzn*_ga*MTkyMDcyNDU1OS4xNTk4NDU5MTUz*_ga_FQHG5CVY2D*MTY1MTk0MDA5OC4zNy4xLjE2NTE5NDEwOTUuNjA.), or in [github discussions](https://github.com/pulumi/pulumi/discussions)?

**Comment by susanev** [comment]
closing this out, @hansarh pls reach out in community slack or github discussions if ya have more questions.
