### ISSUE TITLE
Make glossary more discoverable

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi-hugo#1500]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Might we want to make glossary more discoverable?

https://www.pulumi.com/docs/reference/glossary/

Ideas include moving glossary into the Architecture and Concepts page to make it more visible or adding a hover on key concepts in docs that may be confusing or new to users? Came from a discussion with  @jkodroff @AaronFriel @lblackstone

**Comment by susanev** [comment]
@dixler I def support moving it up into the intro parent in the left nav. As a note we also have a separate glossary from the learn menu in the marketing top nav.

**Comment by jkodroff** [comment]
@susanev How do you feel about a hover-over, maybe implemented via a shortcode? Would be a lot of work to implement consistently across all of the docs, but was the best UX we could come up with while we were discussing.

That said, if we _did_ have a shortcode applied consistently for glossary terms (regardless of the visual implementation), it would be much easier to find/replace when our nomenclature changes in the future.

**Comment by cnunciato** [comment]
This could be nice! Shortcodes shouldn’t be necessary, though; we should be able to write these as simple anchor tags (in plain ol’ Markdown) and apply the hover/tooltip  behavior on the client, keeping the Markdown clean.

**Comment by susanev** [comment]
i believe Josh's intent with the shortcode comment is to allow things to be updated globally with ease as our language changes.

@jkodroff let me think about it a bit more and talk with the team, will respond back next week.
