### ISSUE TITLE
Learning page update - typo in 'making a stack configurable'

### ISSUE THREAD

**Issue by pulumi-TH** [pulumi/pulumi-hugo#1506]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

### Affected area/feature

On the learning page (https://www.pulumi.com/learn/building-with-pulumi/stack-outputs/
) in the section “Making a stack configurable” the `pulumi config set` is wrong. The variables are each indicated with “_”, but in the code - or the previous lesson - the variables are camelCase.
This causes the `pulumi up` to fail with reference to missing variable definitions.

**Comment by susanev** [comment]
@nimbinatus is this something you can take a look at?

**Comment by nimbinatus** [comment]
Yep, this is something I can fix. We must have missed it in the PulumiUp updates
