### ISSUE TITLE
Is version required on provider schemas?

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi-hugo#1508]
File: [themes/default/content/docs/guides/pulumi-packages/schema.md](https://www.pulumi.com/docs/guides/pulumi-packages/schema/)

I didn't see a `version` field on the `schema.json`
https://raw.githubusercontent.com/pulumi/pulumi-kubernetes/v3.15.1/provider/cmd/pulumi-resource-kubernetes/schema.json

and was wondering if this was correct or if I was missing something
https://www.pulumi.com/docs/guides/pulumi-packages/schema/#pulumi-package-schema

@viveklak

**Comment by viveklak** [comment]
Pretty certain version is required - even lists it as required in that page. The example should probably be updated.

**Comment by dixler** [comment]
Iirc the schema file is a partial and is joined together with missing keys at runtime.
