### ISSUE TITLE
Add Newsletter Signup to High Traffic Blog Posts

### ISSUE THREAD

**Issue by lindsaymarolich** [pulumi/pulumi-hugo#1530]
Could we please add a newsletter signup form to the bottom of:
https://www.pulumi.com/blog/pulumi-yaml/
https://www.pulumi.com/blog/crosswalk-for-aws-all-languages/

The form is here: https://app.hubspot.com/forms/4429525/027b4c6d-9b73-4ad8-b149-3c8b07fff608/performance

Above form copy:
Sign up for the Pulumi Newsletter 
Stay updated on new product announcements, industry news and upcoming cloud engineering events.

**Comment by zchase** [comment]
Done in https://github.com/pulumi/pulumi-hugo/pull/1535
