### ISSUE TITLE
something happened to the learn heading

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#1534]
- [ ] h1 its much smaller than the rest of the h1s on the website
- [ ] also, why someones here if we can add a line-length or similar to those paragraphs they are much too long and folks will lose their place trying to read them. accessibility best practices recommend 45-75 characters per line
- [ ] and there are 2 h1s on this page, we need exactly 1 h1 per page, that second heading should be an h2

![learn-heading](https://user-images.githubusercontent.com/5489125/169432540-4560a177-e395-4745-9074-cf331be71008.png)

**Comment by susanev** [comment]
@sean1588 any chance you might be able to take this sometime soon? @zchase do you think this happened when the marketing css was pulled out?

**Comment by sean1588** [comment]
yeah I should be able to take it on tomorrow. :+1:

**Comment by cnunciato** [comment]
It looks like this change is the reason for the smaller header text: https://github.com/pulumi/theme/pull/97/files#diff-dfcd873b65c820df18f3f95d14b705ac22f67246c26170d31738f68291550392L115-L116

**Comment by susanev** [comment]
thanks @sean1588!!

mind shortening those paragraphs, so they look a bit better? maybe...

```
Learn all the concepts of Pulumi, along with best practices and architectural patterns.

Each tutorial will step you through exploring Pulumi and completing a project. Start with Pulumi Fundamentals to get comfortable with vocabulary, then try another pathway to explore more!
```
