### ISSUE TITLE
"Get started" on https://www.pulumi.com/kubernetes/ links to AWS getting started

### ISSUE THREAD

**Issue by squaremo** [pulumi/pulumi-hugo#1536]
### What happened?

I was looking for Kubernetes-specific reference docs, and ended up at https://www.pulumi.com/kubernetes/. Out of curiosity I clicked the prominent "Get started" button, and it took me to an AWS-oriented tutorial. I would expect to be taken to a Kubernetes-oriented tutorial.

### Steps to reproduce

- go to https://www.pulumi.com/kubernetes/
- click on "Get started"

### Expected Behavior

Shown a Kubernetes tutorial.

### Actual Behavior

Shown an AWS tutorial.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by susanev** [comment]
oh no! thats a mistake, ill fix that up!
