### ISSUE TITLE
webiny blog links need to get updated

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#1550]
8 links in this blog: https://www.pulumi.com/blog/how-webiny-built-a-serverless-application-framework/ are 404ing; i cant quite figure out what they are supposed to be so someone else should take this

:link: [/blog/how-webiny-built-a-serverless-application-framework/](https://www.pulumi.com/blog/how-webiny-built-a-serverless-application-framework/) → https://github.com/webiny/webiny-js/blob/next/packages/cwp-template-aws/template/apps/admin/pulumi/app.ts (HTTP_404)
:link: [/blog/how-webiny-built-a-serverless-application-framework/](https://www.pulumi.com/blog/how-webiny-built-a-serverless-application-framework/) → https://github.com/webiny/webiny-js/blob/next/packages/cwp-template-aws/template/apps/admin/pulumi/cloudfront.ts (HTTP_404)
:link: [/blog/how-webiny-built-a-serverless-application-framework/](https://www.pulumi.com/blog/how-webiny-built-a-serverless-application-framework/) → https://github.com/webiny/webiny-js/blob/next/packages/cwp-template-aws/template/apps/admin/pulumi/index.ts (HTTP_404)
:link: [/blog/how-webiny-built-a-serverless-application-framework/](https://www.pulumi.com/blog/how-webiny-built-a-serverless-application-framework/) → https://github.com/webiny/webiny-js/blob/next/packages/cwp-template-aws/template/api/pulumi/index.ts#L10-L16 (HTTP_404)
:link: [/blog/how-webiny-built-a-serverless-application-framework/](https://www.pulumi.com/blog/how-webiny-built-a-serverless-application-framework/) → https://github.com/webiny/webiny-js/blob/next/packages/cwp-template-aws/template/api/pulumi/index.ts#L4-L8 (HTTP_404)
:link: [/blog/how-webiny-built-a-serverless-application-framework/](https://www.pulumi.com/blog/how-webiny-built-a-serverless-application-framework/) → https://github.com/webiny/webiny-js/blob/next/packages/cwp-template-aws/template/api/pulumi/prod/dynamoDb.ts#L27 (HTTP_404)
:link: [/blog/how-webiny-built-a-serverless-application-framework/](https://www.pulumi.com/blog/how-webiny-built-a-serverless-application-framework/) → https://github.com/webiny/webiny-js/blob/next/packages/cwp-template-aws/template/api/pulumi/prod/cognito.ts#L70 (HTTP_404)
:link: [/blog/how-webiny-built-a-serverless-application-framework/](https://www.pulumi.com/blog/how-webiny-built-a-serverless-application-framework/) → https://github.com/webiny/webiny-js/blob/next/packages/cwp-template-aws/template/api/pulumi/prod/elasticSearch.ts#L41 (HTTP_404)

**Comment by sean1588** [comment]
Looks like the directories in the github repo that it is referencing got restructured, so the url paths are different. It is looks like it is now under a directory called common for the first 3. the path to the links should be updated to `https://github.com/webiny/webiny-js/blob/next/packages/cwp-template-aws/template/common/apps/admin/pulumi/*`. The last 5 links seem to be spread out across the repo somewhere. I can take a look and try and get these updated and hopefully the code lines match up.
