### ISSUE TITLE
Cloud backend configuration format is not well documented

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-hugo#1614]
It's currently possible to specify the backend inside a stack configuration, but we don't document this outside of a footnote in this page:

https://www.pulumi.com/docs/intro/concepts/project/#pulumi-yaml

We should document this better here:

https://www.pulumi.com/docs/intro/concepts/state/#config-stack

**Comment by lukehoban** [comment]
This was addressed in https://github.com/pulumi/pulumi-hugo/commit/46a491c3ccdce8d043bc1f4a4d69be2136f052b0 and https://github.com/pulumi/pulumi-hugo/commit/cea053358af9525e17f17efea1d43a8ad01c8dba.
