### ISSUE TITLE
Add "Functions" page in Architecture & Concepts

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-hugo#1628]
We don't have a page in our conceptual docs that talks about functions/invokes generally.  We do have a "Getter Functions" page, but that is only a small part of the broader concept on functions.

We should likely rename the "Getter Functions" page to "Functions" and then cover both functions/invokes and Getter Functions.

We also need to decide where to document all the YAML built-in functions.  I'm inclined to believe those should go into https://www.pulumi.com/docs/intro/languages/yaml/ since it is so YAML specific, but they could also in principle go into this "Functions" page.

**Comment by joeduffy** [comment]
On that last note, agree, and I do think it’s worth basically moving the entire YAML format reference from the README into the YAML language docs.

**Comment by squaremo** [comment]
> it’s worth basically moving the entire YAML format reference from the README into the YAML language docs.

-> https://github.com/pulumi/pulumi-hugo/pull/1665 and https://github.com/pulumi/pulumi-yaml/pull/261
