### ISSUE TITLE
Page addition: /product/automation-api

### ISSUE THREAD

**Issue by infin8x** [pulumi/pulumi-hugo#163]
Let's add a landing page for automation API.

## Affected feature

Marketing website

**Comment by susanev** [comment]
does this mean a drop-down under the top-nav item?
if so, do we need to add others there as well?

**Comment by infin8x** [comment]
@lindsaymarolich (or @gthuang?) is going to add more details here

**Comment by susanev** [comment]
cool ill just add a few thoughts here for consideration
- we've had a past pattern of adding new pages that don't appear in any navigation and are difficult to discover
- id love to stop that pattern and strategize about how new pages fit into the current navigation
- we can always shift and change the navigation over time as needed to fit the model of our new pages
