### ISSUE TITLE
vpc.publicSubnetIds is not an Output[] anymore

### ISSUE THREAD

**Issue by bsod90** [pulumi/pulumi-hugo#1632]
File: [themes/default/content/docs/guides/crosswalk/aws/vpc.md](https://www.pulumi.com/docs/guides/crosswalk/aws/vpc/)

`vpc.publicSubnetIds` is now just a promise, and the example doesn't work anymore as `.apply` doesn't exist on the promise.
I think there are quite a lot of outdated examples like this throughout pulumi docs, and I'm not even sure what's the generic approach to refactoring them. Thanks for any help!

**Comment by susanev** [comment]
@bsod90 thx for opening an issue! we will take a look as soon as we can.

**Comment by stack72** [comment]
Hi @bsod90 

Please can you tell me which example isn't working for you? The examples we are listing here on this page are based on v1.0.0-beta.7 of awsx as that is our latest version of awsx made in a multi-language way

Thanks

Paul

**Comment by susanev** [comment]
@bsod90 are you able to give us some more information?

**Comment by bsod90** [comment]
Hi, @susanev 
Sorry, I missed the notification
I believe I was trying to create a machine in a public subnet or something. I think I was copy & pasting this part

<img width="981" alt="image" src="https://user-images.githubusercontent.com/2292499/176591386-f655c379-9eb6-4838-bdc8-bc7816655f54.png">


but as I mentioned in the original message, `vpc.publicSubnetIds` is now a promise and not an Output so, I couldn't just `.apply` it, had to `.then()` it instead.

I believe earlier I was also trying to follow the ACM Cert with validation example and ran into similar issues. Straight copy & paste doesn't work, I ended up significantly refactoring the example.

**Comment by susanev** [comment]
@stack72 thoughts?

**Comment by stack72** [comment]
The issue here is that the guide is written for the new beta version of AWSX not the "default latest" - I think we need to make this more clear in the docs

**Comment by cnunciato** [comment]
Closing as no longer an issue, as the docs and the current version of AWSx are now aligned. As part of https://github.com/pulumi/pulumi-hugo/issues/2281, we'll also be adding programs and testing to make sure this doesn't happen again. Thanks again for the report!
