### ISSUE TITLE
Don't require two spaces after Go template expressions

### ISSUE THREAD

**Issue by cnunciato** [pulumi/pulumi-hugo#1639]
The current Prettier config, as inherited from the [`prettier-plugin-go-template`](https://www.npmjs.com/package/prettier-plugin-go-template) parser, enforces two empty lines after a Go template (`{{ ... }}`) expression:

```
</div>

{{ if something }}
    {{ something_else }}
{{ end }}


<div ...>
```
☝️ 😢 

This isn't great, though, as we don't write our template code like this. We should figure out a way around it such that we're linting for one empty line instead. (Sadly, `prettier-plugin-go-template` doesn't appear to expose this as an option.) (cc @kimberleyamackenzie as we've chatted about it out of band.)

**Comment by cnunciato** [comment]
Related to this, our Prettier errors are pretty terrible:

```
[warn] themes/default/layouts/migrate/terraform.html
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
error Command failed with exit code 1.
```

Is there any way to add something that explains _what_ issues were found? Or is running `make format` and trying to figure it out manually the only option?

**Comment by susanev** [comment]
@cnunciato what do you have to figure out manually? do you not want it making the fixes for you?

**Comment by cnunciato** [comment]
A linter should tell you what needs fixing so that you can fix it. (Whereas formatters are for formatting.)

It might be there’s a config setting somewhere that controls this somehow, but as of now, when this one fails, all it tells you is “something failed” — so your only option is to run the formatter. This makes the lint step pretty useless by itself — especially in PR builds. If the PR job could tell you “Hey, this failed because this one line is too long,” you could fix it on right there on GitHub. But it doesn’t do that, so you can’t. Contrast this with the Markdown linter, which tells you exactly what needs changing. This is what I’d like Prettier to do also.

**Comment by susanev** [comment]
Can you make the next front end working group? A lot of this was decided there so we should open this convo back up if you have concerns.

**Comment by cnunciato** [comment]
Unfortunately I can’t, I’ll be camping. This particular issue, though (about the plug-in we use for HTML formatting), is one I’ve already spoken to @kimberleyamackenzie about.

**Comment by susanev** [comment]
okay, i must have missed that thread.
ill add it to the agenda for the next meeting.
