### ISSUE TITLE
consider exposing aws profile info in get started guide

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#1644]
during a recent usability study, a participant wanted to know if they could use an aws profile instead. they ended up finding the information they needed but it was a bit of a struggle. can we make this information more accessible?

their flow:
- exported aws variables
- wondered if they could use an aws profile instead
- tried a docs search, and could not find anything
- went to google search
- ended up on the config page for aws classic in the registry
- answered their question

[internal clip](https://dovetailapp.com/tags/1T2o1GieqT7LtA9gB9GS01)

**Comment by stack72** [comment]
@susanev should we link to the installation guide there? https://www.pulumi.com/registry/packages/aws/installation-configuration/ this includes the use of `AWS_PROFILE` ?

**Comment by susanev** [comment]
yes, i think we should consider that. that is where the person ended up just in a round-about way.

**Comment by stack72** [comment]
@susanev that installation-configuration page has just been overhauled and I think we should just link to that going forward now?

**Comment by susanev** [comment]
@stack72 its already linked to on that page, i believe the intent of this issue is to mention they can get info about profiles by navigating there. i opened a pr but could not reach alignment, if someone else wants to try pls do!
