### ISSUE TITLE
Issue with tutorial ECS crosswalk

### ISSUE THREAD

**Issue by pmantica3** [pulumi/pulumi-hugo#1647]
File: [themes/default/content/docs/guides/crosswalk/aws/ecs.md](https://www.pulumi.com/docs/guides/crosswalk/aws/ecs/)

This tutorial did not work for me. I am getting a 503 error.

**Comment by stack72** [comment]
Hi @pmantica3 

I'm sorry for the error you are getting here - please can you give us a little more details? What version of Pulumi cli and Pulumi-awsx are you using? What language are you writing your application? Which exact part of the tutorial are you running and causing the 503?

Thanks 

Paul

**Comment by pmantica3** [comment]
Hey I was running the very top tutorial using python. The python tutorial also has another error where it doesn't export the URL. Also, I am not going to use ECS anymore, so I am no longer blocked.

**Comment by stack72** [comment]
Thanks for that information @pmantica3 

Can you confirm the version of awsx you are using?

**Comment by pmantica3** [comment]
pulumi-awsx = "^1.0.0-beta.8"

**Comment by lukehoban** [comment]
Just tried this and it worked for me as expected with `^1.0.0` of AWSX.
