### ISSUE TITLE
next steps after the get started guide

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#1677]
in a usability study, a participant got to the next steps page, and skipped over all that content. at the end of the session, i asked him "how it went" and he talked about things he wanted to learn about next, those things included...
- how state is stored
- secret management
- dependency resolution

should we consider improving access to the docs on these topics at the end of the get started guides?

[internal recording in slack](https://pulumi.slack.com/archives/C85BS3LJZ/p1656463915839979)

**Comment by cnunciato** [comment]
The next-steps changed released yesterday actually call out mention and link to two of these three (state and secrets): https://www.pulumi.com/docs/get-started/aws/next-steps/#how-pulumi-works

**Comment by cnunciato** [comment]
Closing this as complete, as the content we have today links off to these topics.
