### ISSUE TITLE
add ability to have password protected pages

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#168]
this is only an idea, its not currently planned work.

if we add support for password-protected pages, we could move off the hubspot pages. password-protected pages could be built out in the internal repo.

**Comment by susanev** [comment]
why does this go to service team triage?

**Comment by leezen** [comment]
@susanev @infin8x https://github.com/pulumi/docs/pull/5895

**Comment by chrsmith** [comment]
@susanev there are several ways we could solve this technically. It would be helpful if we had a clearer idea of what the specific requirements we are looking for.

- What would we want those pages to be served from? Would they be "intermixed" with non-protected pages on www.pulumi.com? Or would could we have a top-level directory to isolate them, e.g. www.pulumi.com/private/...?
- How would we want to authorize this? A single token given to users? Or "people with the link" (e.g. the access code could be passed via URL query parameter)? Would logging in using your app.pulumi.com identity (e.g. GitHub OAuth -> Pulumi Console -> Pulumi.com) be the preferred way?

**Comment by susanev** [comment]
@chrsmith the intent was to potentially move some of the hubspot pages to our website. they would be pages sent to specific customers. though after chatting with Isaac it seems there is a need to release things at very specific times so this might not be a good move.

it was also motivated by me updating the pages over at info.pulumi.com for the rebrand. which was a big painful chore and I was all ... _ugh, we cant we just use our website_

**Comment by infin8x** [comment]
> why does this go to service team triage?

@susanev I set up the same automation we have in `pulumi-service` in this repo so we make sure to consider issues that appear here.

**Comment by susanev** [comment]
okay idk if everything should really automatically go there though... like id be worried about not having other peoples voices that work out of this repo

**Comment by cnunciato** [comment]
We don't have any near-term need to do this, so closing for now.
