### ISSUE TITLE
make finding the command to install pulumi effortless

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#1682]
we bury the install command multiple pages into the guides
should we be making this easier to find?
suggest the home page, get started landing page, and the footer

multiple folks in the studies struggled to find the install command

[internal slack convo with video](https://pulumi.slack.com/archives/C85BS3LJZ/p1656471539235789)
related issue: https://github.com/pulumi/pulumi-hugo/issues/1163

**Comment by lukehoban** [comment]
If we make the getting started guide a single page (tracked elsewhere), this will be easily discoverable from the prominent “Getting Started” link (today, it is three clicks deep into the getting started guide). 

We could/should also consider placing this command directly on one or both of www.pulumi.com and www.pulumi.com/docs.

**Comment by susanev** [comment]
this is fixed now
