### ISSUE TITLE
[/tf2pulumi] URL field disappears after code generation

### ISSUE THREAD

**Issue by isaac-pulumi** [pulumi/pulumi-hugo#1701]
There is no obvious way to convert more samples after one conversion because the URL field disappears until the user clicks 'code' or 'upload' and then back to 'url'.

**Comment by jkodroff** [comment]
I think this issue might be obsolete as I believe it refers to an earlier design of the page. I do not see a "code" or "upload" button on the current iteration of the page.

**Comment by interurban** [comment]
Thx Josh; confirmed the https://www.pulumi.com/tf2pulumi/ page no longer has a code or upload cta
