### ISSUE TITLE
`pulumi convert` in docs

### ISSUE THREAD

**Issue by meagancojocar** [pulumi/pulumi-hugo#1708]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I noticed when writing the release notes we have no SEO for `pulumi convert` and no overview on what it is. Chatted with Kyle and he's happy to add it but let us know if you have any feedback! 

### Affected area/feature

Planning to add to the [CLI commands documentation](https://www.pulumi.com/docs/reference/cli/).

**Comment by susanev** [comment]
might consider the converters landing page as well https://www.pulumi.com/docs/converters/
and possibly exposing it as a page in that section of the left nav

**Comment by dixler** [comment]
it's visible now.

https://www.pulumi.com/docs/reference/cli/pulumi_convert/
