### ISSUE TITLE
aws get-started mention `aws configure`

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi-hugo#1729]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Users skim the docs and only see code fences and may miss key prose that mentions that pulumi can (basically) use the aws-cli/aws-sdk configuration. This workflow could explain why users have so many error messages around logging into AWS.
- https://github.com/pulumi/home/issues/2113

`aws configure` is the most comfortable way(imo) to configure your machine to interact with AWS since users are already used to doing this with the AWS CLI, AWS SDK, terraform, etc.  and I'm not sure that we're clear enough that this is supported.

adding a code fence that mentions

```bash
$ aws configure
```

could make it much more clear and even adding a note to emphasize that it may not be necessary to log in if they're already logged in. (more advanced users would be able to assume `aws sso login` also works which it does)

**Comment by dixler** [comment]
blocked by #1721

**Comment by stack72** [comment]
@dixler I think as the AWS Installation and Config page has been overhauled, we can close this out now and link to that page from the gett-started guide?

**Comment by dixler** [comment]
I think @cnunciato has a better opinion on this stuff

**Comment by cnunciato** [comment]
Yeah I think we can close this now that we link off to the AWS Config page.
