### ISSUE TITLE
This page documents awx 1.x.. beta version instead of the current stable 0.40.0

### ISSUE THREAD

**Issue by 1oglop1** [pulumi/pulumi-hugo#1731]
File: [themes/default/content/docs/guides/crosswalk/aws/vpc.md](https://www.pulumi.com/docs/guides/crosswalk/aws/vpc/)

**Comment by scottslowe** [comment]
@cnunciato I believe this can be closed as a result of your work updating all the Crosswalk pages, yes?

**Comment by cnunciato** [comment]
Yep, this is done and conforms to the latest version of AWSx.
