### ISSUE TITLE
YAML reference doesn't show where it is in the navigation menu

### ISSUE THREAD

**Issue by squaremo** [pulumi/pulumi-hugo#1748]
If you go to the Pulumi YAML reference https://www.pulumi.com/docs/reference/yaml/, there's no visible entry in the navigation on the left; usually you would see the matching navigation item in boldface.

The URL is /docs/refefence/yaml/, while in the navigation it's at "Reference" / "Pulumi SDK" / "Pulumi YAML" -- and indeed, if you expand that section, "Pulumi YAML" is in boldface. So I wonder if it's just that those don't match up.

**Comment by cnunciato** [comment]
Closing as this has since been fixed.
