### ISSUE TITLE
repo.url not valid in 0.40.0 (latest) of awsx

### ISSUE THREAD

**Issue by notbrain** [pulumi/pulumi-hugo#1766]
File: [themes/default/content/docs/guides/crosswalk/aws/ecr.md](https://www.pulumi.com/docs/guides/crosswalk/aws/ecr/)

Frustrating issue when it's not clear which version the docs refer to - `repo.url` is not a valid way to get the repository URL in `v0.40.0` of awsx. Had to use `repo.repository.repositoryUrl` instead.

But I upgraded to `1.0.0-beta.7` instead of trying to make `0.40.0` work - should make it easier to tell that the docs like this are not compatible with the latest, default installed version of `awsx`.

**Comment by cnunciato** [comment]
Thank you again for reporting this! We just added GitHub links to our examples that you can use to look up the packages in use for it. (Not all examples support this yet, but we're working on that!)
