### ISSUE TITLE
Incorrect Casing - Parameter Names

### ISSUE THREAD

**Issue by stephenbawks** [pulumi/pulumi-hugo#1770]
File: [themes/default/content/docs/guides/crosswalk/aws/api-gateway.md](https://www.pulumi.com/docs/guides/crosswalk/aws/api-gateway/)

Cognito Authorizers has incorrect parameter names for the Python example.

https://www.pulumi.com/docs/guides/crosswalk/aws/api-gateway/#cognito-authorizers

```
authorizers=[apigateway.AuthorizerArgs(
            parameterName="Authorization",
            identitySource=["method.request.header.Authorization"],
            providerARNs=[userPool.arn]
        )]
```

Should be:

```
authorizers=[apigateway.AuthorizerArgs(
            parameter_name="Authorization",
            identity_source=["method.request.header.Authorization"],
            provider_arns=[userPool.arn]
        )]
```

**Comment by susanev** [comment]
thx for the report @stephenbawks! would you be up for submitting a pr?
https://github.com/pulumi/pulumi-hugo/edit/master/themes/default/content/docs/guides/crosswalk/aws/api-gateway.md

**Comment by cnunciato** [comment]
Fixed via https://github.com/pulumi/pulumi-hugo/pull/3735.
