### ISSUE TITLE
url output for python

### ISSUE THREAD

**Issue by EnochFin** [pulumi/pulumi-hugo#1775]
File: [themes/default/content/docs/guides/crosswalk/aws/ecs.md](https://www.pulumi.com/docs/guides/crosswalk/aws/ecs/)

The python Code Snippet under `Creating a Load Balanced ECS Service` doesn't export any url for the next step

**Comment by EnochFin** [comment]
`pulumi.export('url', lb.load_balancer.dns_name)` is all that needs to be added to the end for the next command to work

**Comment by susanev** [comment]
@EnochFin would you be up for opening a pr?
https://github.com/pulumi/pulumi-hugo/edit/master/themes/default/content/docs/guides/crosswalk/aws/ecs.md

**Comment by EnochFin** [comment]
@susanev Made a PR: https://github.com/pulumi/pulumi-hugo/pull/1776
I hope it follows the pulumi standards.
