### ISSUE TITLE
proposal: move sdk reference documentation at bottom of api reference to language specific pages

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#1790]
we have sdk reference documentation by language at the bottom of the [API reference page](https://www.pulumi.com/docs/reference/pkg/). most of the content of that page was moved to registry, and the only thing left is the [SDK reference documentation](https://www.pulumi.com/docs/reference/pkg/#package-documentation). if we relocate these docs, we can retire this page as defined in: https://github.com/pulumi/pulumi-hugo/issues/785.

note that we also have an [SDK docs](https://www.pulumi.com/docs/reference/pulumi-sdk/) left nav item in reference and i am not proposing any changes to that, this is constrained only to relocating the content at the bottom of the API ref page.

i am suggesting that we move this content to the [language-specific pages](https://www.pulumi.com/docs/intro/languages/).

i am looking for thoughts from other folks. am i overlooking something that will make this a poor experience? do you have other location ideas in mind? other thoughts?

**Comment by stack72** [comment]
I believe we should remove kubernetesx. and cloud from that page as they were preview and are not maintained at this moment in time - @lukehoban may think differently here though

I think the 3 @pulumi/{pulumi|policy|terraform} can be moved the API reference in the left hand nav

That leaves just AWSX - that's a current nodejs link experience until we launch GA of AWSX

**Comment by dixler** [comment]
It might be confusing/hard-to-find to have the Pulumi SDK reference in the `intro to pulumi` area.

**Comment by stack72** [comment]
> It might be confusing/hard-to-find to have the Pulumi SDK reference in the `intro to pulumi` area.

I'm not suggesting in the "intro to pulumi" - It would be in the "API Reference" left hand nav

**Comment by susanev** [comment]
> It might be confusing/hard-to-find to have the Pulumi SDK reference in the `intro to pulumi` area.

as a aside, i really want us to retire that intro section, i don't think is an accurate description of that content. my previous proposal in this area was to make arch+concepts, and pulumi service top-level items. move compare to (along with adopting and converters) to a new top-level section, and remove cloud providers since it just links to registry.
