### ISSUE TITLE
        return ctx.exports();  in java code this method does not exist in Context

### ISSUE THREAD

**Issue by nagkumar** [pulumi/pulumi-hugo#1841]
### What happened?

https://www.pulumi.com/learn/pulumi-fundamentals/configure-and-provision/ source code shows

![image](https://user-images.githubusercontent.com/332234/185148670-d2a32a90-2522-49c4-8750-1e13411a14df.png)

while return ctx.exports();  does not exist and also  the method returns void, that way return statement is also wrong

![image](https://user-images.githubusercontent.com/332234/185148787-6264a92b-1598-4912-87cc-89294597120d.png)

### Steps to reproduce

look at this page https://www.pulumi.com/learn/pulumi-fundamentals/configure-and-provision/

### Expected Behavior

both api and return statement should be removed

### Actual Behavior

no return statement needed as method returns void

### Output of `pulumi about`

G:\DWork\osource\cloudc\devops\pulumi\java\docker>pulumi about
CLI
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME    VERSION
docker  3.2.0
java    unknown

Host
OS       Microsoft Windows 10 Pro
Version  10.0.19045 Build 19045
Arch     x86_64

This project is written in java: executable='d:\Apps\Dev\langs\java\jdk\17.x\bin\java.exe' version='java 17.0.2 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)' java='d:\Apps\Dev\langs\java\jdk\17.x\bin\java.exe' javac='17.0.2'

Backend
Name           pulumi.com
URL            https://app.pulumi.com/nagkumar
User           nagkumar
Organizations  nagkumar

No dependencies found

Pulumi locates its logs in C:\Users\RAJANA~1\AppData\Local\Temp by default
warning: Failed to get information about the current stack: No current stack

G:\DWork\osource\cloudc\devops\pulumi\java\docker>

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by nimbinatus** [comment]
Thanks for the report! We missed this one when updating the code when the Java language host got updated. I'll fix it this morning.
