### ISSUE TITLE
Unclear documentation in learn fundamentals pathway

### ISSUE THREAD

**Issue by nagkumar** [pulumi/pulumi-hugo#1842]
### What happened?

This document does not say where exactly the App.java file should be placed within this source code

![image](https://user-images.githubusercontent.com/332234/185145915-5dea6f06-0dce-44ce-8bb7-2b3775cb1260.png)

### Steps to reproduce

Read the web URL https://www.pulumi.com/learn/pulumi-fundamentals/create-docker-images/

### Expected Behavior

Better this source code https://github.com/pulumi/tutorial-pulumi-fundamentals

contains all the pulumi language specific build code too.. in the case of java App.java etc..

### Actual Behavior

No pulumi code exists

### Output of `pulumi about`

na

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by nimbinatus** [comment]
As noted in #1840, the code referenced from the tutorial repo is for reference only, not part of the actual source code for the pathway. The pathway does not ask you to clone it locally. Instead, the `App.java` file is auto-created when you initialize your Pulumi project with `pulumi new java-gradle -y`. Please start at the first section, https://www.pulumi.com/learn/pulumi-fundamentals/create-a-pulumi-project/, which explains where `App.java` is generated.

**Comment by susanev** [comment]
i wonder if we can do anything to better reinforce this and make it more clear to folks.

**Comment by nimbinatus** [comment]
I noted in https://github.com/pulumi/pulumi-hugo/issues/1840#issuecomment-1224184049 that it might be better to reword the section.
