### ISSUE TITLE
Windows binary download points to darwin

### ISSUE THREAD

**Issue by 1oglop1** [pulumi/pulumi-hugo#1845]
File: [themes/default/content/docs/get-started/install/_index.md](https://www.pulumi.com/docs/get-started/install/)

<img width="414" alt="image" src="https://user-images.githubusercontent.com/7480694/185347832-2c696f5d-ac1f-4691-a388-b2b33b75bf77.png">

this link points to https://get.pulumi.com/releases/sdk/pulumi-v3.38.0-darwin-x64.tar.gz instead of windows binary files.
I assume it should be something like `https://github.com/pulumi/pulumi/releases/download/v3.38.0/pulumi-v3.38.0-windows-x64.zip`

**Comment by susanev** [comment]
hi @1oglop1 thx for opening this issue, i believe this was fixed in https://github.com/pulumi/pulumi-hugo/pull/1843 can you try again?

**Comment by 1oglop1** [comment]
@susanev Looks good to me! feel free to close the issue!
