### ISSUE TITLE
[chore] Remove GCP images for Service Account Key generation

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-hugo#1847]
The images [displayed on the SA setup instructions for GCP](https://www.pulumi.com/registry/packages/gcp/service-account/) are slightly out of date.

After updating the above instructions, let's remove:
- https://github.com/pulumi/pulumi-hugo/blob/master/themes/default/static/images/docs/gcp_configure/gcp_create_credentials.png
- https://github.com/pulumi/pulumi-hugo/blob/master/themes/default/static/images/docs/gcp_configure/gcp_create_service_account_key.png

**Comment by guineveresaenger** [comment]
Part of https://github.com/pulumi/home/issues/2270

**Comment by susanev** [comment]
i try and generally recommend that we don't maintain screenshots of other people's tools. so def support removing these!
