### ISSUE TITLE
Blog posts should have a publish date

### ISSUE THREAD

**Issue by spara** [pulumi/pulumi-hugo#185]
## overview

A publish date will help a reader know what is the most current information. 

## design details
added by @susanev 

- [ ] move the date up below blog titles and above the author
- [ ] change the color to the base text color, instead of the light gray

**Comment by cnunciato** [comment]
Thank you for raising this. We actually do show a publish date today, but we show it at the _bottom_ of the page, which is super unhelpful. We should show it at the top, for exactly the reason you point out.

**Comment by susanev** [comment]
this is not an urgent issue, we have added it to the next iteration for review.

**Comment by susanev** [comment]
this came up again, and ive added it for consideration for the quality iteration. this information is important for folks to be able to evaluate the usefulness of the information and believe we should fix this.
