### ISSUE TITLE
Add unit testing content for Java

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-hugo#1853]
Content is missing for Java on the Pulumi unit testing page.

If it's supported, we should have examples. If not, we should say it's not supported yet.

File: [themes/default/content/docs/guides/testing/unit.md](https://www.pulumi.com/docs/guides/testing/unit/)

**Comment by cnunciato** [comment]
Closing in favor of https://github.com/pulumi/pulumi-hugo/issues/2480.
