### ISSUE TITLE
Out-of-date AWS ECS TypeScript Documentation

### ISSUE THREAD

**Issue by 0xYao** [pulumi/pulumi-hugo#1903]
### What happened?

All TypeScript examples in the AWS ECS page are out-of-date for the latest Pulumi sdk

https://www.pulumi.com/docs/guides/crosswalk/aws/ecs

### Steps to reproduce

- Download the latest Pulumi SDK, for example

```
"dependencies": {
        "@pulumi/aws": "^5.13.0",
        "@pulumi/awsx": "^0.40.0",
        "@pulumi/pulumi": "^3.39.1"
}
```

- Copy and paste any example code snippet from [the link](https://www.pulumi.com/docs/guides/crosswalk/aws/ecs) above.
- You would see TypeScript definition errors, here is one of the errors for example

![image](https://user-images.githubusercontent.com/48658585/188241858-71f50c6a-ce0d-49d3-b197-51de7e6b82ea.png)

### Expected Behavior

The code in the documentation should run without any errors.

### Actual Behavior

Code could not be executed because of TypeScript errors.

### Output of `pulumi about`

```
CLI          
Version      3.39.1
Go Version   go1.19
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.13.0
docker  3.4.1
nodejs  unknown

Host     
OS       darwin
Version  12.3
Arch     arm64

This project is written in nodejs: executable='/Users/alex/.nvm/versions/node/v16.15.0/bin/node' version='v16.15.0'

Current Stack: test

Found no resources associated with test

Found no pending operations associated with test

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/0xYao
User           0xYao
Organizations  0xYao

Dependencies:
NAME            VERSION
@pulumi/aws     5.13.0
@pulumi/awsx    0.40.0
@pulumi/pulumi  3.39.1
@types/node     14.18.26

Pulumi locates its logs in /var/folders/cw/rxyvcdpx4szdh9dlns5nr3n00000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Hi @0xYao 

I apologise for the error here - unfortunately the code is these guides are intended for use with the new 1.x-beta series of awsx. The docs for the previous version of the product are based https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/awsx/

I’ll add a banner now to these to ensure that is more clear. The behaviour between the 0.40.x package and the 1.x series has changed thus the issue you may be seeing

I’m sorry again for the frustration that this could cause

Paul
