### ISSUE TITLE
Add Promotion for the Pulumi Challenge

### ISSUE THREAD

**Issue by lindsaymarolich** [pulumi/pulumi-hugo#1911]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Could we please add a promotional text banner to the top of the global nav to promote the Pulumi Challenge (as we've done for events in the past). Copy:
Build something cool, get Pulumi swag in return! Take the [Pulumi Challenge: Startup in a Box](https://www.pulumi.com/challenge/startup-in-a-box/) ⚡

And also, if @susanev approves of the design, please add a banner to /docs to the right of the text, below the 'Was this page helpful' section. Option for banner below (@SaraDPH let me know if you have feedback on this):
![pulumi-challenge](https://user-images.githubusercontent.com/69173062/188709790-3a4a974e-f68c-495b-b80b-8c0a5604fd58.png)

Link for the banner is the same as above: https://www.pulumi.com/challenge/startup-in-a-box/

**Comment by susanev** [comment]
can we do the banner with a white background, or no background, then add a purple outline on the button. then id be good with adding it to the docs. very happy to make the design edits if yall would like.

**Comment by lindsaymarolich** [comment]
Here's an updated banner image with @susanev's suggested changes, could you please add this @zchase?  
![pulumi-challenge](https://user-images.githubusercontent.com/69173062/189980699-6c202052-5168-4973-9e3b-6b37f36bf0f0.png)

**Comment by lindsaymarolich** [comment]
@shughes26 or @sean1588, mentioning you here in case either of you have time to tackle this while Zack is out.

**Comment by sean1588** [comment]
thanks @lindsaymarolich ! I'll get the image updated.
