### ISSUE TITLE
Add links to https://archive.pulumi.com/

### ISSUE THREAD

**Issue by zchase** [pulumi/pulumi-hugo#2019]
We have an archive of Community Slack messages at https://archive.pulumi.com/ that we do not yet expose on pulumi.com. We should add links in the following places:

- In the Learn menu dropdown
- The footer (right column at the top)
- https://www.pulumi.com/docs/support/troubleshooting/
- https://www.pulumi.com/docs/support/faq/

**Comment by susanev** [comment]
i wonder if we should remove something from Learn if we add this here, or if we need a new top-level category. Learn is becoming quite full.

some deets on this usability issue if ur interested: https://www.smashingmagazine.com/2016/09/reducing-cognitive-overload-for-a-better-user-experience/#3-too-many-options-hick-s-law

**Comment by susanev** [comment]
are you actively working on this @shughes26?

**Comment by cnunciato** [comment]
Closing as we not link to this in the footer.
