### ISSUE TITLE
Updates to CED Page

### ISSUE THREAD

**Issue by lindsaymarolich** [pulumi/pulumi-hugo#2041]
We have a few changes to make to update Cloud Engineering Days:
1/ Replace the 'Hackathon' tile with 'Case Studies' and the text below with: 'Learn from Pulumi customers on how they scaled up their infrastructure velocity and reliability with Pulumi. Infrastructure experts from companies like Fauna, Panther Labs, and Altana AI will present best practices for using Pulumi and infrastructure as code to increase velocity and even build their product platforms.' Please change button to a 'Register' button like the others
2/ Please remove Kat and David from the workshops presenter images
3/ Please remove the section about the Pulumi Community Hackathon (right below 'Join the Conversation')
4/ Please add partner logos to the section where Hackathon used to be. This can just be a white background with logos equally distributed horizontally across the page (I will add the logos shortly)
5/ Please remove 'Hackathon Launch' from the agenda and update 'Workshop Day' to the 12PM slot instead of 1PM
6/ It was noticed that sometimes the images of people look stretched at different screen sizes, can we prevent this?
<img width="428" alt="Screen Shot 2022-10-12 at 2 31 38 PM" src="https://user-images.githubusercontent.com/69173062/195453272-07c5f863-3680-488a-8cd0-3072a49b97a4.png">

**Comment by shughes26** [comment]
https://github.com/pulumi/pulumi-hugo/pull/2040 this PR covers:
1 (halfway)/ removes hackathon tile (not replaced yet)
2/ removes Kat and David from presenters
3/ removes hackathon section
5/ removes hackathon launch from the agenda
6/ fixes stretchy images

will open a separate PR for:
1 (the rest of it)/ 'Case Studies'
5/ move up workshop day timing
4/ partner logos

**Comment by wamazonsmith-web** [comment]
Add Customer speakers in the Pulumi Demo's and best practices:
Wondering if there is a way to pull in the customer logos so they feature prominently?
Dan Swartz, Principal Software Engineer, Altana AI
Dennis Webb, Staff Software Engineer, Panther

Also adding to Schedule at a Glance:
Can we add the customer logos in the relevant spots?
Within Achieving Results with Pulumi Customers
Add in the two above
![danswartz](https://user-images.githubusercontent.com/75398972/195645915-47cad009-627d-405c-be11-b125b4d1f307.jpeg)

![](https://files.slack.com/files-pri/TC2U317C7-F046AQ4FXB6/dscf9081.jpg)
![fauna](https://user-images.githubusercontent.com/75398972/195646368-3f445be2-9afc-4a7a-a1e2-669c687279eb.png)
![panther](https://user-images.githubusercontent.com/75398972/195646381-ef713c9c-4c39-4b7b-9c17-d2c6f041f410.png)
![altana](https://user-images.githubusercontent.com/75398972/195646750-dc542be1-2443-4ed0-9b1d-ea44262bb81d.png)

**Comment by lindsaymarolich** [comment]
Here are the partner logos @shughes26:
![lockup_GoogleCloud_FullColor_rgb_544x96px](https://user-images.githubusercontent.com/69173062/195646347-1f991659-5eaa-4e96-8eab-6c491fdac470.png)
![aws (1)](https://user-images.githubusercontent.com/69173062/195646365-9d775efc-458a-4ee4-bfe7-8d334846cefe.png)


Also could we please add Tushar and Ringo as presenters on the workshop tile (where Kat and David were):
![ringo-de-smet](https://user-images.githubusercontent.com/69173062/195646217-7b9aeb20-5fa3-4c66-9818-94c25595e700.png)
![tushar-shah](https://user-images.githubusercontent.com/69173062/195646237-2a7245c4-82a2-4305-b2ff-9e9204e6d28c.jpeg)
