### ISSUE TITLE
Update Banner Text on Site Header

### ISSUE THREAD

**Issue by lindsaymarolich** [pulumi/pulumi-hugo#2080]
Could we please update the text banner at the top of the website (currently promoting CED):

<img width="560" alt="Screen Shot 2022-10-24 at 8 42 28 AM" src="https://user-images.githubusercontent.com/69173062/197568054-d4c89397-0887-4f7b-8891-64bb3cd03c97.png">

**New text:** 
🎉 New Pulumi Kubernetes Operator v1.10: [Flux integration, Inline Infrastructure support, and Server Side Apply](https://www.pulumi.com/blog/pulumi-kubernetes-new-2022/)

**Comment by shughes26** [comment]
Just merged PR, updates should be live soon
