### ISSUE TITLE
Docs / Reference / API should be "cmd-f" searchable

### ISSUE THREAD

**Issue by blampe** [pulumi/pulumi-hugo#2096]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

As a user, when I visit the API Reference page I'm presented with a large number of providers. I'm looking for a particular provider, so in my browser I type cmd-f followed by the name of the provider I'm looking for. I would expect this to take me to the name of the provider on the page.

Instead, our providers are only identified by images, so I have to visually scan the page and all of its relevant sections until I eventually find the logo of my provider. This is slow and frustrating.

### Affected area/feature

https://www.pulumi.com/docs/reference/pkg/

**Comment by susanev** [comment]
we need to remove that page, its depreciated and not up to date, its been replaced by registry.
where we have this issue: https://github.com/pulumi/registry/issues/657

a related issue to removing the API ref page from docs: https://github.com/pulumi/pulumi-hugo/issues/785

imma close as a duplicate, but feel free to open a new issue in registry or comment on 657 if that doesn't capture ur request
