### ISSUE TITLE
Remove/replace CED banner(s) on the site

### ISSUE THREAD

**Issue by lindsaymarolich** [pulumi/pulumi-hugo#2178]
Could we please remove the CED banner on the home page (shown below):

<img width="910" alt="Screenshot 2022-11-02 at 9 28 20 AM" src="https://user-images.githubusercontent.com/69173062/199546491-13f275c4-1927-404f-aeb2-29c812cbd82e.png">

And also replace the CED display banner on the /docs pages with the one below, linking to:
https://www.pulumi.com/product/pulumi-deployments/

![pulumi-deployments](https://user-images.githubusercontent.com/69173062/199554154-85234ef9-dd54-424c-95ad-23669b695923.jpg)

**Comment by lukehoban** [comment]
This was completed in https://github.com/pulumi/pulumi-hugo/pull/2184.
