### ISSUE TITLE
AWS v5.0.0 Blog showing Bucket instead of BucketV2 for c# and go examples

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-hugo#2200]
### What happened?

https://www.pulumi.com/blog/announcing-v5.0.0-of-the-pulumi-aws-provider/#what-if-i-want-to-migrate-to-use-the-new-implementation-of-an-s3-bucket

the go and c# examples are using `aws.s3.Bucket` when they should be using `aws.s3.BucketV2` like typescript and python examples.

### Steps to reproduce

- go to https://www.pulumi.com/blog/announcing-v5.0.0-of-the-pulumi-aws-provider/#what-if-i-want-to-migrate-to-use-the-new-implementation-of-an-s3-bucket
- view c# or go and look at the `what if I want to migrate to use the new implementation of an S3 Bucket`

### Expected Behavior

code should use `aws.s3.BucketV2`

### Actual Behavior

code uses `aws.s3.Bucket`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by susanev** [comment]
theres something to work out around updating past blogs when things change. ill post about it in #docs.

**Comment by susanev** [comment]
oh ignore me, i see now.
