### ISSUE TITLE
AWS Serverless Template page missing side panel

### ISSUE THREAD

**Issue by gthuang** [pulumi/pulumi-hugo#2210]
### What happened?

The AWS serverless template landing page is missing the right side panel. 

### Steps to reproduce

Go to https://www.pulumi.com/templates/serverless-application/aws/ from safari.

### Expected Behavior

It should have a right side panel.

### Actual Behavior

There is no right side panel.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by cnunciato** [comment]
Closing as it no longer repros.
