### ISSUE TITLE
Audit Logs: Timestamp format is incorrectly documented

### ISSUE THREAD

**Issue by alexstojda** [pulumi/pulumi-hugo#2225]
File: [themes/default/content/docs/intro/pulumi-service/audit-logs.md](https://www.pulumi.com/docs/intro/pulumi-service/audit-logs/)

<img width="683" alt="image" src="https://user-images.githubusercontent.com/1353716/201785068-18af36a5-95e1-43f6-a7ea-be5b5787c689.png">

Docs mention the `timestamp` is RFC3339 (`2020-12-09T16:09:53+00:00`) but the API actually returns the time in UNIX(Seconds) as show in the API Docs: 

<img width="726" alt="image" src="https://user-images.githubusercontent.com/1353716/201785317-207299c4-a2b5-4690-b147-5cb1c0c15412.png">

**Comment by susanev** [comment]
@EvanBoyle do you mind triaging this?
