### ISSUE TITLE
Update to re:Invent Page

### ISSUE THREAD

**Issue by lindsaymarolich** [pulumi/pulumi-hugo#2275]
Request for a few updates to the [re:Invent page](https://www.pulumi.com/reinvent/)

1/ Could we please update the link on the 'Pulumi Templates' card to [go here](https://www.pulumi.com/templates/) (it currently goes to the Challenges page)

2/ Can we please add a fourth card titled: Pulumi Crosswalk for AWS
Description: Pulumi Crosswalk for AWS is now v1.0! Use these libraries to quickly build modern cloud architectures using well-architected best practices.
CTA: [Learn More](https://www.pulumi.com/blog/crosswalk-for-aws-1-0/)

**Comment by shughes26** [comment]
Crosswalk card added, challenge link fixed in [this PR](https://github.com/pulumi/pulumi-hugo/pull/2264)
