### ISSUE TITLE
Update Crosswalk for AWS guides for 1.0

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-hugo#2281]
- [x] ECS - upgrade and add languages
  - https://github.com/pulumi/pulumi-hugo/pull/2274
- [x] ECS - upgrade and add languges
  - https://github.com/pulumi/pulumi-hugo/pull/2284
- [x] API Gateway - add missing languages
- [x] EKS - add languages
  - https://github.com/pulumi/pulumi-hugo/pull/2286
- [x] ELB - upgrade to 1.0 and add all languages
  - fixes pulumi/pulumi-aws#2337
- [x] VPC - rework for 1.0 and add all languages (in progress @danielrbradley)
  - https://github.com/pulumi/pulumi-hugo/pull/2329
- [x] Index - upgrade for 1.0 and add all languages
  - https://github.com/pulumi/pulumi-hugo/pull/2328

Blog posts referencing AWSx:
- [x] https://www.pulumi.com/blog/crosswalk-for-aws-1-0/
- [x] https://www.pulumi.com/blog/crosswalk-for-aws-all-languages/
- [x] https://www.pulumi.com/blog/introducing-pulumi-crosswalk-for-aws-the-easiest-way-to-aws/
- [x] https://www.pulumi.com/blog/pulumi-universal-iac/#crosswalk-for-aws-in-all-pulumi-languages
- [ ] https://www.pulumi.com/registry/packages/aws/how-to-guides/ecs-fargate/
  - (wrongly?) filed under AWS Classic/How-to Guides

Not required:
- Autoscaling - only supported in AWSx Classic
- Cloudwatch - only supported in AWSx Classic
- IAM - says only supports TS for AWSx, but also includes other languages for plain resources, but missing Java and YAML
- Lambda - only supported in TS

**Comment by lukehoban** [comment]
Changing to kind/bug since all of the remaining examples to be updated no longer work by default.

**Comment by mnlumi** [comment]
Added AWSx blog posts that need to be reviewed for 1.0 updates as well.
