### ISSUE TITLE
Move large asset files to uploads bucket

### ISSUE THREAD

**Issue by sean1588** [pulumi/pulumi-hugo#2319]
We are currently reaching size limitations with our hugo build. See https://github.com/pulumi/docs/issues/8220.  Moving our larger assets such as images, videos, and gifs to the separate uploads bucket would help address this. We should have them moved to the uploads bucket and update the references to reference them from that location.

**Comment by susanev** [comment]
@sean1588 do you need a triage on this? if not, can you drop the needs-triage label?

**Comment by cnunciato** [comment]
This is done.
