### ISSUE TITLE
Remove embedded HTML with Markdown in Pulumi Learn content

### ISSUE THREAD

**Issue by scottslowe** [pulumi/pulumi-hugo#2333]
There is at least one spot in the Pulumi Learn content (the "Create a Pulumi Project" topic in the "Pulumi Fundamentals" pathway) where we are using embedded HTML instead of leveraging Markdown. (This may be due to some as-yet-unexplained interaction with the `{{< langfile >}}` shortcode.) For maximum maintainability and usability, we should remove the embedded HTML and replace with it Markdown.

**Comment by scottslowe** [comment]
This might be one way of approaching/solving the issue: https://github.com/pulumi/pulumi-hugo/blob/master/themes/default/content/docs/get-started/aws/review-project.md?plain=1#L46

**Comment by cnunciato** [comment]
Closing as the plan is to replace this section with Tutorials.
