### ISSUE TITLE
[Learn] Langhost shortcode not working properly

### ISSUE THREAD

**Issue by scottslowe** [pulumi/pulumi-hugo#2358]
### What happened?

In at least one of the Learn topics ("Creating Docker Images", found at https://www.pulumi.com/learn/pulumi-fundamentals/create-docker-images/), the `{{< langhost >}}` shortcode _always_ returns "Node.js" regardless of the language selected in the language chooser. This results in text like:

> In this case, we're using Node.js, so our main file is `App.java`

Clearly, that isn't correct.

### Steps to reproduce

1. Navigate to https://www.pulumi.com/learn/pulumi-fundamentals/create-docker-images/
2. Scroll down to the paragraph starting with "Back inside your Pulumi program..."
3. Select a language _other_ than TypeScript from the language chooser just below the paragraph. 
4. Note that the paragraph always says "In this case, we're using Node.js..." regardless of the language selected in the language chooser.

### Expected Behavior

I expected the `{{< langhost >}}` shortcode to render correctly based on the language selected in the chooser.

### Actual Behavior

The `{{< langhost >}}` shortcode always renders as "Node.js".

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by scottslowe** [comment]
Assigning this to @interurban; this may be an issue you'll want to close as not planned once you and Torian sort out the plan for tutorials.

**Comment by interurban** [comment]
It looks like the original bug is fixed, and the {{< langhost >}} shortcode is working as expected, but we'll double check with the team next week.

**Comment by cnunciato** [comment]
Fixed via #3235.
