### ISSUE TITLE
build: Preview sometimes gets rate limited

### ISSUE THREAD

**Issue by abhinav** [pulumi/pulumi-hugo#2382]
### What happened?

I submitted a pull request and the preview job failed with the following error:

```
./scripts/ci/pull-request.sh
# ...
ERROR 2023/01/09 19:41:15 Failed to get JSON resource "https://api.github.com/repos/pulumi/docs/contents/content/docs/reference/cli/pulumi.md": Failed to retrieve remote file: Forbidden, body: "{\"message\":\"API rate limit exceeded for 40.86.28.130. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\",\"documentation_url\":\"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting\"}\n"
```

### Steps to reproduce

Maybe create many pull requests at the same time?

### Expected Behavior

Job finishes successfully and posts a preview to the PR.

### Actual Behavior

Job fails and no preview is posted.

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by susanev** [comment]
im not really sure what we can do about this. @sean1588 @cnunciato thoughts?

**Comment by abhinav** [comment]
Unauthenticated requests get rate limited more heavily.
If we provide a GitHub API token for whatever is making that request, the rate limit is a lot higher.

**Comment by sean1588** [comment]
yeah, i notice i've been running into this a bit more often as well.

> If we provide a GitHub API token for whatever is making that request, the rate limit is a lot higher.

thanks @abhinav. If using a github api token to make the request would bump up the rate limit we should probably do that and I imagine it should be fairly trivial to do.

**Comment by susanev** [comment]
k, adding it to the iteration if we end up having time, otherwise lets fix it up next iteration

**Comment by abhinav** [comment]
👍 

https://github.com/pulumi/pulumi-hugo/blob/master/themes/default/layouts/shortcodes/pulumi-command.html appears to be the perpetrator.
The `getJSON` function used there [supports headers](https://gohugo.io/templates/data-templates/#add-http-headers).
We can stick the auth token (`secrets.GITHUB_TOKEN` is auto-populated) in an environment variable, pull it with [getenv](https://gohugo.io/functions/getenv/) and place it in that `getJSON` request per [GitHub docs](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#oauth2-token-sent-in-a-header).

**Comment by cnunciato** [comment]
Seems fine to pass the assigned GITHUB_TOKEN -- but it's also interesting this one API request would put us over a rate limit. Maybe the actual problem is elsewhere?
