### ISSUE TITLE
Change " | Pulumi" to " | Pulumi Registry" across all /registry/ title tags

### ISSUE THREAD

**Issue by zchase** [pulumi/pulumi-hugo#2386]
Request: Change " | Pulumi" to " | Pulumi Registry" across all /registry/ title tags.

For example: AWS Provider | Pulumi → AWS Provider | Pulumi Registry

Rationale: To improve ease for searchers to distinguish between marketing and documentation pages, which at times are cannibalizing each other and have duplicate title tags on the SERP.

**Comment by zchase** [comment]
"Cannibalizing" refers to multiple URLs that share content (titles, text on the page, etc..) so they rank for the same keywords. When a domain has multiple URLs that rank for the same search term, they are forced to compete with one another for ranking, and that is considered "cannibalization".

My opinion on the titles is that as long as everything before the `|` character is under the limit then we are in a good place. The character limit is just what Google displays to users and I think of everything to the right of `|` is for bots, not humans.

**Comment by susanev** [comment]
i kind of wish we could adjust some of the marketing page titles, so instead of using `AWS Provider` for the marketing page for the provider, maybe `Understanding the AWS Provider` or similar. idk if that's an option?

**Comment by zchase** [comment]
@susanev I opened this issue that hopefully captures your suggestion above: https://github.com/pulumi/pulumi-hugo/issues/2388

Feel free to edit if needed!
