### ISSUE TITLE
Make learn clickable in the top nav

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi-hugo#2391]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
It's hard to find learn content. It'd reduce mental load to click it.

**Comment by susanev** [comment]
@dixler can you be more specific? it should be interactive.

**Comment by susanev** [comment]
do you mean in the black practitioner nav?

**Comment by susanev** [comment]
okay, thx for opening an issue.

we are going to be working on integrating learn and get started in some way this quarter, so will hold off on this for right now. but would love your feedback as we start figuring out how to raise the visibility of learn.

**Comment by cnunciato** [comment]
Closing as we aren't currently planning to make changes to these menus.
