### ISSUE TITLE
Automation API Reference should allow language change

### ISSUE THREAD

**Issue by RobbieMcKinstry** [pulumi/pulumi-hugo#2396]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

On the [Automation API reference page](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/automation/), I would like to navigate from one language to another. IMO there should be a language selector on this page, letting users navigate between languages. It's quite hard to navigate between different languages -- the URL isn't intuitive, and I had to navigate back to the Automation API guide first (via Google) to find the versions of the reference available. 

### Affected area/feature

Automation API Reference pages](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/automation/

**Comment by susanev** [comment]
we really need to fix the package documentation in general including the navigation

**Comment by RobbieMcKinstry** [comment]
To clarify, neither of these pages are part of the registry (I'm assuming that's what you mean by "package documentation?"

**Comment by susanev** [comment]
this is what i meant? is this not what ur talking about?
<img width="1002" alt="Screen Shot 2023-01-12 at 2 03 50 PM" src="https://user-images.githubusercontent.com/5489125/212191036-28f4b517-537e-4e5c-8265-e1105bfc5310.png">

**Comment by cnunciato** [comment]
Since these pages are all fundamentally language-specific, this isn't something we can practically do. Therefore closing this issue for now.
