### ISSUE TITLE
metral/pulumi-nginx example no longer works

### ISSUE THREAD

**Issue by Frassle** [pulumi/pulumi-hugo#2408]
### What happened?

There's a load of references in our blogs to https://github.com/metral/pulumi-nginx, but that example apparently isn't working: https://pulumi-community.slack.com/archives/C84L4E3N1/p1674044874588559

We should move this example to our examples repo, fix it, and update docs links.

### Steps to reproduce

Try to run https://github.com/metral/pulumi-nginx

### Expected Behavior

Example to work

### Actual Behavior

Example fails to install dependencies.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by alinalex1392** [comment]
I found this repo useful for testing Pulumi Operator https://github.com/pulumi/examples!
