### ISSUE TITLE
Create design doc for moving docs into hugo repo

### ISSUE THREAD

**Issue by sean1588** [pulumi/pulumi-hugo#2417]
create design doc for: https://github.com/pulumi/pulumi-hugo/issues/2416

**Comment by sean1588** [comment]
here is the doc: https://docs.google.com/document/d/10LVEG6UeCIFkprd5IzwTvHM-TYDg9xJlIp3qIFYVTSs/edit

**Comment by cnunciato** [comment]
Closing this as complete with the recent round of design docs.
