### ISSUE TITLE
Issue with https://www.pulumi.com/learn/embedding-pulumi/building-api/

### ISSUE THREAD

**Issue by panorampaul** [pulumi/pulumi-hugo#2457]
There is a mistake in this page.  It refers to updating index.ts which, given the sample code is Python, does not exist. I assume it should refer to __main__.py

**Comment by susanev** [comment]
thank you for the report @panorampaul!

@scottslowe since you have been here recently would you like to fix this up? there is also #2458

**Comment by scottslowe** [comment]
@susanev Yes, I'll have a look at this one and #2458. This may be another instance of `{{ langhost }}` and/or `{{ langfile }}` not working as expected, see #2358.

**Comment by scottslowe** [comment]
Assigning this to @interurban; this may be an issue you'll want to close as not planned once you and Torian sort out the plan for tutorials.

**Comment by interurban** [comment]
Thx Scott; this example has been fixed since this issue was logged, I see no reference to any index.ts. but agree, these tutorials will be refactored, so It's safe to close this issue.
