### ISSUE TITLE
[small typo]create create, update, or delete...

### ISSUE THREAD

**Issue by hdmn54321** [pulumi/pulumi-hugo#2470]
File: [themes/default/content/docs/intro/vs/cloud-templates/_index.md](https://www.pulumi.com/docs/intro/vs/cloud-templates/)

At the end of the first paragraph.

"...which then processes the files to create create, update, or delete cloud infrastructure..."

**Comment by abhinav** [comment]
Thanks for catching this, @hdmn54321.
Fixing in #2479.
Thanks again!
