### ISSUE TITLE
Explicit provider options

### ISSUE THREAD

**Issue by caffeinate** [pulumi/pulumi-hugo#2471]
File: [themes/default/content/docs/intro/concepts/resources/providers.md](https://www.pulumi.com/docs/intro/concepts/resources/providers/)

`__opts__=pulumi.ResourceOptions(provider=useast1))`
should be
`opts=pulumi.ResourceOptions(provider=useast1))`

Same in this article https://www.pulumi.com/blog/deploy-to-multiple-regions/

**Comment by abhinav** [comment]
Thanks for the report, @caffeinate!
Fixing this in #2483.
