### ISSUE TITLE
improve the project file docs

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#2508]
See https://pulumi.slack.com/archives/C85BS3LJZ/p1676046170153479 for additional context.

consider...

- Links to https://www.pulumi.com/docs/intro/concepts/project/
- Notes that every Pulumi program has a project file
- Notes that for Pulumi programs written in Pulumi YAML, the file can also contain the program definition (and link to https://www.pulumi.com/docs/intro/languages/yaml/)
- searching for “YAML” on our site - neither https://www.pulumi.com/docs/intro/languages/yaml/ nor https://www.pulumi.com/docs/reference/pulumi-yaml/ show up in results (@susanev will take this part, it requires a change to an internal tool)

**Comment by KaKashi1210** [comment]
I would like to contribute can you help me get understand this better! like how should i proceed.

**Comment by susanev** [comment]
@KaKashi1210 wonderful!! ill asign you.
you can edit the markdown file directly and then open a pr.
let me know if you need any help.

https://github.com/pulumi/pulumi-hugo/edit/master/themes/default/content/docs/reference/project-file.md

**Comment by KaKashi1210** [comment]
@susanev I messaged  you on slack can please read that.

**Comment by cnunciato** [comment]
Note that the last bullet (search-related) has been fixed, via cutover to Algolia. ("YAML" now surfaces both of those docs as the top two results.)
