### ISSUE TITLE
Introduce a CI check to extract code examples from markdown and compile them

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-hugo#251]
Introduce a CI check to extract code examples from markdown and compile them. This would catch accidentally adding non-compiling code in the examples.  Instance of this in C#: https://github.com/pulumi/pulumi-hugo/pull/250

## Affected feature

Code examples are not compiling.

**Comment by cnunciato** [comment]
Closing this as no longer needed, now that we have the ability to [provide testable examples](https://github.com/pulumi/pulumi-hugo/pull/3690).
