### ISSUE TITLE
Investigate build failure on push jobs

### ISSUE THREAD

**Issue by sean1588** [pulumi/pulumi-hugo#2518]
Sometimes when multiple PRs are merged into master around the same time it causes the build job to fail. It appears to be some sort of race condition that causes it. Typically, the pipeline turns green again on master once the job related to the last PR passes.

https://github.com/pulumi/pulumi-hugo/actions/runs/4287742103/jobs/7468954107

**Comment by cnunciato** [comment]
@sean1588 I think given we have a workaround here, and that we're planning to archive this repo as well, we can probably close this as a wontfix. What do you think? Do you think this is something we need to do?

**Comment by interurban** [comment]
I agree; checking in again @sean1588 do you think we're safe to close this issue?
