### ISSUE TITLE
Search box on blog page is misleading

### ISSUE THREAD

**Issue by mnlumi** [pulumi/pulumi-hugo#2532]
### What happened?

The search box on the left side of the [blog pages](https://www.pulumi.com/blog/) shows the text "Search the blog", but the search actually covers the whole website. 
![Screenshot 2023-03-06 at 2 57 36 PM](https://user-images.githubusercontent.com/118926824/223223406-e96fdfcb-c600-42b7-9788-ed732fc0a6e0.png)

### Expected Behavior

I would expect the search to return results only within the blog section of the site.

### Steps to reproduce

Go to: https://www.pulumi.com/blog/ and search for anything (ex: kubernetes). The results returned are not limited to blogs, but all items on the site.

### Output of `pulumi about`

N/A

### Additional context

Either the text "Search the blog" should be modified to not lead people to believe it will only show blog results OR the search should be limited to blog pages as expected by the text.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jazzyfresh** [comment]
Thank you for reporting! An additional search bar could be added for the entire website, or the search bar could be limited to different spaces depending on the context of which page the user is viewing.

**Comment by cnunciato** [comment]
Fixed via https://github.com/pulumi/pulumi-hugo/pull/2868.
