### ISSUE TITLE
Update Stack Reference docs to mention GetOutputDetails

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi-hugo#2547]
Related to https://github.com/pulumi/pulumi/issues/10839.

Update the existing documentation for Stack References to mention the new `GetOutputDetails` method in each language.

https://www.pulumi.com/docs/intro/concepts/stack/#stackreferences

https://github.com/pulumi/pulumi-hugo/blob/master/themes/default/content/docs/intro/concepts/stack.md

**Comment by abhinav** [comment]
Up at https://github.com/pulumi/pulumi-hugo/pull/2637
This is effectively unusable in Python until https://github.com/pulumi/pulumi/issues/12172
For Java, we need to cut a release before we land the docs https://github.com/pulumi/pulumi-java/issues/1042
