### ISSUE TITLE
Error with make serve

### ISSUE THREAD

**Issue by Comradin** [pulumi/pulumi-hugo#2572]
### What happened?

I followed the readme to start the local development server, but got an error.

```
marcus@NanElmoth pulumi-hugo % make serve-all
./node_modules/.bin/concurrently --kill-others -r "./scripts/serve.sh" "yarn --cwd ./themes/default/theme run start"
yarn run v1.22.19
$ yarn run concurrently 'yarn --cwd stencil run start' 'yarn run webpack --watch' --raw --kill-others
Start building sites … 
hugo v0.111.3+extended darwin/arm64 BuildDate=unknown
$ /Users/marcus/git/Comradin/pulumi-hugo/themes/default/theme/node_modules/.bin/concurrently 'yarn --cwd stencil run start' 'yarn run webpack --watch' --raw --kill-others
Error: Error building site: "/var/folders/sh/ldk5jf_95yb1yrrq79f17gn40000gn/T/hugo_cache/modules/filecache/modules/pkg/mod/github.com/pulumi/registry/themes/default@v0.0.0-20230316203047-8b0d4a0468c1/content/registry/packages/fusionauth/_index.md:16:1": failed to extract shortcode: shortcode "chooser" must be closed or self-closed
Built in 537 ms
make: *** [serve-all] Error 1
```

### Expected Behavior

The hugo server starts.

### Steps to reproduce

The things I did:

```
gh repo clone pulumi/pulumi-docs
cd pulumi-docs
make ensure
make serve
```

### Output of `pulumi about`

Not pulumi related but more a hugo or JavaScript module error.

### Additional context

Haven't tried other OSs, but this happend on macOS Ventura 13.2.1

```
% hugo version
hugo v0.111.3+extended darwin/arm64 BuildDate=unknown
%  go version
go version go1.20.2 darwin/arm64
% nvm version
v18.14.0
yarn install v1.22.19
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by sean1588** [comment]
Hi @Comradin, thanks for filing an issue. It looks like the versions of some of the dependencies you have installed are different than what is suggested in the README. Specifically the version of hugo that you are using, as our build is very particular about the hugo version.

https://github.com/pulumi/pulumi-hugo/blob/master/README.md?plain=1#L16

**Comment by Comradin** [comment]
Hi, I've got the latest release, that comes with homebrew. I'll have a look at the version in the docs
