### ISSUE TITLE
Footnotes

### ISSUE THREAD

**Issue by nimbinatus** [pulumi/pulumi-hugo#2593]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

For the Learn pathways, we want to move the glossary links to footnotes. Unfortunately, the markdown processor renders footnotes after all the classes are applied, and the footnotes just appear as regular text (and the arrows are confusing). I've tried stuff like adding `markdown=1` to the HTML, wrapping it in other tags to apply the other classes... Goldmark doesn't have a class-apply function for non-headings, from what I've been able to find. So we need some way to show footnotes.

For additional notes, reference pulumi/theme#48.

### Affected area/feature

Theme

**Comment by susanev** [comment]
closing as wont fix, we can reopen if this comes up again
