### ISSUE TITLE
Upgrade Sentry 

### ISSUE THREAD

**Issue by zchase** [pulumi/pulumi-hugo#2604]
Some of the errors being logged in Sentry look to be related to Sentry itself. We should upgrade the SDK as noted in the Sentry UI.

<img width="950" alt="sentry-upgrade" src="https://user-images.githubusercontent.com/15146337/196296550-1c98c90f-3e4e-4e3e-86ab-9cbcf8370ebe.png">

**Comment by cnunciato** [comment]
Closing as we currently fetch the latest Sentry SDK on page load.
