### ISSUE TITLE
Standardize on verbiage related to languages and runtimes

### ISSUE THREAD

**Issue by sean1588** [pulumi/pulumi-hugo#2617]
Consider standardizing how we refer to languages and runtimes when listing them throughout the site. This is seen a lot where we use C# and .NET interchangeably. For example we say things like "using languages such as Typescript, Python, Go, .NET, and Java..." We tend to use C# and .NET interchangeably as well as node.js and Typescript, JavaScript. There are some suggestions to use .NET if we say node.js or vice-versa so we remain consistent when referring to runtimes vs individual languages. There are also places where we explicitly list out multiple languages the runtime supports (e.g. ...Python, Go, or any .NET language, including C#, F#, and VB.)

Here is a link to the original slack thread containing the initial discussion: https://pulumi.slack.com/archives/C85BS3LJZ/p1650998119095349

Here are a couple examples of this: 
using .NET - https://www.pulumi.com/docs/intro/concepts/
using C# -  https://www.pulumi.com/solutions/terraform-migration/

**Comment by cnunciato** [comment]
Definitely agree with you on this, and I think we do do our best now to align with this thinking whenever we write and review new content these days. So with that in mind, I'll close this issue for now, and we'll address individual instances in context as we update our docs and marketing content.
