### ISSUE TITLE
Weird Anchor Render on Python SDK Page

### ISSUE THREAD

**Issue by RobbieMcKinstry** [pulumi/pulumi-hugo#2625]
### What happened?

I navigated to https://www.pulumi.com/docs/reference/pkg/python/pulumi/ from the docs homepage. 

I noticed that there's a weird character rendering poorly in the h1. It looks like we're generating two anchor tags here, one duplicate.

<img width="1426" alt="Screenshot 2023-03-28 at 4 02 51 PM" src="https://user-images.githubusercontent.com/4955075/228353885-8a8dbc99-22fc-4af4-8a59-273ef2c51804.png">

In the image above, you can see two consecutive anchor tags. If you hover on the title and click the on-hover anchor icon, you can see the same text in the URL bar, translating to this URL:

https://www.pulumi.com/docs/reference/pkg/python/pulumi/#pulumi-python-sdk%EF%83%81

### Expected Behavior

No weirdness Unicode character

### Steps to reproduce

Navigated to https://www.pulumi.com/docs/reference/pkg/python/pulumi/ and inspect the top bar.

Firefox v111.0 on MacOS v13.0.1

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by susanev** [comment]
cc/ @justinvp not sure if yall have a tracking epic to add things like this to

**Comment by justinvp** [comment]
Ah yes, we thought we fixed this by adding a new CSS selector to select the character that changed recently, but that didn't appear to work. Anyway, let me fix this.
