### ISSUE TITLE
Schema Documentation for Python references NPM

### ISSUE THREAD

**Issue by RobbieMcKinstry** [pulumi/pulumi-hugo#2626]
### What happened?

Upon visiting the schema documentation located at https://www.pulumi.com/docs/guides/pulumi-packages/schema/ , I navigated to the description of Python specific schema under the "PropertyLanguage" heading:
<img width="962" alt="Screenshot 2023-03-28 at 4 06 19 PM" src="https://user-images.githubusercontent.com/4955075/228354552-7f669849-851a-4e3e-95fa-de2b3da0732c.png">

I noticed on the `requires` row, a reference to required NPM packages. Since this is Python, I expect this is actually a reference to required `PyPi` packages, and this was a copy-paste error from the NodeJS section. 

### Expected Behavior

I wouldn't expect NPM referenced for Python packages. Or if there is some connection, I'd expect a more thorough description as to the relationship between Python schama and NPM.

### Steps to reproduce

Navigate to the page and inspect the documentation. Observe NPM referenced under the Python table.

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by susanev** [comment]
these tables also need language selectors
