### ISSUE TITLE
all users on 16.4 safari see giant icons on all api docs pages

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#2657]
this is a pretty broken experience
we are going to need to figure out a quick fix

![image (3)](https://user-images.githubusercontent.com/5489125/230190745-ed033c14-28d2-4094-a0fd-b7fda8954935.png)

**Comment by susanev** [comment]
https://github.com/pulumi/pulumi-hugo/pull/2654 attempted to fix this

**Comment by susanev** [comment]
removed the p0 label as requested.

**Comment by iwahbe** [comment]
My current experience now looks like this:
![screenshot_2023-05-03_at_10 21 17_am_720](https://user-images.githubusercontent.com/22222529/236001911-f19d9cf5-910e-40f1-b505-364a363c9efc.png)

**Comment by susanev** [comment]
we removed facet and fast and this is no longer an issue.
