### ISSUE TITLE
Lint to ensure PNGs only for meta images

### ISSUE THREAD

**Issue by cnunciato** [pulumi/pulumi-hugo#2694]
SVGs and other non-bitmaps are dicey when used as social images. The [blogging README suggests PNGs](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md#social-meta-images), but we really should enforce this at the lint level so we don't ship images that aren't supported on social platforms.

**Comment by susanev** [comment]
@sean1588 since this caused a launch delay, do you think we could pick this up this iteration?

**Comment by sean1588** [comment]
@susanev yeah sounds good!
