### ISSUE TITLE
confirm accuracy of inputs and outputs go example in concepts docs

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#2739]
_this feedback was submitted by way of docs feedback_

https://www.pulumi.com/docs/intro/concepts/inputs-outputs/
the go example for pulumi.All() was reported as being incorrect
folks would also like to know how to get back errors

**Comment by interurban** [comment]
Possible fix; will be checking with Scott: 

connectionString := pulumi.All(sqlServer.Name, database.Name).ApplyT(func(args []interface{}) string {
    server := args[0].(string)
    db := args[1].(string)
    return fmt.Sprintf("Server=tcp:%s.database.windows.net;initial catalog=%s...", server, db)
}).(pulumi.StringOutput)

**Comment by interurban** [comment]
hey @scottslowe I'm wondering if you can take a look at this example?

**Comment by scottslowe** [comment]
@interurban I _believe_ your suggested fix is right. The callback function doesn't return an error, so it should be `string` instead of `(string, error)` for the return values/types. Adding `.(pulumi.StringOutput)` is probably also needed.

Note I haven't tested this code somewhere yet, but I can do that if you'd like.

**Comment by desteves** [comment]
Related https://github.com/pulumi/pulumi/discussions/9069

**Comment by desteves** [comment]
I see this as a two part issue. The first part is having a non-working go example for which I’ll submit a PR to update the docs with working go code. The second part is around error handling guidance. I will add a quick note on how can this be achieved in the same PR. To avoid having error handling examples in go but not the other languages thereby having an inconsistent experience, I plan to add the error handling examples directly in this issue for soundness.
