### ISSUE TITLE
stack docs missing information about why and benefits

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#2741]
_this feedback was submitted by way of docs feedback_

this person went to https://www.pulumi.com/docs/intro/concepts/stack/ and expected to find information about why they would use a stack and what benefits it would give them and this page did not provide that information.

**Comment by susanev** [comment]
@cnunciato @scottslowe either of you want to take this, thought it might be a good fit for one of you

**Comment by scottslowe** [comment]
@interurban Assigning to you, probably needs to go to the Docs board

**Comment by desteves** [comment]
We can add a link to https://www.pulumi.com/docs/using-pulumi/organizing-projects-stacks/  Thoughts?

**Comment by cnunciato** [comment]
Closing this issue as it's not quite clear what'd need to be done to call it "fixed", given the page does explain what stacks are and how to use them (and the "why" and "benefits" are therfore sort of implicit). Feel free to reopen with specific suggestions, though, and we'll consider 'em!
