### ISSUE TITLE
Create Page for Microsoft Build

### ISSUE THREAD

**Issue by lindsaymarolich** [pulumi/pulumi-hugo#2802]
We'd like to create an event landing page for Microsoft Build using our previous [KubeCon page](https://www.pulumi.com/kubecon/) as the template. Please create the page at pulumi.com/microsoft-build

Only a few sections need to be updated:

**Header Image:**
![msftbuild-hero-2023](https://user-images.githubusercontent.com/69173062/236880369-65233238-d8ac-49e6-b66a-d7f226e78828.png)

**Title:** Microsoft Build May 23–25, 2023 (Please make text white)
**Description:** Meet us at Microsoft Build, Room 434
Join us to find out how Pulumi’s Infrastructure as Code reduces cloud complexity, accelerates development velocity and helps companies scale and innovate.

**CTAs:**
Please update the 'RSVP to Happy Hour CTA' to say:
RSVP to Seattle Meetup
Join us at our re-launch of the Seattle Pulumi User Group to meet our CEO, Joe Duffy, and members of our product and engineering teams. 5PM on May 23rd at Rhein Haus Seattle.
'Reserve your spot' CTA: https://www.meetup.com/pulumi-seattle/events/293452944/

Remove workshops section for now. 

Templates:
Please update the templates to the following three:

Title: Azure Static Website Template
Text: Easily deploy static HTML websites on Azure with Pulumi Static Website templates.
Link: https://www.pulumi.com/templates/static-website/azure/

Title: Virtual Machine on Azure
Text: Easily deploy virtual machines (VMs) on Azure with Pulumi Virtual Machine templates.
Link: https://www.pulumi.com/templates/virtual-machine/azure/

Title: Kubernetes Cluster on Azure
Text: Easily deploy Kubernetes clusters and their associated infrastructure on Azure with Pulumi K8s templates.
Link: https://www.pulumi.com/templates/kubernetes/azure/

The rest of the page can stay as-is.

**Comment by SaraDPH** [comment]
Replace this section with text below:
![image (3)](https://github.com/pulumi/pulumi-hugo/assets/100384099/0e4e3405-2493-43db-a3d0-e10c2b1db219)

### New
No speakers, no agenda. Just a casual evening to network and have fun! Meet fellow engineers and CEO Joe Duffy and CTO Luke Lohan. Food and drinks are on us.
May 23, 5:00 Pm PDT at Rhein Haus Seattle

**Comment by lindsaymarolich** [comment]
![msft-build](https://github.com/pulumi/pulumi-hugo/assets/69173062/217d31eb-9b74-4059-9f6c-cce97a935265)

Sorrry @shughes26, here you go!

**Comment by SaraDPH** [comment]
@shughes26 Please add the page to resources and correct the title. 

![image](https://github.com/pulumi/pulumi-hugo/assets/100384099/a7fbd8a3-97ad-4f09-a7a0-d85a151e59bb)

**Comment by prischoi** [comment]
Quick thing I noticed that the break tag is in the page title.

<img width="1723" alt="Screenshot 2023-05-12 at 10 41 15 AM" src="https://github.com/pulumi/pulumi-hugo/assets/105661381/c8d5d535-421b-4463-9555-d8f9662c4665">
