### ISSUE TITLE
Promote Challenge on /ai

### ISSUE THREAD

**Issue by lindsaymarolich** [pulumi/pulumi-hugo#2810]
Please add a link to https://www.pulumi.com/ai to promote the [Pulumi Challenge](https://www.pulumi.com/challenge/ai-architecture/).

Suggested copy:

Put Pulumi AI to the test and join this month's [Pulumi Challenge: GPT Your IaC](https://www.pulumi.com/challenge/ai-architecture/). Use Pulumi AI to deploy the craziest architecture you can imagine. The best PulumiAI generated stack wins a grand prize!

**Comment by cnunciato** [comment]
Closing as no longer applicable.
