### ISSUE TITLE
follow up to new docs nav

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#2818]
for later (fine to do after shipping)
- [x] stop extensions card from growing
- [ ] ~focus styles?~
- [x] did anything break the cli release process?
- [ ] ~seo for the cli command pages (skips h2)~
- [x] ask for seo review
- [ ] ~move images out of docs~
- [x] cloud tokens doc to 1 page https://github.com/pulumi/pulumi-hugo/pull/3038
- [ ] ~remove parent pages~
- [ ] ~move concepts docs to their own tab~
- [ ] ~cloud docs missing policies information~
- [x] open pr in service to update links
- [x] open pr in main repos to update links
- [x] add pkg redirect in registry
- [x] remove cloud providers nav item in registry
- [x] open pr in registry for link changes there
- [ ] ~review overview pages for accuracy~

from joe
- [ ] Get Started links to just one scenario (S3 bucket), not the template picker which is what I expected.
    - [x] I guess I can see why we'd do that, but if we do, I'd make the Templates much more visible on the page and near the top.
- [ ] For the templates, I would err on the side of mentioning the actual services. E.g, instead of "Virtual machine on AWS," why not "EC2 virtual machine" (the "on AWS" is implied anyway given the page I am on).
- [ ] Should we have a brief description of what the components do? E.g.
    - "AWSx": _Built-in best practices for common AWS services_
    - "AWS Static Website:" _Easy S3-based static website with optional Cloudfront CDN_

**Comment by anita-trimbur** [comment]
closing as all relevant, unchecked items have been moved into separate issues.
