### ISSUE TITLE
Deprecated text outside of box on TransitGatewayPeeringAttachmentAccepter

### ISSUE THREAD

**Issue by mnlumi** [pulumi/pulumi-hugo#2832]
### What happened?

On the [aws.ec2.TransitGatewayPeeringAttachmentAccepter ](https://www.pulumi.com/registry/packages/aws/api-docs/ec2/transitgatewaypeeringattachmentaccepter/)registry page, the deprecated warning box is empty and the text visible outside and below it.

<img width="826" alt="Screenshot 2023-05-09 at 10 52 57 PM" src="https://github.com/pulumi/registry/assets/118926824/46d86f2b-4498-47af-b497-a8ee7c8cf8a4">

### Expected Behavior

I expect the deprecated text to be inside the warning box.

### Steps to reproduce

View the [aws.ec2.TransitGatewayPeeringAttachmentAccepter ](https://www.pulumi.com/registry/packages/aws/api-docs/ec2/transitgatewaypeeringattachmentaccepter/)registry page. The deprecation text and box are at the top of the page.

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Actually, maybe we should try to fix the docsgen to not have nested `<p>` as I don't think that's valid HTML. https://stackoverflow.com/a/12015809/43620

> Any `<p>` (or other block-level element) will implicitly close any open `<p>`.
> 
> Per [9.3.1 Paragraphs: the P element](http://www.w3.org/TR/html401/struct/text.html#h-9.3.1) of the HTML 4.01 specification:
> 
> > The P element represents a paragraph. It cannot contain block-level elements (including P itself).

**Comment by interurban** [comment]
@justinvp Checking in as well, do you see this as one that could be worked on in the next sprint or two?

**Comment by justinvp** [comment]
PR: https://github.com/pulumi/pulumi/pull/13773
