### ISSUE TITLE
Updates for Microsoft Build

### ISSUE THREAD

**Issue by lindsaymarolich** [pulumi/pulumi-hugo#2862]
Could we please add Build to the /resources area?

**Details:**
Title: Microsoft Build 2023
Date: May 23, 2023
Description: Join us for Microsoft's annual developer conference, exploring innovations from OpenAI to teams.
Link: https://www.pulumi.com/microsoft-build/

Also on the [Build page](https://www.pulumi.com/microsoft-build/) a few minor changes:
- Please remove the break from appearing in the title tag
<img width="246" alt="Screenshot 2023-05-17 at 11 39 54 AM" src="https://github.com/pulumi/pulumi-hugo/assets/69173062/e319b165-fab3-4a2b-a24b-ca190e201c9a">

- Could we please change the Happy Hour 'Reserve Your Spot' cta to say 'RSVP' and go directly to the meetup.com event URL: https://www.meetup.com/pulumi-seattle/events/293452944/

**Comment by lukehoban** [comment]
This was closed with #2865, right?
