### ISSUE TITLE
ARM-only Docker image referenced in the Fundamentals tutorial

### ISSUE THREAD

**Issue by SpecLad** [pulumi/pulumi-hugo#2893]
### What happened?

The Pulumi Fundamentals tutorial [includes the following passage](https://www.pulumi.com/learn/pulumi-fundamentals/create-docker-images/):

> Our application includes a frontend client and MongoDB. We’ll add them to the program, so add this code after the previous fragment.
> ```python
> ...
> # Pull the MongoDB image
> mongo_image = docker.RemoteImage("mongo_image",
>                                 name="pulumi/tutorial-pulumi-fundamentals-database-local:latest"
>                                )
> ```

If you examine the [tutorial-pulumi-fundamentals-database-local](https://hub.docker.com/r/pulumi/tutorial-pulumi-fundamentals-database-local/tags) image on Docker Hub, you'll see that it only has an ARM variant, so it won't run on a typical x86-based Linux machine. In fact, if you do proceed with the tutorial on such a machine, then the container provisioning step in the next chapter will fail.

### Expected Behavior

Either the tutorial should reference a different image, or an x86 variant should be added to the `tutorial-pulumi-fundamentals-database-local` image.

### Steps to reproduce

Just follow the tutorial.

### Output of `pulumi about`

CLI
Version      3.68.0
Go Version   go1.20.4
Go Compiler  gc

Host
OS       ubuntu
Version  22.04
Arch     x86_64

Backend
Name           [redacted]
URL            file://~
User           [redacted]
Organizations

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by susanev** [comment]
thx for the report @SpecLad!! we will take a look as soon as we can ❤️ 

@cnunciato @scottslowe can you pls triage this? thank you!!

**Comment by scottslowe** [comment]
@SpecLad Thanks for reporting this! We're already tracking this issue: https://github.com/pulumi/tutorial-pulumi-fundamentals/issues/11

I'll close this as a duplicate, but feel free to track progress/updates on the linked issue. Thank you!
