### ISSUE TITLE
AzureAD Cloud Provider Page points to azure-native page for setup

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi-hugo#295]
When the Azure provider was renamed to classic, the link for the azuread setup page was broken for setup :/

We need to point this to the correct azure repo

**Comment by mastoj** [comment]
@stack72 , the link "Azure setup page" on https://www.pulumi.com/docs/intro/cloud-providers/azuread/ still points to the azure setup page which doesn't mention that the configs should be named: `azuread:xxx`, it only mentions `azure:xxx`.

**Comment by stack72** [comment]
Sorry @mastoj I just corrected the link it used to point to - this means we need to create a page of it's own - I will re-open and we will push this back through the process
