### ISSUE TITLE
Home Page Banner Updates for Launch Week

### ISSUE THREAD

**Issue by lindsaymarolich** [pulumi/pulumi-hugo#3004]
We want to add back the small banner in the upper left section of the home page, which will be updated daily on 6/12-6/14 with announcements about that day's launch and link to the highest priority post. Approved copy is below, by date. We would also like the banner background color to be changed each day so it is more noticeable. The 'Learn more' text of each day will link to the relevant blog post, the author of the post will notify @shughes26 at the time of publishing to provide the link and PR for the commit.

**Copy:**
**6/12:** New and improved Terraform conversion tool available! Convert HCL and TF modules to Pulumi.<Learn more>
**6/13:** Introducing Review Stacks: Temporary, on-demand environments for reviewing changes in pull requests. <Learn more>
**6/14:** New: Search for resources across any cloud by resource property from the Pulumi Cloud console. <Learn more>

**Colors:**
6/12: #f2ebf3 (background) // #80398d (text)
6/13: #fdf9eb (background) // #eec14d (text)
6/14: #edeffa (background) // #505bd1 (text)

@gthuang please proof the copy / dates one last time
FYI @susanev

**Comment by cnunciato** [comment]
Closing as done, feel free to reopen if there's anything more to do here.
