### ISSUE TITLE
Pulumi to add support for creating triggers with the Google Cloud Build Repositories Generation 2 API 

### ISSUE THREAD

**Issue by m-haydar** [pulumi/pulumi-hugo#3086]
Pulumi to add support for creating triggers with the Google Cloud Build Repositories Generation 2 API

**Comment by cnunciato** [comment]
@m-haydar Thanks for submitting! Would you mind adding a bit more context to this issue, though? It sounds like it might be something related to one (or both) of our Google Cloud providers, but it'd be good to flesh it out a bit more so we know what's being requested.

**Comment by cnunciato** [comment]
Closing as it's not clear what's to be done for this issue.
