### ISSUE TITLE
Update to /resources

### ISSUE THREAD

**Issue by lindsaymarolich** [pulumi/pulumi-hugo#3100]
We have a handful of events to add to /resources please:

**Platform Engineering Happy Hour with Pulumi and Spot by NetApp**
July 20, 2023
Enjoy a casual session about platform engineering, meet new people and take home some swag. Food, drinks, and a great view from NetApp's office rooftop are on us.
Link: https://www.meetup.com/new-york-pulumi-user-group/events/294358229/

**WeAreDevelopers World Congress**
July 27-28, 2023
We are heading to WeAreDevelopers World Congress. Meet us in-person in Berlin, or request a virtual 1:1 with one of our experts.
Link: https://info.pulumi.com/wearedevelopers-2023

**DASH by Datadog**
August 2-3, 2023
We are heading to DASH 2023. Meet us in-person at Moscone Center, or request a virtual 1:1 with one of our experts. 
Link: https://info.pulumi.com/dash-2023

**New Relic O11y Day**
August 9, 2023
Join Us for New Relic O11y Day: NYC. This event is jam-packed with hands-on lab sessions, lunch, and drinks—and even a little time to network at happy hour.
Link: https://newrelic.com/events/2023-08-09/newrelic-o11yday-nyc

**Google Next**
August 29-30, 2023
We are heading to Google Next 2023. Meet us in-person at Moscone Center, or request a virtual 1:1 with one of our experts.
Link: https://info.pulumi.com/google-next-2023

**GopherCon**
September 26-29, 2023
We are heading to GopherCon 2023. Meet us in-person at the Marriott Marquis in San Diego, or request a virtual 1:1 with one of our experts.
Link: https://info.pulumi.com/gophercon-2023

**Comment by SaraDPH** [comment]
@shughes26 please move the events to "Featured" so only the workshops appear in "Upcoming," the short erm strategy was to have "Feature" become "Events" and "Upcoming" become "Workshops" but at the very least keep them separate so people can find what they are looking for more easily.

**Comment by cnunciato** [comment]
Closing this issue as this appears to have been completed, but feel free to open another if there's work to be done that hasn't been captured elsewhere.
