### ISSUE TITLE
No way to navigate to our older AWS Guides

### ISSUE THREAD

**Issue by cnunciato** [pulumi/pulumi-hugo#3106]
Pages like these still rank highly in search results (external as well as internal), but there's no way to navigate them directly in the UI:

![image](https://github.com/pulumi/pulumi-hugo/assets/274700/f833ff6b-d132-4b20-9421-ad24265a3287)

https://www.pulumi.com/docs/clouds/aws/aws-guides/ec2/

Following the breadcrumb to the "top level" of this section (by clicking "AWS Guides") also leads to this page, which appears to have no descendants and also contains @pulumi/cloud content that we may or may not want to continue featuring in this way. 

We should decide on a path forward for these pages and get their content integrated properly, either into existing AWS Guides or other tutorials.

**Comment by susanev** [comment]
related https://github.com/pulumi/pulumi-hugo/issues/2892

**Comment by cnunciato** [comment]
We should probably pull all of this content (and be sure to redirect properly, and reduce duplication where it makes sense) into https://www.pulumi.com/docs/clouds/aws/guides/.
