### ISSUE TITLE
Blog should have search box

### ISSUE THREAD

**Issue by headconnect** [pulumi/pulumi-hugo#318]
There's just so much in the blog that's absolutely great - and vital to get up and running in a productive way. Unfortunately, it's hard to find stuff in there sometimes, and it would be great to search.

I'm aware that the search function also searches blog content - but there is no searchbar in the blog itself.  Could this be added?

**Comment by jonelleb** [comment]
# Design Goals
It is sometimes hard to find items in the blog. It would be a better user experience if there was a search bar that searched the blog itself, this would cut down the search parameters and make it easier to find particular blog articles.

# [Figma File](https://www.figma.com/file/8kz7uSX7MD430hCwl7q8Ll/Jonelle's-Miscellaneous-Work?node-id=49%3A899)

### Blog Design with New Search Bar

**Blog without scroll**

<img width="614" alt="Screen Shot 2022-03-24 at 8 08 58 AM" src="https://user-images.githubusercontent.com/100616532/159924741-c303c6ee-ab2b-4b8e-988e-2e7773b60e07.png">

**Blog with scroll**

<img width="616" alt="Screen Shot 2022-03-24 at 8 09 09 AM" src="https://user-images.githubusercontent.com/100616532/159924797-93b33f48-1b10-4001-8e5f-24231fcb83f7.png">

# Design Changes
- New search bar added in left nav of blog page right under 'Pulumi Blog' header.
- Please follow the same style, size, and search behavior as search bar on current Docs page.
- On scroll, Pulumi nav is pinned to the top and middle page content scrolls while the left nav with the search bar stays in the same place while the user scrolls (this is the same scroll behavior that the current Docs' page has - please follow that).

# Engineer Notes
- Responsive design should follow the same behavior as current Docs search bar does when that page is responsive (basically the responsive design for Blog stays the same as is now but the search bar is added)
- Comments have been added in Figma but please feel free to reach out with any questions or concerns

Thanks!
