### ISSUE TITLE
Need to update `gcp.service_account` to `gcp.serviceaccount`

### ISSUE THREAD

**Issue by dgdsingen** [pulumi/pulumi-hugo#3183]
File: [themes/default/content/registry/packages/gcp/api-docs/container/cluster/_index.md](https://www.pulumi.com/registry/packages/gcp/api-docs/container/cluster/)

Need to update python sample code in `With A Separately Managed Node Pool (Recommended)` part.

> https://www.pulumi.com/registry/packages/gcp/api-docs/container/cluster/#with-a-separately-managed-node-pool-recommended

```python
import pulumi_gcp as gcp

# "service_account" is not a known member of module "pulumi_gcp".
default = gcp.service_account.Account("default",
...

# Need to update "service_account" to "serviceaccount".
default = gcp.serviceaccount.Account("default",
...
```

You can find related source here.

> https://github.com/pulumi/pulumi-gcp/blob/dfacd8a41f257a7011712346177aea9721e8e882/sdk/python/pulumi_gcp/__init__.py#L187

**Comment by Jaafar-Nasrallah** [comment]
I have a similar issue in [This issue](https://github.com/pulumi/pulumi-gcp/issues/1128)

**Comment by toriancrane** [comment]
This issue is being worked on [here](https://github.com/pulumi/pulumi-gcp/issues/722). Moving to GCP repo/board.

**Comment by toriancrane** [comment]
This issue is being worked on [here](https://github.com/pulumi/pulumi-gcp/issues/722). Closing as a duplicate.
