### ISSUE TITLE
Deletion failed because file exist and force delete is no set 

### ISSUE THREAD

**Issue by JeanJacques92** [pulumi/pulumi-hugo#3206]
File: [themes/default/content/docs/clouds/gcp/get-started/destroy-stack.md](https://www.pulumi.com/docs/clouds/gcp/get-started/destroy-stack/)
![image](https://github.com/pulumi/pulumi-hugo/assets/7045337/59ed9d8f-9cbe-49af-af8d-8919dd0fcc18)

**Comment by danielrbradley** [comment]
Hi @JeanJacques92 a couple of questions to understand how you got to the error you're seeing:
1. During the destroy, did you see the `index.html` BucketObject get deleted before Pulumi attempted to delete the bucket?
2. Did you create additional files within the bucket before trying to delete it?

**Comment by JeanJacques92** [comment]
Hi @danielrbradley, 
I think, I followed the quickstart start guide.
1. There was still an index.html file in the bucket.
2. I did not add any other files to the bucket
I can try again from scratch to confirm the result

**Comment by interurban** [comment]
@danielrbradley one thing to note from @cnunciato is Christian did a major update to the GCP getting started guide; if it was a docs related bug I hope this is solved now. Any sense if we can close this issue as resolved?

**Comment by danielrbradley** [comment]
Yes, @cnunciato assuming you've re-tested this process while re-working the GCP getting started guide and this issue didn't occur any more, feel free to close this as completed.

**Comment by cnunciato** [comment]
Yep, this issue was fixed with https://github.com/pulumi/pulumi-hugo/pull/3221!
