### ISSUE TITLE
I suggest removing the Sid property from the IAM page example.

### ISSUE THREAD

**Issue by dev-yyh** [pulumi/pulumi-hugo#3215]
File: [themes/default/content/docs/clouds/aws/guides/iam.md](https://www.pulumi.com/docs/clouds/aws/guides/iam/)

As mentioned in this review(https://github.com/pulumi/pulumi-hugo/pull/3209#pullrequestreview-1555365666), the `Sid` property is optional and the "" value isn't significant, 
so it looks good to remove it.

**Comment by cnunciato** [comment]
Fixed via #3216.
