### ISSUE TITLE
Sentence is not complete

### ISSUE THREAD

**Issue by fabl3ss** [pulumi/pulumi-hugo#3218]
File: [themes/default/content/docs/concepts/resources/functions.md](https://www.pulumi.com/docs/concepts/resources/functions/)

In the provider functions variations, the first item I assume should be a continuation of a sentence, not just "and,"
_a function that accepts plain arguments (strings and so on) and returns a Promise, or blocks until the result is available; and,_

URL to this item: https://www.pulumi.com/docs/concepts/resources/functions/#:~:text=a%20function%20that%20accepts%20plain%20arguments%20(strings%20and%20so%20on)%20and%20returns%20a%20Promise%2C%20or%20blocks%20until%20the%20result%20is%20available%3B%20and%2C

**Comment by interurban** [comment]
thanks @fabl3ss for the issue and helping us improve our docs, it's an easy fix and we have a PR in the works.
