### ISSUE TITLE
Running Containers on ECS Fargate is out of date

### ISSUE THREAD

**Issue by interurban** [pulumi/pulumi-hugo#3233]
Per a recent new user email:  GitHub and the official documentation are out of sync. For example, the following tutorial contains faulty code on the documentation website (but the issues have since been corrected in the GitHub code repository):  https://www.pulumi.com/registry/packages/aws/how-to-guides/ecs-fargate/

**Comment by toriancrane** [comment]
Related to [#9581](https://github.com/pulumi/docs/issues/9581)
