### ISSUE TITLE
access tokens permission table misleading

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#3287]
https://www.pulumi.com/docs/pulumi-cloud/access-management/access-tokens/

this is totally my fault, sorry.
but, the personal tokens column makes it seem like personal tokens can only take limited actions, but that's not true (unless that has changed recently), personal tokens have the exact permissions as your user, so if your user has permission to list users in an org (for example) then ur personal token does as well. so i think almost everything in that column needs a checkmark.
also, may consider reverting the reorder that happened in https://github.com/pulumi/pulumi-hugo/pull/3137

will leave this to @AaronFriel and @djgrove who absolutely know more than i do.

**Comment by interurban** [comment]
Thank you so much @susanev for capturing this one, we'll triage and get a fix out.

**Comment by EvanBoyle** [comment]
Thanks for reporting.

I'm inclined not to change anything after reading the issue. Personal tokens do have those permissions by default unless you are an admin, which there is an entry for in the table. Admins, whether user admins or org admin tokens, have those same set of elevated permissions.
