### ISSUE TITLE
Clarify usage of ".NET" vs individual language names

### ISSUE THREAD

**Issue by infin8x** [pulumi/pulumi-hugo#332]
### Problem description

A [Twitter user](https://twitter.com/dpihac/status/1404888914691858440) mentioned that we use ".NET" and/or ".NET Core" in several places where we should instead refer to specific languages.

### Suggestions for a fix

- Remove the .NET Core image from the center column of the spinner on pulumi.com. Every other item in that column is specifically a programming language.
- Leave pulumi.com/product’s “Your Clouds, Your Languages, Your Workflows” alone. There’s no real good way to shoehorn something like “Languages/runtimes”, and the “Your languages” string is also core to our marketing verbiage. I think most people could look at that box and understand that the first logo means they can use JavaScript/Typescript and that the last logo means they can use any .NET framework language, which is true.
- On pulumi.com/cloud-engineering, change the heading to “Standard programming languages & runtimes”.

**Comment by susanev** [comment]
these are my thoughts.

- i dont think we need to remove it from the slot machine, there isn't a clear label there describing the different slots.
- there are diagrams on the home page and the products page that the original report was referring to, is there alignment in leadership that we want to adjust these diagrams? if so let me know, happy to do that work
- for the cloud-eng heading, id prefer to use the same casing scheme as the rest of the sections

**Comment by cnunciato** [comment]
Several of these pages have been updated since this issue was filed, and we don't have any plans to make any fundamental/site-wide changes to address this, so I'm closing for now.
