### ISSUE TITLE
Readability issue in styling, or in python pkg

### ISSUE THREAD

**Issue by mcint** [pulumi/pulumi-hugo#3335]
File: [themes/default/content/docs/reference/pkg/python/pulumi/_index.md](https://www.pulumi.com/docs/reference/pkg/python/pulumi/)
![Screenshot_20230904_141801](https://github.com/pulumi/pulumi-hugo/assets/601708/89ace687-a1c1-48c1-9dc6-75153260d4c7)

**Comment by interurban** [comment]
Thank you for submitting this issue @mcint ; we'll get this fixed

**Comment by cnunciato** [comment]
Closing this issue as we're now delivering our Python SDK docs differently (as of https://github.com/pulumi/docs/pull/10279). Thanks again for submitting this -- and hope you like the improvements!
