### ISSUE TITLE
Update What is Infrastructure As Code article

### ISSUE THREAD

**Issue by interurban** [pulumi/pulumi-hugo#3374]
## Hello!

- Vote on this issue by adding a 👍 reaction
The following conceptual page could be made more valueable and helpful to the infrastructure as code and devops community. https://www.pulumi.com/what-is/what-is-infrastructure-as-code/

This work item tracks the enhancements we'll be making to make the content more authoritative, and illustrative (with the use of a diagram and short form video).

**Comment by scottslowe** [comment]
@interurban Is this addressed via the recent update I made to that page?

**Comment by cnunciato** [comment]
Closing this as fixed via https://github.com/pulumi/pulumi-hugo/pull/3561 (as I'm not aware of further work planned for this page), but feel free to reopen if there's more to be done here.
