### ISSUE TITLE
Lambda documentation new keyword used in getting existing s3 bucket.

### ISSUE THREAD

**Issue by SahanAmarsha** [pulumi/pulumi-hugo#344]
### Problem Description
File: [themes/default/content/docs/guides/crosswalk/aws/lambda.md](https://www.pulumi.com/docs/guides/crosswalk/aws/lambda/)

```
import * as aws from "@pulumi/aws";

// Look up an S3 bucket that already exists in our account.
const docsBucket = new aws.s3.Bucket.get("docs", "arn:aws:s3:::docs-4f64efc");

// Create an AWS Lambda event handler on our bucket using magic functions.
docsBucket.onObjectCreated("docsHandler", (e) => {
    // your lambda code goes here
});
```

Running this example would result in an error,

`
TypeError: aws.s3.Bucket.get is not a constructor
`

### Fix
We can **remove the new keyword** when calling  aws.s3.Bucket.get();

**Comment by leezen** [comment]
Thanks for pointing this out!
