### ISSUE TITLE
Download & Install Pulumi ESC: "other installation methods" and "installation script" repeat once for every OS in nav

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-hugo#3465]
### What happened?

<img width="1293" alt="image" src="https://github.com/pulumi/pulumi-hugo/assets/410614/12b7d7d3-1720-4a28-9da9-8fb4bf901597">

### Example

n/a

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by interurban** [comment]
We've tracked down the why; but the fix is still under investigation:

**Comment by desteves** [comment]
This is a duplicate, tracking under #3548 therefore I will go ahead and close this one.

**Comment by interurban** [comment]
Also, as we applied the page level fix, there's still a site wide (potential bug) where the right nav of the docs site sometimes contains repeated elements. Tracked here: https://github.com/pulumi/pulumi-hugo/issues/3584
