### ISSUE TITLE
ESC CLI Login references pulumi login

### ISSUE THREAD

**Issue by toriancrane** [pulumi/pulumi-hugo#3480]
File: [themes/default/content/docs/esc-cli/commands/esc_login.md](https://www.pulumi.com/docs/esc-cli/commands/esc_login/)

On this page, we have the following content:

By default, this will log in to the managed Pulumi Cloud backend. If you prefer to log in to a self-hosted Pulumi Cloud backend, specify a URL. For example, run

```bash
$ pulumi login https://api.pulumi.acmecorp.com
```

Should this be `esc login` instead? If not, what is the reason for referencing `pulumi login` here?

**Comment by komalali** [comment]
yeah I think that whole section about logging into self-hosted shouldn't be there. but these are auto-gen'd docs so might need some fixing in the esc repo.

**Comment by cnunciato** [comment]
It looks like this has already been fixed, but the docs haven't been updated:

https://github.com/pulumi/esc/commit/d7c76709a97e921195c2768cc0edccf0f258a97b

I'll look into getting these updated and report back.
