### ISSUE TITLE
ESC installation table of contents has repeated elements

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-hugo#3548]
File: [themes/default/content/docs/install/esc.md](https://www.pulumi.com/docs/install/esc/)

It looks like this might have something to do with the platform selection.
![Screenshot 2023-10-27 at 11 25 11 AM](https://github.com/pulumi/pulumi-hugo/assets/9253463/534b53f8-7dec-49d5-b395-8c117541e680)

**Comment by desteves** [comment]
This is happening because the header markdown exists inside the language short code.

**Comment by desteves** [comment]
I'm moving it....
