### ISSUE TITLE
Code examples should be complete enough to run

### ISSUE THREAD

**Issue by 1oglop1** [pulumi/pulumi-hugo#355]
Hi, I'm reading through the documentation and quite often I find code examples that look like they were taken away from a bigger sample and therefore miss the context around. 
It would be much better if the example would be complete so I can copy paste it and run or at least it could link to the original source.

Here is such an example on this page: [themes/default/content/docs/reference/pkg/aws/ec2/defaultsecuritygroup.md](https://www.pulumi.com/docs/reference/pkg/aws/ec2/defaultsecuritygroup/)

If I copy paste the examples I get `TypeError`, `ImportError` and other errors because the static method cannot live outside the class.

```python
@staticmethod
def get(resource_name: str,
        id: str,
        opts: Optional[ResourceOptions] = None,
        arn: Optional[str] = None,
        description: Optional[str] = None,
        egress: Optional[Sequence[DefaultSecurityGroupEgressArgs]] = None,
        ingress: Optional[Sequence[DefaultSecurityGroupIngressArgs]] = None,
        name: Optional[str] = None,
        owner_id: Optional[str] = None,
        revoke_rules_on_delete: Optional[bool] = None,
        tags: Optional[Mapping[str, str]] = None,
        tags_all: Optional[Mapping[str, str]] = None,
        vpc_id: Optional[str] = None) -> DefaultSecurityGroup
 ```

For example the Pydantic has an excellent documentation where I can run all examples.

https://pydantic-docs.helpmanual.io/#example

Thank you!

**Comment by leezen** [comment]
Generally, the examples are meant to be snippets and not fully executable programs. For fully executable programs, you may want to take a look at https://github.com/pulumi/examples. The examples in documentation are there to help provide a sense of how to use the functions and resources.
