### ISSUE TITLE
CLI installation table of contents has repeated element

### ISSUE THREAD

**Issue by interurban** [pulumi/pulumi-hugo#3583]
page: https://www.pulumi.com/docs/install/

![image](https://github.com/pulumi/pulumi-hugo/assets/73448/43ea6032-0bb6-45df-b672-c0906e221c1d)

**Comment by interurban** [comment]
hey @desteves can you apply your fix to this page as well! thank you!

**Comment by desteves** [comment]
@interurban See PR https://github.com/pulumi/pulumi-hugo/pull/3588

**Comment by desteves** [comment]
PR https://github.com/pulumi/pulumi-hugo/pull/3625
