### ISSUE TITLE
Error in Azure Python AKS example

### ISSUE THREAD

**Issue by spara** [pulumi/pulumi-hugo#36]
https://github.com/pulumi/examples/blob/master/azure-py-aks/__main__.py

KubeDashboard is deprecated and breaks example

addon_profiles={
         "KubeDashboard": {
             "enabled": True,
         },
     },

**Comment by stack72** [comment]
Hi @spara should this be in this repo or in the examples repo? Or is this linked to a tutorial?

**Comment by spara** [comment]
wrong repo - too many tabs open
