### ISSUE TITLE
Python examples throw error: "missing 1 required keyword-only argument: 'name'"

### ISSUE THREAD

**Issue by automagic** [pulumi/pulumi-hugo#3615]
File: [themes/default/content/docs/clouds/aws/guides/ecs.md](https://www.pulumi.com/docs/clouds/aws/guides/ecs/)

The python examples on this page throw the following error:

```
Diagnostics:
  pulumi:pulumi:Stack (awsx-py-ecs-fargate-dev):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/Users/james/Code/awsx-py-ecs-fargate/__main__.py", line 31, in <module>
        container=awsx.ecs.TaskDefinitionContainerDefinitionArgs(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: TaskDefinitionContainerDefinitionArgs.__init__() missing 1 required keyword-only argument: 'name'
```

`name` is a required argument on `awsx.ecs.TaskDefinitionContainerDefinitionArgs`, and adding name as an argument allows the stack to successfully deploy.

**Comment by toriancrane** [comment]
Thank you @automagic for submitting this issue! We will take a look into getting this resolved.

**Comment by interurban** [comment]
I suspect this is also broken in other places, but did confirm the fix for this page.
