### ISSUE TITLE
Bump pulumi program dependencies automatically

### ISSUE THREAD

**Issue by desteves** [pulumi/pulumi-hugo#3762]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently, we have to manually update the `go.mod` files for the Pulumi program examples. This quickly become stale as dependencies have their own update cycles. We want to always test our examples against the latest versions.

### Affected area/feature

Pulumi programs in the hugo repo.

### Possible solution

Investigate the use of something like the Dependabot to automatically update these programs.

**Comment by cnunciato** [comment]
There's some [prior art in pulumi/templates](https://github.com/pulumi/templates/blob/master/generator/generate-go-mod.sh) for this (where we do the same sort of thing to generate [PRs like this one](https://github.com/pulumi/templates/pull/715)), but  there may be a better/more maintainable way to do it.
