### ISSUE TITLE
Invalid/Incomplete example

### ISSUE THREAD

**Issue by irl-segfault** [pulumi/pulumi-hugo#378]
File: [themes/default/content/docs/reference/pkg/tls/getcertificate.md](https://www.pulumi.com/docs/reference/pkg/tls/getcertificate/)

Hi all,

The example here references a variable `exampleCertificate` that is presumably the result of a `GetCertificate` call but the example does not show this call ever being used.

**Comment by irl-segfault** [comment]
JFYI this code is probably just totally broken.  The `*GetCertificateResult` returned from `GetCertificate` doesn't even have the `ApplyT` method that is used in this example.

**Comment by lukehoban** [comment]
This is the same issue tracked in https://github.com/pulumi/docs/issues/3473, so I'll close this out to track the general case there.
