### ISSUE TITLE
Incorrect syntax

### ISSUE THREAD

**Issue by 1oglop1** [pulumi/pulumi-hugo#406]
Hi, I think that the example of registering outputs in python is incorrect syntax.

File: [themes/default/content/docs/intro/concepts/resources.md](https://www.pulumi.com/docs/intro/concepts/resources/#registering-component-outputs)

## Actual

```
self.register_outputs({
    bucketDnsName: bucket.bucketDomainName
})
```

## Expected

```
self.register_outputs({
    "bucketDnsName": bucket.bucketDomainName
})
```

**Comment by cnunciato** [comment]
@1oglop1 I think you're right! Thanks for letting us know. I'll get a fix for this.

**Comment by cnunciato** [comment]
Added `emergent` but just went ahead and fixed, as it was a quick one.
