### ISSUE TITLE
update cloud eng logo

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#414]
## overivew
update the old cloud eng logo to the new one
use it in the header and remove the logo on the page

logo: https://drive.google.com/file/d/1r2Reugm6fox6nZh71s_10ov3UtSJkrJv/view?usp=sharing

**Comment by zchase** [comment]
The logo was updated in this PR: https://github.com/pulumi/pulumi-hugo/pull/562

Going to close this out but feel free to re-open if something was missed.
