### ISSUE TITLE
Add documentation for the new `typechecker` python runtime option

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi-hugo#4181]
Document https://github.com/pulumi/pulumi/pull/15725

- [ ] At a minimum, update: https://www.pulumi.com/docs/concepts/projects/project-file/
- [ ] Also consider adding a new "Type Checking" section to https://www.pulumi.com/docs/languages-sdks/python/

**Comment by olafurnielsen** [comment]
Could you also update the [Pulumi.yaml JSON schema](https://json.schemastore.org/pulumi.json) in schemastore.org?

Getting a warning from the yaml language server when trying out this new feature:
![Screenshot 2024-04-16 at 12 44 25](https://github.com/pulumi/pulumi-hugo/assets/69799161/b1fc6a2c-5473-497d-8814-813442cbb1bc)
