### ISSUE TITLE
Missing Configuring Secrets Encryption section

### ISSUE THREAD

**Issue by jimmyp** [pulumi/pulumi-hugo#422]
File: [themes/default/content/docs/intro/concepts/config.md](https://www.pulumi.com/docs/intro/concepts/config/)

Multiple other document pages, such as https://www.pulumi.com/docs/intro/concepts/state/#secrets link to this page pointing to a Configuring Secrets Encryption section which no longer seems to exist. The link is https://www.pulumi.com/docs/intro/concepts/config/#configuring-secrets-encryption

**Comment by jimmyp** [comment]
I suspect it is supposed to link to https://www.pulumi.com/docs/intro/concepts/secrets/

**Comment by stack72** [comment]
Closer via #424
