### ISSUE TITLE
redesign marketing top-navigation menus

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-hugo#427]
This is a super minor piece of feedback, however, I find it odd that we grey out the top nav links when you hover over them. Typically in most websites I use, the hover behavior is to make the target link look _more_ activated rather than _less_, and to me greying something out typically indicates it is unimportant, not clickable, etc.

For instance:

![image](https://user-images.githubusercontent.com/3953235/126574035-8ae56077-943a-419c-b833-bfc07e366d62.png)

Notice when I hover over Cloud Engineering, I get:

![image](https://user-images.githubusercontent.com/3953235/126574048-fcb9ea5e-9d44-411b-9c71-517994939cf7.png)

I assume this was intentional (I see in the original website design it was present also), and perhaps I'm the only person with this reaction, however, it strikes me as odd every time I see it so I figured I would mention.

**Comment by joeduffy** [comment]
Ohhh, I now see something subtle I had not realized before. The individual items, when you hover, come back to life:

![image](https://user-images.githubusercontent.com/3953235/126574203-4d05a055-029a-4de5-a2ea-59cd80d52463.png)

Maybe this is because the top-heads are not clickable right now? I.e., I can't just click "Cloud Engineering" or "Learn".

Hmm, but it's strange then that the others get greyed out. How are they suddenly less clickable than the other nav items, simply because I selected the top heading?

Also weird, when I hover over the other top nav items, they also grey out. For example here I am hovering over Products:

![image](https://user-images.githubusercontent.com/3953235/126574280-7a264de6-5920-45f8-9bbe-20c80d1dea0c.png)

**Comment by joeduffy** [comment]
My suggestion would be to remove all greying out, and just highlight the currently hovered item purple/bold/something that stands out.

**Comment by susanev** [comment]
yes, i very much agree that it is very strange that we present these items in this light gray color. I've been wanting to fix it ever since we did the rebrand.

**Comment by susanev** [comment]
some exploration work in [figma](https://www.figma.com/file/AVYzxAC8g4gTOabh2RqfQx/navigation?node-id=0%3A1)

**Comment by susanev** [comment]
this work should be a collaborative effort with @gthuang

**Comment by jonelleb** [comment]
# Design Goals
Design new top-navigation for Pulumi site, including adding new page links and menu items - making sure to consider mobile UI as well.

**Comment by jonelleb** [comment]
# Desktop Design
**FILES:**
- **[Figma File](https://www.figma.com/file/AVYzxAC8g4gTOabh2RqfQx/Marketing-Site-Navigation?node-id=306%3A1799)**
*Comments have been added, but please feel free to reach out with any questions and/or concerns*
- **[Figma Prototype](https://www.figma.com/proto/AVYzxAC8g4gTOabh2RqfQx/Marketing-Site-Navigation?page-id=306%3A1799&node-id=306%3A2733&viewport=246%2C48%2C0.19&scaling=scale-down&starting-point-node-id=306%3A1800)**
*Please view to see examples of interaction*
- **[Google Doc](https://docs.google.com/document/d/1YfKu0BKr31APmyLwUNm0iJKwmfZR68lX2NU9T-CUhCA/edit?usp=sharing)**
*Currently, discussions are taking place in the Google Doc to decide on the final link names and menu items. If there are any changes I will note them in this issue, but just wanted to provide this document as well.*

# Engineer Notes

**NEW DESIGN:**
![Screen Shot 2022-04-28 at 2 19 42 PM](https://user-images.githubusercontent.com/100616532/165831099-c6f56c8c-032f-4f3e-9744-85aa0d927013.png)

Currently on the Pulumi site we have a lot of marketing pages that are hidden throughout the site, so with this redesign we structured the links in a way to bring some of those that we feel may be important or useful to the forefront. 

In this new design we have kept the same main links but have renamed ‘Products’ to ‘Product’ and have given it a dropdown icon and menu.

When a user hovers over any of the links the color changes to purple which matches with our Pulumi primary buttons.  For the links that have menus, we’ve given a short summary of the overall link and for each menu item. There’s some hover change within this as well with the purple and the bolding of the text. There’s also a different icon for each link.

![Screen Shot 2022-04-28 at 2 20 14 PM](https://user-images.githubusercontent.com/100616532/165831784-130e144b-c684-4073-bb40-92ce2c12a999.png)

The product menu is where we’ve added links to the various Marketing pages. Pulumi Overview is the basic products page that is on the site now, but the rest are links to the Marketing pages.

The Learn and Cloud Engineering menu links have remained the same, except with the addition of the Enterprises link in Cloud Engineering.

**Cloud Engineering Menu:**
![Screen Shot 2022-04-28 at 2 19 51 PM](https://user-images.githubusercontent.com/100616532/165831807-c8ae487b-381e-480c-9c47-d7eaaf3d4b23.png)

**Product Menu:**
![Screen Shot 2022-04-28 at 2 20 31 PM](https://user-images.githubusercontent.com/100616532/165832177-3a881799-2735-4eb6-a71d-841dd3f0c186.png)

**Learn Menu:**
![Screen Shot 2022-04-28 at 2 20 43 PM](https://user-images.githubusercontent.com/100616532/165832211-163cec4e-091f-48b4-9665-e5a88c4c57c4.png)

**Comment by susanev** [comment]
closing this as done. mobile nav updates are in progress, but there's a separate issue.
