### ISSUE TITLE
Python documentation is mis-formatted causing it to display oddly

### ISSUE THREAD

**Issue by jspiewak** [pulumi/pulumi-hugo#434]
File: [themes/default/content/docs/reference/pkg/python/pulumi/_index.md](https://www.pulumi.com/docs/reference/pkg/python/pulumi/)

![image](https://user-images.githubusercontent.com/399516/126786329-5d298305-9992-4d8e-bda5-d97f1df28a2a.png)

**Comment by cnunciato** [comment]
Fixed via https://github.com/pulumi/docs/pull/10279.
