### ISSUE TITLE
Add link to old pricing model

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-hugo#443]
Can we either have it linked to from the /pricing page or somewhere that I can send a link to people. Had someone asking what the limitations were of the old Team Starter package was and I didn't know where to point them

**Comment by pierskarsenbarg** [comment]
@susanev sent me a screenshot which should be fine so closing

**Comment by joeduffy** [comment]
There is also always https://web.archive.org/web/20210302165032/https://www.pulumi.com/pricing/ 😄

**Comment by pierskarsenbarg** [comment]
Dammit, I looked on the way back machine but I went with the latest (22nd April) which didn't have any styling for some reason 🤦
