### ISSUE TITLE
evaluate what is required to finish the provider consolidation work

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#446]
evaluate what is required to finish the work in: https://github.com/pulumi/pulumi-hugo/pull/342

this issue is not to finish the work or merge the pr, and is instead to evaluate the level of work required to finish the work

**Comment by joeduffy** [comment]
Are we doing this independent of the registry workstream? I am a big fan of the work, but thought that it would be redundant with most of the registry plans, so figured we'd wait.

**Comment by susanev** [comment]
@joeduffy, i have been advocating that we release this work, its almost done from Dave's description in the pr, and i believe registry is a ways out. i. believe it provides a ton of value that id like to get to users as soon as possible. happy to chat over zoom if im missing context here on why we should wait.

**Comment by cnunciato** [comment]
After spending some time looking through the PR today, here's what it's looking like in terms of remaining work. This probably isn't everything, but it should be fairly close. Rough sizings included to give y'all a sense of the overall picture.

In short, there's still a good deal of work to be done -- so my suggestion, given the work we're planning now and how it'll effectively replace everything in #342 and below (and result in yet more URL/redirect churn/risk, etc.), is to close that PR and just focus instead on what's ahead. Nevertheless, here's what it looks like from my perspective: 

**Functional stuff**

* Add an API Docs item to the nav for each provider. **Small**
* Devise and draft a release plan. **Small**
    * This is necessary because of the coordination that’ll need to be done between pulumi/pulumi (where template updates happen), pulumi/docs (where docs and tutorials will need to be regenerated), pulumi-hugo (which’ll contain the navigational and in-page changes to point to all the new locations), and stakeholders like Paul and others.
* Change the location of generated docs and tutorials in pulumi/docs **Small**
* Merge in the changes to pulumi/pulumi to add new frontmatter params to docs templates (to support the new navigation structure). **Small**
* Update docs templates in pulumi/pulumi to add Hugo aliases for all docs. (To make sure we 301 properly.) **Small** 
* Regenerate all docs and tutorials to add these new params and aliases. **Small**
* Update a lot of relrefs to make sure all of our links (a) work and (b) link to the right places. **Small**
* Run a full integration build to make sure everything actually builds, looks right, and all the 301s do what they’re supposed to. Share that build and address whatever feedback comes out of that. **Small**
* Execute the release plan. **Small**

**Cosmetic stuff**

* Add a summary to the top of the SDK page (where the “TODO” text is now). **Small**
* Show the menu items under Packages (Core Providers, Other Providers) as closed by default. (They're open now, which pushes everything below the Packages section off the page.) **Small**
* Resolve the open naming question ("core" vs. "other", "native" vs. "bridged") and apply whatever changes come out of it. **Small**
* Fix the styling on /docs/tutorials (seems broken). **Small**
* Validate that the content changes introduced in the PR are correct. **Small**
    * Changes of “providers” -> “packages” in code snippets — is this right? Is what we have today wrong?
    * Should the new index page be called Packages or Providers? (Nav currently says Packages, but H1 is Providers.)

**Comment by cnunciato** [comment]
Closing this as the evaluation is complete.
