### ISSUE TITLE
serviceAccount should be changed to serviceaccount

### ISSUE THREAD

**Issue by cangussu** [pulumi/pulumi-hugo#477]
Typescript: All the examples are using `serviceAccount`, but the real code is actually `serviceaccount`.

File: [themes/default/content/docs/reference/pkg/gcp/serviceAccount/_index.md](https://www.pulumi.com/docs/reference/pkg/gcp/serviceaccount/)

**Comment by susanev** [comment]
im going to close this out as a dupe of https://github.com/pulumi/registry/issues/758
i know this one was opened earlier, but the related user experience has been moved to the registry
