### ISSUE TITLE
Incorrect ProjectEnvironmentEnvironmentVariable "type" documentation

### ISSUE THREAD

**Issue by youanden** [pulumi/pulumi-hugo#483]
File: [themes/default/content/docs/reference/pkg/aws/codebuild/project/_index.md](https://www.pulumi.com/docs/reference/pkg/aws/codebuild/project/)

So actually, the TYPE should be one of: [PLAINTEXT PARAMETER_STORE SECRETS_MANAGER]

It looks like it was copied from source in a few areas. 

Attempting to build with any of the variables provided would give us something like this:

```
error: aws:codebuild/project:Project resource 'codebuild-project' has a problem: 
expected environment.0.environment_variable.4.type to be one of 
[PLAINTEXT PARAMETER_STORE SECRETS_MANAGER], got CODECOMMIT. 
Examine values at 'Project.Environment.EnvironmentVariable[4].Type'.
```

**Comment by lukehoban** [comment]
This is fixed - I expect with https://github.com/pulumi/pulumi-terraform-bridge/pull/712.
