### ISSUE TITLE
Docs are not correct

### ISSUE THREAD

**Issue by ShayDahan99** [pulumi/pulumi-hugo#493]
File: [themes/default/content/docs/reference/pkg/aws/appautoscaling/policy/_index.md](https://www.pulumi.com/docs/reference/pkg/aws/appautoscaling/policy/)

            metricIntervalUpperBound: 0, is not number but string

**Comment by lukehoban** [comment]
I believe this is now correct.  I'm not 100% sure what was seen at the time this was opened - but there have been some fixes since that could have improved this.
