### ISSUE TITLE
gcp.dns.ManagedZone does not have a nameServers argument

### ISSUE THREAD

**Issue by VikramVasudevan** [pulumi/pulumi-hugo#508]
File: [themes/default/content/docs/reference/pkg/gcp/dns/managedzone/_index.md](https://www.pulumi.com/docs/reference/pkg/gcp/dns/managedzone/)

The document states that there is a state argument called nameServers but there is none in the code like this. Does the document need correction or the code?

**Comment by stack72** [comment]
Hi @VikramVasudevan 

Thanks so much for the question here - I do see the output - https://github.com/pulumi/pulumi-gcp/blob/master/sdk/nodejs/dns/managedZone.ts#L231

I am not sure what version of pulumi-gcp that you are using, maybe that would be the issue if it's an older version?

Thanks

Paul

**Comment by stack72** [comment]
I am going to close this out - I can see the argument in the current documentation and in the SDK as linked above. If this continues to be an issue, please let us know a version and we can look into this more
