### ISSUE TITLE
use descriptive page names instead of _other_ in the docs

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#560]
## overview
i noticed we use _other_ to describe a few pages, which isn't very helpful to folks scanning the nav because its not descriptive. id like to propose we update this page names and URLs and add redirects.

## design details
- [x] change o[ther in continuous delivery](https://www.pulumi.com/docs/guides/continuous-delivery/other/) to `Create New CI/CD Integration`
- [x] change [other in crosswalk for aws](https://www.pulumi.com/docs/guides/crosswalk/aws/other/) to `AWS Index of Services`
- [x] change [pulumi vs other ](https://www.pulumi.com/docs/intro/vs/)to `Compare Pulumi to...` h/t @infin8x

**Comment by susanev** [comment]
@infin8x @cnunciato @praneetloke @lukehoban 
do yall have any thoughts on this?
are there other places we currently use _other_ that i missed?

**Comment by infin8x** [comment]
Agreed we should fix this, good shout. And, agree with all of your suggestions.
