### ISSUE TITLE
docs navigation usability improvements

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#561]
_this issue is still in ux development and is not yet ready for eng work_

## design details
- [x] any top-level item that has children can be expanded/collapsed
- [ ] any top-level item that has children should not have a page associated with it; in situations where that page was not repeating information, add an `Overivew` page as a child instead
- [x] search should always be visible, even if they scroll down in the left nav
- [x] a user can expand/collapse menus in any configuration they want, i.e., expanding a menu should not close other menus
- [x] if a user configures the open menus so that part of the left nav is no longer visible then a scroll bar should be visible, even on osx (we should also consider other affordances to communicate more content)
- [x] expanding a left nav menu should not send the left nav up to the top in the user's view (pretty sure this does a page reload currently)

**Comment by cnunciato** [comment]
> any top-level item that has children should not have a page associated with it; in situations where that page was not repeating information, add an Overivew page as a child instead

Would love to talk more with y'all about this one.

**Comment by susanev** [comment]
@anita-trimbur what do you think? should we close this out and move the last checkbox into its own issue?

**Comment by anita-trimbur** [comment]
sounds good! i'll open another issue for the parent pages
