### ISSUE TITLE
difficult to navigate between different pulumi sdks

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#591]
_this issue was orignally reported by @aureq_

## overview
its not easy to figure out how to navigate from one pulumi/pulumi language sdk to another
e.g., if you are here https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/ there's no clear way to get here https://www.pulumi.com/docs/reference/pkg/python/pulumi/ and notice the change in URL, so if folks try and edit the URL directly to python they will get a 404

## proposed considerations
consider a navigation structure that makes it easy to move between the pages

**Comment by infin8x** [comment]
@susanev and @aureq thanks for filing this. As a stop-gap, I wonder if we could, as part of https://github.com/pulumi/pulumi-service/issues/7390, add languages as sub-options under `Reference > Pulumi SDK`?

**Comment by susanev** [comment]
yes, i asked for that here as well: https://github.com/pulumi/pulumi-hugo/pull/351#issuecomment-864453999
but @cnunciato's suggestion did not end up working once it got to doocs.

**Comment by infin8x** [comment]
ah gotcha. OK, I added this to https://github.com/pulumi/pulumi-hugo/issues/591 so we can take a second swing at it.
