### ISSUE TITLE
top navigation changes

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#592]
## overview
we need to make a few changes to our top navigation
this was a collaborative effort with @infin8x jay and @susanev 

## design details

- [ ] change the learn menu to be `Blog`, `Learn Pulumi`, `Events & Workshops`
    - [ ] link to the new learn platform in the learn pulumi item
    - [x] remove `Tutorials` from the learn menu
    - [ ] rename `Resources` to `Events & Workshops`
    - [ ] change the page name of `Resources` to `Events & Workshops`
    - [ ] optional but would be nice to update the learn platform URL to `learn-pulumi`
- [ ] note the desktop and mobile navs are defined in separate code pieces, pls update both versions of the nav

### screenshot
<img width="1342" alt="top-nav" src="https://user-images.githubusercontent.com/5489125/133838439-d6c7004b-3239-4ba6-86b9-8b33da91d610.png">
## notes about choices and direction

- we are moving to a practitioner-focused top-top nav
- resources and workshops link to the same page just with a different filter, so collapsing that into one item with a more descriptive name
- tutorials is being removed as its being rebranded as how-to guides and moving to registry which will be in the top-top nav
- we want to keep the learn top nav item because its generic enough to describe the bucket of learning resources, and we are going to brand the new platform as Learn Pulumi to differentiate
- we believe the current nav structure is working well overall, its clear what we do and what our value is so we don't want to make major changes to it as part of this work

**Comment by susanev** [comment]
this is blocked because this work shouldnt happen until cloud eng summit

**Comment by joeduffy** [comment]
Just a reminder for posterity, we agreed to keep the GitHub star widget :-)

**Comment by susanev** [comment]
yah, i updated the text to say that, just haven't gotten to fixing the screenshot yet.

**Comment by susanev** [comment]
a pr for this work will be opened up on 10/14.
still working on the plan for when it will merge, will update when i know that.

**Comment by praneetloke** [comment]
@zchase my attempt at relocation `resources` to `events-workshops` failed. It's explained in this [comment](https://github.com/pulumi/pulumi-hugo/pull/671#issuecomment-932447881).

**Comment by susanev** [comment]
im going to close this, most of this was done already
