### ISSUE TITLE
Doc search is broken (Safari)

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-hugo#602]
## Steps to reproduce

1. Open Safari
2. Type something into the search box
3. Hit enter

Expected: A search window to appear center screen, and the rest of the screen greyed out. 
Actual: Only the side bar greyed out. Search didn't show up. I think they do show up in some way, cause I can click on them (hence the mouse icon change), but they are not visible. 

https://user-images.githubusercontent.com/22222529/133693093-09011d21-98ec-485d-b8eb-751f70341ae6.mov

**Comment by lukehoban** [comment]
Related, in Chrome on Mac, the nav doesn't dim correctly when the search modal comes up.   There was an attempt to fix this in https://github.com/pulumi/pulumi-hugo/pull/533, but it was reverted in https://github.com/pulumi/pulumi-hugo/pull/542.

<img width="1792" alt="Screen Shot 2021-09-16 at 3 12 31 PM" src="https://user-images.githubusercontent.com/223467/133704224-b0665ad9-2e1c-4e05-a5ef-a0dfb06a3ea4.png">

**Comment by susanev** [comment]
https://github.com/pulumi/pulumi-hugo/issues/602#issuecomment-921348103 is fixed in https://github.com/pulumi/pulumi-hugo/pull/603

**Comment by djgrove** [comment]
Not fixed until the theme is updated in Hugo

**Comment by djgrove** [comment]
Hugo uses the latest version of the Theme, so I will consider this fixed.
