### ISSUE TITLE
On linux, logging into an S3 compatible backend requires double quotes

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-hugo#610]
See here: https://www.pulumi.com/docs/intro/concepts/state/#logging-into-the-aws-s3-backend

Instead of `pulumi login s3://<bucket-name>?endpoint=my.minio.local:8080&disableSSL=true&s3ForcePathStyle=true` it should be `pulumi login "s3://<bucket-name>?endpoint=my.minio.local:8080&disableSSL=true&s3ForcePathStyle=true"`

**Comment by infin8x** [comment]
@pierskarsenbarg are you asking just for a docs update or advocating that we should remove the need for double-quotes?

**Comment by toriancrane** [comment]
The [login code example ](https://www.pulumi.com/docs/concepts/state/#aws-s3) has already been updated with quotes. 

`pulumi login 's3://<bucket-name>?endpoint=my.minio.local:8080&disableSSL=true&s3ForcePathStyle=true'`

Is this still an issue @pierskarsenbarg?
