### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by kfontaine-skyhook** [pulumi/pulumi-hugo#621]
File: [themes/default/content/docs/reference/pkg/eks/cluster/_index.md](https://www.pulumi.com/docs/reference/pkg/eks/cluster/
![Screen Shot 2021-09-22 at 10 31 49 AM](https://user-images.githubusercontent.com/46328696/134363404-8d13635c-b913-4e04-911c-6db93df75dde.png)
)

**Comment by chrsmith** [comment]
Thank you for the bug report. As GitHub helpfully pointed out, this should be fixed when https://github.com/pulumi/pulumi-eks/pull/625 gets merged.
