### ISSUE TITLE
Group content related to adopting, comparing, and converters into one section in the docs

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#628]
## overview
right now we have adopting content, comparing content, and converters in 3 separate sections. lets group these together

## design details
- [ ] create a top-level item of `Adopting Pulumi`
- [ ] add `Compare Pulumi to...`, `Converters`, `Importing Infrastructure`, and `Moving From...` as the adopting children
- [ ] setup redirects for all changes
- [ ] place this new section below the getting started section

### screenshot
<img width="530" alt="Screen Shot 2021-09-23 at 12 45 23 PM" src="https://user-images.githubusercontent.com/5489125/134573825-9dfb3a28-8171-44dd-b93f-ccf21a2d3ed3.png">

**Comment by susanev** [comment]
@zchase the proposal here would mean that `https://www.pulumi.com/docs/intro/vs/terraform/` would become `https://www.pulumi.com/docs/adopting-pulumi/vs/terraform/` page names and headings would be unchanged, and i can include a redirect. will this negatively impact SEO?

**Comment by zchase** [comment]
@susanev That should be a fine change. I think the most important thing is that the page title remain `Pulumi vs Terraform`.

**Comment by susanev** [comment]
hold on any work here, potentially until after a major restructuring in information.

**Comment by cnunciato** [comment]
Closing as mostly complete, and we've no further plans to make changes here.
