### ISSUE TITLE
Add Cloud Engineering Summit CTA to homepage

### ISSUE THREAD

**Issue by lindsaymarolich** [pulumi/pulumi-hugo#648]
Can we please add a more prominent CTA for the upcoming Cloud Engineering Summit to the home page? I've added a [suggested style here](https://drive.google.com/file/d/18voNf2dS7oxI-yScsyQ8VsMYCS-RM_BM/view?usp=sharing), but definitely open to other options. We may want to do a banner takeover in the week or two leading up to the summit as well.

**Comment by susanev** [comment]
this looks fine to me!
