### ISSUE TITLE
update marketing pages to mention registry where it makes sense

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#668]
on the release of registry, we want to mention registry where appropriate and link to registry where appropriate

pr for this work should be opened on the 13th, still working on when it should be merged will update when i know

**Comment by lukehoban** [comment]
It is mentioned in all the places I'd expect - including header and footer of all pages, as well as on https://www.pulumi.com/product/packages/.  Closing out as fixed.
