### ISSUE TITLE
Python does not have props, but args

### ISSUE THREAD

**Issue by 1oglop1** [pulumi/pulumi-hugo#684]
This issue is a result of the discussion on slack with @jaxxstorm.

This page: File: [themes/default/content/docs/reference/pkg/python/pulumi/_index.md](https://www.pulumi.com/docs/reference/pkg/python/pulumi/)

Says that Resources have `props` but that is not true in Python because this argument is named `args` and later in the resource code is `args` assigned to `__props__`

In python the resource can take `XxxArgs` object or arguments can be passed directly to the initializer.

Resource `__init__`can take args or arguments directly
```
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ZoneArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
```
`args` is later in the code assigned to `__props__`
And since `__init__` method has multiple overrides it allows the creation of the resource in multiple ways.
* Example using `args` (`props`).
```
route53.Zone(
    args=route53.ZoneArgs(name="example.com")
)
```

* Example instantiating the resource directly
```
route53.Zone(name="example.com")
```

I have a feeling that the `props` argument name came from JS/TS in this case and therefore is a typo in docs.
As for the usage of props, here is an example.
https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/#CustomResource-constructor

**Comment by komalali** [comment]
In the case of component resources, the props are largely for display purposes. (i.e. to render a diff in the component’s inputs during an update). 

This is not a typo, args are different than props. The [base class](https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/resource.py#L868) accepts `props`.
