### ISSUE TITLE
Incorrect Python Syntax

### ISSUE THREAD

**Issue by kjenney** [pulumi/pulumi-hugo#699]
File: [themes/default/content/docs/intro/concepts/assets-archives.md](https://www.pulumi.com/docs/intro/concepts/assets-archives/)

`pulumi.AssetArchive` instead of `pulumiAssetArchive`

**Comment by leezen** [comment]
Thank you for reporting. Fixed in https://github.com/pulumi/pulumi-hugo/pull/549
