### ISSUE TITLE
we need a third nav design

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#73]
on pages with a third nav, the nav is extremely easy to miss, we need a properly designed third nav

an example from the brand page (logos/colors is the nav)
https://www.pulumi.com/brand/
<img width="1915" alt="brand-page" src="https://user-images.githubusercontent.com/5489125/154309604-d8a8b643-e47f-4ca0-9bcd-a24f2ac9aa4d.png">

**Comment by jonelleb** [comment]
### Design Goals
---
- Current third nav design is too easy to miss, we need a new design that brings more attention to it.

### Examples of Third Navs on the Site
---
- Brand Resources: https://www.pulumi.com/brand 
- Resources: https://www.pulumi.com/resources/#all
- Case Study Pages: https://www.pulumi.com/case-studies/  

### Additional Notes
---
We've decided that the Resources and Brand Resources pages will have a tab design similar to the design that we currently have for tabs, but with a few modifications. All throughout the site wherever tabs like this are used should be updated to keep consistency.  The Case Study pages will have more of a table of contents type of design and will not be using the new tab design.

**Comment by susanev** [comment]
@jonelleb lets keep this issue for brand and resources only, and move that over to ready. and then open a new issue to tackle that case study pages.

**Comment by jonelleb** [comment]
# Resources Page

[Figma File] (https://www.figma.com/file/VRCp6m8TyfCN4tZugJiyh7/Third-Nav-Design?node-id=31%3A548/ "Title")

[Figma Prototype] (https://www.figma.com/proto/VRCp6m8TyfCN4tZugJiyh7/Third-Nav-Design?node-id=41%3A2318&scaling=scale-down&page-id=31%3A548&starting-point-node-id=41%3A2318/ "Title")
**(Prototype shows hover states and gives examples of interactions)**

# 3rd Nav / Tab Design Changes
- The text for the active tab (w/ rainbow colored indicator line) now has a medium weight font.
- Icons have been added 8px to the left of text (using the same icons that are currently being used on this page)
- Inactive tabs no longer have indicator lines underneath text.
- I'm suggesting that we limit the number of links within the nav to 5. If there are more than 5 links, a carrot icon should appear on the right side of the nav that will allow the user to scroll to the right. 
- Left carrot icon appears once the user starts scrolling to the right. The left scroll icon disappears again when user scrolls back to the left; only appears when needed.

## Additional Page Changes
- A bigger size of the corresponding icon is next to the page title.

<img width="900" alt="Screen Shot 2022-03-08 at 2 08 12 PM" src="https://user-images.githubusercontent.com/100616532/157318581-394b5790-cb6f-4cec-b952-235dd27cba2f.png">
<img width="904" alt="Screen Shot 2022-03-08 at 2 09 10 PM" src="https://user-images.githubusercontent.com/100616532/157318620-261b58a0-0e9a-49da-80c0-82e5690c1140.png">

# Handoff Notes
- Comments have been added in Figma but please feel free to reach out with any questions or concerns
- Mobile design is included in Figma file (size: 375px)

**Comment by jonelleb** [comment]
# Brand Resources Page

[Figma File](https://www.figma.com/file/VRCp6m8TyfCN4tZugJiyh7/Third-Nav-Design?node-id=3%3A273)
[Figma Prototype](https://www.figma.com/proto/VRCp6m8TyfCN4tZugJiyh7/Third-Nav-Design?node-id=3%3A1034&scaling=scale-down-width&page-id=3%3A273&starting-point-node-id=3%3A1034&show-proto-sidebar=1)
*(Prototype shows hover states and gives examples of interactions - there are two prototype flows, one for desktop and one for mobile )*

# 3rd Nav / Tab Design Changes
- The text for the active tab (w/ rainbow colored indicator line) now has a medium weight font.
- Inactive tabs no longer have indicator lines underneath text.
- New Tab Behavior: Content below tabs should change according to the tab that the user is on (currently the tabs act as anchor links)

# Additional Page Changes
- New Tab Behavior *(mentioned above)*

<img width="1432" alt="Screen Shot 2022-03-08 at 2 36 08 PM" src="https://user-images.githubusercontent.com/100616532/157320568-0ed5fd01-fc4d-4236-8dd5-8162c4ab9256.png">
<img width="1435" alt="Screen Shot 2022-03-08 at 2 36 18 PM" src="https://user-images.githubusercontent.com/100616532/157320579-fa2b98d4-93f6-444b-8d96-d62f3f8fc350.png">

# Handoff Notes
- Comments have been added in Figma but please feel free to reach out with any questions or concerns
- Mobile design is included in Figma file (size: 375px)

**Comment by susanev** [comment]
this was done 28 days ago, we missed closing it, apologies.
