### ISSUE TITLE
on the resources page, lets use different colors for different resource types

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#74]

**Comment by jonelleb** [comment]
This is being handled through the Issue #73 - both the Resources and Brand Resources page will use the same third nav tab design.

**Comment by jonelleb** [comment]
@susanev - can this ticket be closed since we're handling both Resources and Brand Resources on another ticket?

**Comment by susanev** [comment]
yup, sounds good to me! add a `resolution/duplicate` label (and oh it will need a `kind/enhancement` too) then feel free to close!
