### ISSUE TITLE
on /product/, all the link offs to docs and other pages should open in a new window rather than in the existing window

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#77]
originally reported by @gthuang 

on /product/, all the link offs to docs and other pages should open in a new window rather than in the existing window

**Comment by leezen** [comment]
@susanev Are you saying that that is the desired behavior to open in a new window? Though I'm a UX noob, but these are all within the same site, so it would feel odd to me?

**Comment by susanev** [comment]
talked with George about this, we are going to hold off if/when docs becomes a separate website, or if/when we receive user feedback.
