### ISSUE TITLE
Landing page has a gap on a large screen

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-hugo#86]
I have a 3840x2160 monitor and I open the website half-width full-height, this is what I see now:

![image](https://user-images.githubusercontent.com/1454008/115358901-6bd65980-a1be-11eb-99fe-72ffeb9d5fb3.png)

I think we could reduce the spacing between the top section and the bottom one to make it look better and fit more useful content.

I'm on a Mac/Firefox.

**Comment by susanev** [comment]
@kimberleyamackenzie would love your thoughts on this

**Comment by kimberleyamackenzie** [comment]
Yeah, I think maybe we just ought to define a max-height for the homepage hero.  I'll play around with some numbers and make a PR.

**Comment by susanev** [comment]
this was fixed.
