### ISSUE TITLE
github actions stack-name could use a note

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#863]
this came in from user feedback

https://www.pulumi.com/docs/guides/continuous-delivery/github-actions/
i believe this assumes ur in personal account for stack-name, and that if folks are in an org they need to add the org-name ahead of stack-name

i think we should either add a note or link to the stacks arch and concepts page

anyone else have better ideas?

**Comment by cnunciato** [comment]
Fixed via #2054.
