### ISSUE TITLE
Add Event Tracking for New User to 'All Web Site Data' GA Property

### ISSUE THREAD

**Issue by lindsaymarolich** [pulumi/pulumi-hugo#865]
We've got an event on our Pulumi Production GA property called '[New User](https://analytics.google.com/analytics/web/#/report/content-event-events/a116166038w172807111p173651817/_u.date00=20211001&_u.date01=20211011&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventCategory:All,analytics.eventAction:New%20User/)' which looks to be accurately tracking new signups.

Could we please fire this same event on our '[All Web Site Data](https://analytics.google.com/analytics/web/#/report/content-event-events/a116166038w270326820p241820757/_u.date00=20211001&_u.date01=20211011/)' GA property so that I can track signups across domains? This would really help with overall attribution.

**Comment by zchase** [comment]
I've add another Repeater destination for the Service's backend events. It is now pumping those events, including `New User` in to the `All Web Site Data` property. Closing.
