### ISSUE TITLE
Enable previews for PRs created from forks

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#869]
we dont create preview links for folks that open prs from forks
it would be helpful for reviewers to still be a ble to easily preview the changes
we may want to consider adding a way to make this happen

some eng notes from @cnunciato 
>the secrets we use to communicate with AWS (to deploy the previews to S3) aren’t available to them. there might be a way we can make this possible, but it’d likely require a pulumian to do it (like run some command in a PR comment)

**Comment by cnunciato** [comment]
Note that some workflows also skip PRs for branches that originate on other repos (e.g., in pulumi-hugo and registry), so we'd need adjust those to make them more lenient as well.

**Comment by susanev** [comment]
this came up again in an [internal slack convo](https://pulumi.slack.com/archives/C85BS3LJZ/p1646182213455379)

**Comment by susanev** [comment]
another [internal slack convo](https://pulumi.slack.com/archives/C02FXTZEZ6W/p1658506393984369) about this

**Comment by stack72** [comment]
This can't be supported unless we go for a /command style workflow - forks don't get access to any secrets

**Comment by cnunciato** [comment]
Closing as not possible given current preview architecture.
