### ISSUE TITLE
make docs search more prominent

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#883]
## what problem do we want to solve

- docs search is very easy to miss, it is visually very small and it scrolls off the screen if you scroll down in the left navigation
- community slack convos make it clear some folks do not know our docs has a search at all

## ux design recommendations
[ux designs in figma](https://www.figma.com/file/mkrb8VjlqzMjXLgAtZQBiA/docs-search?node-id=0%3A1)

### take up less space in the header, to focus on the docs content
- [x] remove the top navigation and replace it with the practitioner nav

### make search more prominent
- [x] move search up above the docs content
- [x] make the search always stay visible on the page as folks scroll (but don't fix the practitioner nav)
- [x] search button should open up the swift search dialog (enter should do this as well)

#### without scroll
![top](https://user-images.githubusercontent.com/5489125/144110063-7761f805-cb83-438b-bf58-df58663c7536.png)

#### with scroll
![scroll](https://user-images.githubusercontent.com/5489125/144110079-40edbe2d-dd7f-411e-9412-9da5163152dd.png)

_note: the behaviour on interaction with search should remain the same_

**Comment by susanev** [comment]
@lukehoban @cnunciato @zchase @kimberleyamackenzie would love yalls feedback on this proposal when you have time

**Comment by lukehoban** [comment]
I'm generally a big fan of improving search visibility.  My questions:
1. Interested in @zchase @lindsaymarolich feedback on potential impact of the top nav changes (reducing visibility of some core marketing pages from the `/docs` part of the site).
2. This looks like it fragments our top nav strategy even more - we'll now have rather different top nav in each of `/`, `/docs/` and `/registry/`.  That may be "right", but feels like potentially an opportunity to bring more consistency vs less?  For example, should we adopt this same search approach in the registry as well if this is the pattern we want to use?
3. I'd love to also do some investments in improving tuning of search results along with changes here.

**Comment by susanev** [comment]
i do really believe that folks rarely have a need to go out to the marketing pages once they are in the docs. all of the marketing pages are accessible from the practitioner nav in the logo dropdown if needed (e.g., pricing page)

that being said, i can pull out all of the nav changes to a separate issue if that would make it easier to make progress. that will mean a few things though...
- search will not be as prominent since our header currently is very large and quite dominant
- we will not be able to make search always visible and when folks scroll down it will be off page (this is because the current behaviour is to pin the top nav)

**Comment by susanev** [comment]
>This looks like it fragments our top nav strategy even more - we'll now have rather different top nav in each of /, /docs/ and /registry/. That may be "right", but feels like potentially an opportunity to bring more consistency vs less? For example, should we adopt this same search approach in the registry as well if this is the pattern we want to use?

what im proposing here aligns docs and registry. though i can push this even further to have a docs logo like registry and search. would love to be able to pin search in registry as what is being suggested here.

**Comment by zchase** [comment]
In regards to the visibility of the Marketing pages, IMO I think having the search more prominent and available is more important than the Marketing pages. My reasoning is that by the point a user is visiting our docs that they have already graduated above the content on the Marketing pages. @lindsaymarolich what do you think?

**Comment by Brant-Soler** [comment]
I like the view where the search bar is prominent, and I'm also a fan of including the regular nav above. I would feel more comfortable with both lines (logo & get started conversion button with the search box below with a white background) from the first screenshot sticking to the page as you scroll down through it. It's not as much a difference between where users will go while working through the content but that they have the ability to go anywhere from anywhere so we're not limiting their adventure toward conversion. 

Case in point: What if I am doing the research before contacting sales and I want to see what type of support documentation is available before we commit to an enterprise-level paid service?

Example attached.
![screenshot](https://user-images.githubusercontent.com/99282439/154565485-75d8e91d-591a-4064-964e-1dc67807b5d2.png)

**Comment by susanev** [comment]
@Brant-Soler i do not think we should pin the tertiary nav because most of the items in that nav take folks out of the docs if they interact with anything in that navigation.

**Comment by susanev** [comment]
there is not a return to top button, but that would be a great thing to add! we can include that in this work.

most users who come to the docs, want to stay in the docs, yes. secondarily, they may come to the docs trying to figure out how to get to registry (though that is going to be addressed in a separate project related to our docs landing page).

**Comment by susanev** [comment]
this is done.
metrics can be watched in https://github.com/pulumi/theme/issues/98
