### ISSUE TITLE
Missing permissions to Google Cloud Storage object after enabling uniform_bucket_level_access

### ISSUE THREAD

**Issue by fkalinski** [pulumi/pulumi-hugo#889]
File: [themes/default/content/docs/get-started/gcp/deploy-changes.md](https://www.pulumi.com/docs/get-started/gcp/deploy-changes/)

After performing the change, altering of index.html properties failed with error

```
  gcp:storage:BucketObject (index.html):
    error: 1 error occurred:
    	* Error when reading or editing Storage Bucket Object "index.html-b9e45f3": googleapi: Error 403: XXX@YYY.ZZZ does not have storage.objects.get access to the Google Cloud Storage object., forbidden
```

Looks like it's correlated with enabling uniform_bucket_level_access on the bucket as docs on https://cloud.google.com/storage/docs/uniform-bucket-level-access say

> Caution: If you enable uniform bucket-level access, you revoke access from users who gain their access solely through object ACLs and prevent users from administrating permissions using bucket ACLs. Be sure that you read considerations when migrating an existing bucket prior to enabling uniform bucket-level access.

Looks like the script should be updated to cover for it (add permissions for account owner through IAM binding)

**Comment by leezen** [comment]
I wasn't able to reproduce this. In many cases, it's a replace (due to the way the fields are marked). Even with an update, I was able to update the object. Could you please describe more about your auth setup?
