### ISSUE TITLE
Pulumi Service detail page

### ISSUE THREAD

**Issue by gthuang** [pulumi/pulumi-hugo#907]
## overview

Build a new page that describes what is the Pulumi Service, and what are its benefits and capabilities.

## design details

[ux designs in figma](https://www.figma.com/file/3ZlUfOhdfEzajjB6hLWtXE/pulumi-service-marketing-page?node-id=7%3A650)

[svgs in google drive](https://drive.google.com/drive/folders/1Z2RlN07GUq5WxdrCncYn2nT4f7qEEP5-?usp=sharing)

- [ ] top screenshot should use the same svg has our homepage
- [ ] key capabilities are slightly modified accordions where we show some text, and then expand to see even more text
    - [ ] expanded content can be found in the [service marketing page google doc](https://docs.google.com/document/d/1eRh5AOLHF0ONOq54q4IdfQ1wqyDgkbEVXj9GgFOx2q0/edit?usp=sharing) note that the rest of the content in that doc is out of date
- [ ] anywhere the service is mentioned on the homepage, product page, or pricing page we should like to this new page

**Comment by susanev** [comment]
@gthuang could you also plan to include a list of places you want to link to this page from?

**Comment by gthuang** [comment]
/product/, /pricing/, and the updated nav.

**Comment by susanev** [comment]
the updated nav is going to come in the new year.
so everywhere the service is mentioned that should be a link to this page, is that correct?

**Comment by gthuang** [comment]
yes, we can probably link to this page from most mentions of the Pulumi Service

**Comment by susanev** [comment]
@zchase i updated this with a link to a folder in google drive with 3 of the 4 svgs, ill hopefully get the last one done and added tomorrow am 🤞

**Comment by susanev** [comment]
k, everything is in there now, thank you!
