### ISSUE TITLE
weird mix of headings on the case studies page

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#920]
## overview

the case studies page has a weird mix of company names, or headings. i think we should standize what we want to do here instead of having a mix.

### screenshot
<img width="976" alt="Screen Shot 2021-12-20 at 9 29 09 AM" src="https://user-images.githubusercontent.com/5489125/146808053-e642db07-7bcb-4d89-b74d-ad3fc1f5c2be.png">

**Comment by susanev** [comment]
@gthuang @zchase thoughts on this?

**Comment by gthuang** [comment]
I recommend just listing the company name as the title for each case study on this page. We can leave the existing title as-is on the case study page itself.
