### ISSUE TITLE
consider linking to the core cloud provider registry api pages from the language pages in docs

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#927]
## overview

a community member suggested linking to the core cloud provider registry pages the language pages. or at least linking to registry from those pages. i think this is a good idea, anyone else have thoughts?

<img width="770" alt="community-convo" src="https://user-images.githubusercontent.com/5489125/147001317-b52bb073-a71a-4f3e-98d6-47bc5a0784ee.png">

**Comment by susanev** [comment]
@nimbinatus @cnunciato any thoughts on this?

**Comment by cnunciato** [comment]
Yep, I think this could work as a section, say, at the bottom of each of these pages (underneath a new heading) that linked to a language-specific pathway into the Registry -- e.g., by passing a `?language=go` param as the getting-started guides to today.

Given how high/intro-level these language pages are today, though, and that the Registry already does a good job of featuring providers like AWS so prominently, it might be better to have this new section just call out Registry, as you suggest -- "here's a bit about what Registry is, click here to explore Go packages", etc. -- than to link to a particular provider's API docs, which are generally less oriented toward guiding you through a process.
