### ISSUE TITLE
add edit this page functionality to learn lessons

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#937]
## overview
we had someone open a support ticket asking how they could submit spelling corrections to: https://www.pulumi.com/learn/building-with-pulumi/testing/

i believe Laura had a version with the right panel and edit this page functionality but i think it was dropped before launch. we should add it back in so folks can submit edits.

**Comment by cnunciato** [comment]
Closing as we've no further work planned for these layouts.
