### ISSUE TITLE
Reconsider the current ToC layout

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-hugo#947]
Our current ToC, especially in light of our recent API docs improvements, doesn't make the most impactful documentation as front as center as it should be. Further, it's fairly scattered.

For instance, if I want to learn about Pulumi's AWS support (or Azure, GCP, Kubernetes, etc) -- presumably the main pivot someone coming to our site -- there are many places to look:

* Getting Started > AWS
* Cloud Providers > AWS
* Cloud Providers > AWS > AWS Setup (subtly buried)
* Tutorials > AWS
* User Guides > Crosswalk for AWS
* API Reference > AWS (and there are actually two in here)

These are also separated vertically by quite a bit of distance in the ToC -- and our beautiful new provider docs are way down at the bottom, buried under the semi-boring "API Reference" heading.

An alternative approach would be to pivot around the cloud provider. For example:

* AWS (was Cloud Providers > AWS)
* AWS > Getting Started (was Getting Started > AWS)
* AWS > Setup (was Cloud Providers > AWS > AWS Setup)
* AWS > Tutorials (was Tutorials > AWS)
* AWS > User Guide (was user Guides > Crosswalk for AWS)
* AWS > Provider Reference (was API Reference > AWS)

This feels like it would significantly simplify overall navigation and also tighten up the left nav. Obviously, for clouds other than those four, we'd need an "Other Providers" catch-all section, but I assume we'd retain the overall structure beneath (getting started, setup, tutorials, reference, etc).

We do need to be careful that Getting Started doesn't suffer. The primary advantage to our current approach is that we really do make it easy and smooth to get up and running without getting lost.

**Comment by susanev** [comment]
@anita-trimbur just found this old issue in case its helpful to you
