### ISSUE TITLE
Committing encrypted secrets to source control

### ISSUE THREAD

**Issue by holwech** [pulumi/pulumi-hugo#950]
File: [themes/default/content/docs/intro/concepts/secrets.md](https://www.pulumi.com/docs/intro/concepts/secrets/)

This is both a question and a request for a change, you could say. Is it safe to commit the encrypted(?) secret (e.g. the key `secure: xxxx`) to source control? Whether, it is ok to do or not, should in my opinion be stated more clearly in the docs. I don't think it's mentioned anywhere in the docs how the pulumi config files should be handled wrt. to source control and secrets.

**Comment by rawkode** [comment]
Hi @holwech,

> Is it safe to commit the encrypted secret to source control?

💯. We encourage you to commit the stack files to source control.

We'll update the docs to be much more explicit about this. We'll also ensure we provide some information on how these values are kept safe while doing so.
