### ISSUE TITLE
aws quick starts blog preview is much longer than the other previews

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#952]
noticed the aws quick starts blog has a much longer preview than the rest.. not sure whats going on
https://www.pulumi.com/blog/

<img width="793" alt="Screen Shot 2022-01-05 at 7 58 27 PM" src="https://user-images.githubusercontent.com/5489125/148326137-4eb8a70b-cda4-4722-9e42-93afaab6d7bd.png">

**Comment by susanev** [comment]
@cnunciato do you know whats up with this?

**Comment by cnunciato** [comment]
Not offhand, will take a look.
