### ISSUE TITLE
Node.js SDK docs direct folks to homepage for CLI install

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#958]
File: [themes/default/content/docs/reference/pkg/nodejs/pulumi/pulumi/_index.md](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/)

On this page we direct folks to the homepage to install the CLI  (`This SDK is meant for use with the Pulumi CLI. Please visit pulumi.com for installation instructions.`) which doesn't seem quite right since we don't have CLI installation instructions on that page.

Should we be sending them to https://www.pulumi.com/docs/get-started/install/ instead?

**Comment by cnunciato** [comment]
Yes! Submitted a lil' fix for it. Good spot.
