### ISSUE TITLE
[Docs] Matrix of supported versions and languages

### ISSUE THREAD

**Issue by nimbinatus** [pulumi/pulumi-hugo#964]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

One common question is which version of a language we support. A page with a support matrix of all of the languages and versions in one place would be very helpful to have and may reduce confusion. We could have a simple table, or we could go bigger with a grid like Node's release support version timeline.

### Affected area/feature

Docs

**Comment by cnunciato** [comment]
> [cnunciato](https://github.com/cnunciato) changed the title [Docs] Matrix of supported versions and languages

🤦 oops.

**Comment by Brant-Soler** [comment]
Would it be possible to add a second dimension to this where we identify for internal purposes which technologies work together and which do not? 

It would be really helpful to create advertising-focused value-based content for each of the components and dynamically populate a set of pages on the front of the website for each combination of technologies.

The intent here is to target searches for technology combinations. This can be broken into separate issues if necessary. Ideas?

**Comment by cnunciato** [comment]
Since we now provide this information at the top of each language page, I'll close this now, but feel free to reopen if necessary. (Also, 👋!)
