### ISSUE TITLE
Review Hugo security options for 0.91 and above

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-hugo#972]
## Issue details

[Huge v0.91](https://github.com/gohugoio/hugo/releases/tag/v0.91.0) added a security section to harden the build runtime. These settings prevent building & serving the site locally on the latest releases. This is at least partially resolved by #971, but a fuller review should occur.

### Steps to reproduce

1. Install Hugo latest
2. `make build`
3. See errors like:

  ```
  ERROR 2022/01/13 23:52:35 render of "page" failed: execute of template failed: template:
blog/single.html:3:7: executing "blog/single.html" at <partial "head.html" .>: error calling
partial: "/home/friel/c/pulumi/pulumi-hugo/themes/default/layouts/partials/head.html:131:33":
execute of template failed: template: partials/head.html:131:33: executing "partials/head.html" at
<getenv "ASSET_BUNDLE_ID">: error calling getenv: access denied: "ASSET_BUNDLE_ID" is not
whitelisted in policy "security.funcs.getenv"; the current security configuration is:
```

**Comment by cnunciato** [comment]
Note that our scripts currently assume (and should be checking, in `ensure.sh`) that you're on Hugo 0.82 locally, as that's the version we currently run in CI.

**Comment by cnunciato** [comment]
@AaronFriel Is there anything more to be done on this? I've updated :all-the-hugos: and the website is currently on 0.92, which uses the config changes you added in #971. Ok to close?

**Comment by AaronFriel** [comment]
@cnunciato a quick perusal of [Hugo's security model](https://gohugo.io/about/security-model/) suggests we should be good with the defaults. Looks good to me!

**Comment by cnunciato** [comment]
Awesome, thanks again for the nudge forward on this. 🍻
