### ISSUE TITLE
Get Started should offer a clearer pathway to creating a service account

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/pulumi-hugo#994]
## Overview
"Get Started" is the primary CTA from our homepage and as such gets significant traffic. While we want visitors to be assured the Pulumi CLI can be used without a service account, visitors should also have an earlier opportunity to learn that a free SaaS is available to them and what it can do.

As its stands, it take four clicks (Get Started > Cloud provider of choice > Before You Begin > Create a New Project) before there's mention that the service exists. We can direct more traffic to the sign-up page by creating additional pathways from Get Started to account registration that emphasize both the optionality and add-value of the SaaS. 

[Related Epic](https://github.com/pulumi/home/issues/1774)

**Comment by anita-trimbur** [comment]
## Constraints
- Page 1 of Get Started does not conceptually differentiate "Pulumi" from "Pulumi CLI" or "Pulumi Service" 
- Information about the Service should never supersede guidance for getting started with the CLI
- Existing language in our documentation articulates the Service's add-value for orgs rather than individual accounts
- Lack of information about the benefits of the Service could diminish user trust in the platform

**Comment by anita-trimbur** [comment]
## Proposed Addition

I'm proposing an additional subsection on the first page of Get Started that references the Service as part of our platform, its general purpose, our editions, and includes a create account button. This would appear beneath the video walkthrough, as modeled in [this Figma file](https://www.figma.com/file/riI9WrMVNaLalRSTrA8XXA/Add-Create-Account-pathway-from-Get-Started?node-id=0%3A1). Although many visitors may not even scroll down far enough to see this subsection, I think its worthwhile to mention our Service on one of our most high-traffic pages. If we want to position the Service as a trustworthy part of our platform, it's important we make users aware of it early. Being that the SaaS is not mentioned on the homepage, the addition here is only an initial movement in that direction.

![Group 1](https://user-images.githubusercontent.com/97129308/155803194-b2a5f981-3773-4de7-b574-bcaf28395cd3.png)

## Next Steps
- [ ] Align with Luke on proposal
- [ ] Connect with marketing on proper content

**Comment by gthuang** [comment]
I've updated the Figma with recommended copy for that section.

> The Pulumi Service is a fully managed service that helps you adopt Pulumi’s open source SDK with ease. It provides built-in state and secrets management, integrates with source control and CI/CD, and offers a web console and API that make it easier to visualize and manage infrastructure. It is free for individual use, with features available for teams.

For the CTA button under the text, I recommend having it say "Start a free trial" and entering the 14-day trial flow. cc @lindsaymarolich @zchase for visibility on this.

**Comment by gthuang** [comment]
In the "Additional resources" section, should we also provide a link to Pulumi Learn https://www.pulumi.com/learn/ ?
