### ISSUE TITLE
Add png downloads to brand page

### ISSUE THREAD

**Issue by aaronkao** [pulumi/pulumi-hugo#996]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Current brand page (https://www.pulumi.com/brand/) only has SVGs to download. Would like to have PNGs for external users that are less design inclined.

**Comment by susanev** [comment]
oh @cnunciato, Aaron messaged me about this, did he also message you? happy for you to take this if you'd prefer.

**Comment by cnunciato** [comment]
@susanev Feel free to take it if you like -- I think this was filed before we synced up about this stuff, so I just took it assuming I'd do it. Up to you.

**Comment by susanev** [comment]
cool ill do it today, i honestly totally forgot and meant to do it last week.
